### ISSUE TITLE
Problem of BonusPack tuto when porting in Android Studio 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MKergall/osmbonuspack#106]
```
What steps will reproduce the problem?
1. Integration of OSMBonusPack tuto in Android Studio environment


What is the expected output? What do you see instead?
- in Eclipse IDE : no problem
- Android Studio : trouble with RoadManager and OSM API (road is not loaded, 
and waypoints not found ...)
"Error when loading the road"
"Error when loading KML"

see : attached snapshot (I can not attach the project ... too big)

What version of the products are you using (Android SDK, osmdroid,
OSMBonusPack)?
OsmBonusPack 5.1

Please provide any additional information below.


```

Original issue reported on code.google.com by `courd...@gmail.com` on 24 Jan 2015 at 9:10

Attachments:
* [device-2015-01-24-220303.png](https://storage.googleapis.com/google-code-attachments/osmbonuspack/issue-106/comment-0/device-2015-01-24-220303.png)

**Comment by k3b** [comment]
At https://github.com/k3b/LocationMapViewer you find an example of a working gradle/androidstudio app that use a local copy of osmbonuspack. 

In the next days i will try to port my gradle build to this repository. (see #118)

**Comment by MKergall** [comment]
Issue was linked to the well-known problem about network calls - not to the port on Android Studio. 
And port to Android Studio is now available in the main repo. 
=> Closing issue.
