### ISSUE TITLE
Maven Central or jCenter Publication

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MKergall/osmbonuspack#108]
```
It would be nice to have an easy-accessible dependency. If you are not familiar 
with it, this change will allow a very nice dependency resolving mechanism for 
this library: 
https://developer.android.com/tools/building/configuring-gradle.html

Also, this will allow you to remove binaries from the source code (the 'libs' 
directory). It will require to migrate the library to Gradle or Maven though.
```

Original issue reported on code.google.com by `artur.dr...@gmail.com` on 26 Jan 2015 at 3:34

**Comment by spyhunter99** [comment]
I'll vote for this too. Definitely need to include the dependencies in the published pom

**Comment by ming13** [comment]
Hey, it was me! Subscribing.

**Comment by Phantast** [comment]
I also vote for that. Please include it in MavenCentral. I cannot publish my app SmartNavi in F-Droid, as long as the OSMBonusPack is a local library. Can we expect this to be done in the near future? Regards and thanks for your effort in OSMBonusPack!

**Comment by spyhunter99** [comment]
+1

**Comment by larsgrefer** [comment]
How about https://jitpack.io/#MKergall/osmbonuspack
It's very easy to use

**Comment by spyhunter99** [comment]
would you take a PR for this? @MKergall
