### ISSUE TITLE
Migrate to GitHub

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MKergall/osmbonuspack#116]
```
Are there any plans to migrate this project to GitHub?
```

Original issue reported on code.google.com by `ziem1...@gmail.com` on 25 Mar 2015 at 8:37

**Comment by MKergall** [comment]
Update: 
1) Migrate to GitHub (pushed by Google Code planned shutdown) => done
2) Migrate to Android Studio => done
3) Migrate to Maven => Migrate to Gradle, done. 
4) And publish on Maven Central => still to do.
