### ISSUE TITLE
migrate to gradle build

### ISSUE THREAD

**Issue by k3b** [MKergall/osmbonuspack#118]
currently there is no gradle build support if you want to locally build from android-studio.

i have alredy implemented this in https://github.com/k3b/LocationMapViewer which contains a local copy of osmbonuspack because currently there is no gradle source at Maven Central or jCenter (see issue #108 )

**Comment by MKergall** [comment]
Gradle build now available. 
Lib available as an AAR in release v5.2. 
"How to install" instructions have been updated.
