### ISSUE TITLE
The Tutorials are not clear

### ISSUE THREAD

**Issue by SilverFoxA** [MKergall/osmbonuspack#121]
Sir, I am trying to use the POI functionality and i'm following your tutorial but i can't find how do you set the "pois"

**Comment by MKergall** [comment]
Could you be more precise?

**Comment by SilverFoxA** [comment]
Sir, i have tried the exact solution mentioned in the tutorial for the `Point of Interest` but the `pois` will always return null for me wherever i put the co-ordinates to, its always null

**Comment by MKergall** [comment]
Please provide the relevant piece of your code. 
Also look at your logcat, and provide the url that is (should be after: "NominatimPOIProvider:get:")
And if you have an error or a stacktrace in your logcat, provide it.

**Comment by SilverFoxA** [comment]
MapView mMapView= (MapView) v.findViewById(R.id.mapview);
        locationManager = (LocationManager) getActivity().getSystemService(Context.LOCATION_SERVICE);
        locationManager.requestLocationUpdates(LocationManager.GPS_PROVIDER, 5000, 10, this);
        GeoPoint geoPoint= new GeoPoint(37.439974,-119.003906);
        mMapView.setBuiltInZoomControls(true);
        mMapView.getController().setCenter(geoPoint);
        mMapView.getController().setZoom(5); //set initial zoom-level
        mMapView.setUseDataConnection(true);
        mMapView.setMinZoomLevel(5);
        double north = 84;
        double east = -180;
        double south = -84;
        double west = 180;
        BoundingBoxE6 boundingBoxE6 = new BoundingBoxE6(north, east, south, west);
        mMapView.setScrollableAreaLimit(boundingBoxE6);
        mMapView.setMultiTouchControls(true);
        Marker marker= new Marker(mMapView,mResourceProxy);
        marker.setPosition(geoPoint);
        mMapView.getOverlays().add(marker);//sets the marker
        NominatimPOIProvider poiProvider = new NominatimPOIProvider();
        ArrayList<POI> pois = poiProvider.getPOIInside(boundingBoxE6,"ATM",1000);    //.getPOICloseTo(geoPoint, "cinema", 50, 0.1);
        FolderOverlay poiMarkers = new FolderOverlay(getActivity());
        mMapView.getOverlays().add(poiMarkers);
        Drawable poiIcon = getResources().getDrawable(R.drawable.marker_poi_default);
        if (pois != null) {
            for (POI poi : pois) {
                Marker poiMarker = new Marker(mMapView);
                poiMarker.setTitle(poi.mType);
                poiMarker.setSnippet(poi.mDescription);
                poiMarker.setPosition(poi.mLocation);
                poiMarker.setIcon(poiIcon);
                if (poi.mThumbnail != null) {

                    poiItem.setImage(new BitmapDrawable(poi.mThumbnail));
                }
                poiMarkers.add(poiMarker);
            }
        }else{
            Toast.makeText(getActivity(),"null",Toast.LENGTH_SHORT).show();
        }
        mMapView.invalidate();

        //return mMapView;
        return v;

Here is the code that i have implemented but it won't display the POI as the `arraylist pois` is returning null and in  my app i can't downgrade it to api 3 or so

**Comment by MKergall** [comment]
Please also provide the logcat trace with the error message.

**Comment by SilverFoxA** [comment]
sir, in logcat all i get is that the nomination data can not be recieved

**Comment by MKergall** [comment]
Provide it, it will be much more useful than speaking about it. 
You should have in the logcat a trace of the url sent to Nominatim.

**Comment by SilverFoxA** [comment]
Sir, here is my Logcat

    05-12 15:22:52.813    5980-5980/com.package.myapplication E/BONUSPACK﹕ NominatimPOIProvider: request failed.

**Comment by MKergall** [comment]
And the url?

**Comment by SilverFoxA** [comment]
Sir, there's no link.. all i got is those two

**Comment by SilverFoxA** [comment]
Ok the url, i'm sorry i was looking for it in different area

    NominatimPOIProvider:get:http://nominatim.openstreetmap.org/search?format=json&q=[ATM]&limit=1000&bounded=1&viewbox=180.0,84.0,-180.0,-84.0
    05-13 19:08:24.193    2357-2564/com.package.myapplication D/skia﹕ --- SkImageDecoder::Factory returned null

**Comment by SilverFoxA** [comment]
![error](https://cloud.githubusercontent.com/assets/6983070/7612885/1fe8ab3e-f9ab-11e4-9433-27b2f9189510.png)


Ok what i understood is it's not taking the entire link, it's stoping before completing the entire link 
Plz help me out sir

**Comment by MKergall** [comment]
Your code seems correct, and the url produced is working fine (easy to verify with any browser). 
The error you get is quite strange: 
"Invalid response from server: HTTP/1.1 403 Forbidden"

On the other side, I just checked again POI search with Nominatim service in the OSMBonusPackTuto project, and it was working fine. 
You may have a configuration issue in your project. 
Could you specify: 
- Android target SDK used
- OSMBonusPack and osmdroid versions used
- Android SDK version of the device you are using. 

By the way, you are apparently searching for ATM on the whole world... Note that Nominatim returns a maximum of 50 results... You should narrow a little bit.

**Comment by SilverFoxA** [comment]
sir, I'm using Osmdroid  v 4.3 and OsmBonuspack v 5.1 target sdk is 22 and the android sdk i am using the latest

**Comment by ismaelrami** [comment]
Hello sir please help i have the same problem with GeocoderNominatim.getFromLocationName()

**Comment by MKergall** [comment]
Same questions than for SilverFoxA: please provide relevant piece of code, url produced (from logcat), the stack trace, and versions used (Android target and Android device version, OSMBonusPack and osmdroid versions).
