### ISSUE TITLE
Kml Line Color support?

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#122]
I'm trying to import some kml that hasa <LineStyle><color>ff080808</color></LineStyle> elements in and the colors do not seem to be honored. Does the format of the color string need to be changed or updated in order to have render the appropriate color?

**Comment by MKergall** [comment]
KML colors are supposed to be honored. 
If not, please provide the KML file and explain which color is not correct. 
Take care that in your kml file, KML color format is "aabbggrr" (not similar to usual Android color string). You can refer to KML doc.

**Comment by MKergall** [comment]
Can this issue be closed?

**Comment by spyhunter99** [comment]
I think so. I'm using another open source library to generate kml. It spits out "ffffffff" color codes. I "fixed" it by looping through all intrepreted bonuspack folderoverlays, replacing the colors with an android color. I'm still not sure what the issue was, but it's working with the code I have now.

**Comment by spyhunter99** [comment]
Nope, not working.
LineStyle/color/ff00ff00 renders as black

**Comment by spyhunter99** [comment]
failing input

<Folder id="c1c95cbf-68fa-42be-8704-3c4ccdd12f89"><name><![CDATA[Default Layer]]></name><visibility>1</visibility><Placemark><description><![CDATA[<b>Default Layer</b><br/>Very Course Sand]]></description><Style id="lineColor"><LineStyle><color>ff00b4ff</color><colorMode>normal</colorMode><width>3</width></LineStyle><PolyStyle><color>ff00b4ff</color><colorMode>normal</colorMode><fill>1</fill><outline>1</outline></PolyStyle></Style><MultiGeometry><Polygon><outerBoundaryIs><LinearRing><altitudeMode>clampToGround</altitudeMode><tessellate>1</tessellate><coordinates>-74.80285894,40.04829283 -74.79589908,40.03385055 -74.80738894,40.00362252 -74.83806325,39.99522585 -74.86519392,40.00059972 -74.88488128,40.00765293 -74.80285894,40.04829283 </coordinates></LinearRing></outerBoundaryIs></Polygon></MultiGeometry></Placemark></Folder>

**Comment by spyhunter99** [comment]
&gt;&lt;/description&gt;&lt;Style 

id=&quot;lineColor&quot;&gt;&lt;LineStyle&gt;&lt;color&gt;ff00b4ff&lt;/color&gt;&lt;colorMode&gt;normal&lt;/colorMode&gt;&lt;width&gt;3&lt;/width&gt;&lt;/LineStyle&gt;&lt;PolyStyle&gt;&lt;color&gt;

ff00b4ff&lt;/color&gt;&lt;colorMode&gt;normal&lt;/colorMode&gt;&lt;fill&gt;1&lt;/fill&gt;&lt;outline&gt;1&lt;/outline&gt;&lt;/PolyStyle&gt;&lt;/Style&gt;&lt;MultiGeometry&gt;&lt;Polygon&gt;&lt;

outerBoundaryIs&gt;&lt;LinearRing&gt;&lt;altitudeMode&gt;clampToGround&lt;/altitudeMode&gt;&lt;tessellate&gt;1&lt;/tessellate&gt;&lt;coordinates&gt;-

74.80285894,40.04829283 -74.79589908,40.03385055 -74.80738894,40.00362252 -74.83806325,39.99522585 -74.86519392,40.00059972 

-74.88488128,40.00765293 -74.80285894,40.04829283 

&lt;/coordinates&gt;&lt;/LinearRing&gt;&lt;/outerBoundaryIs&gt;&lt;/Polygon&gt;&lt;/MultiGeometry&gt;&lt;/Placemark&gt;&lt;/Folder&gt;

**Comment by MKergall** [comment]
OK, there is an issue with the inline Style. 
I will look at it. In the meantime, if you set your Style as a ShareStyle, it should work:


<?xml version='1.0' encoding='UTF-8'?>
<kml xmlns='http://www.opengis.net/kml/2.2'>
<Folder id="c1c95cbf-68fa-42be-8704-3c4ccdd12f89"><name><![CDATA[Default Layer]]>
</name><visibility>1</visibility>
<Placemark><description><![CDATA[<b>Default Layer</b><br/>Very Course Sand]]>
</description>
<styleUrl>#lineColor</styleUrl>
<MultiGeometry><Polygon>
<outerBoundaryIs>
<LinearRing><altitudeMode>clampToGround</altitudeMode><tessellate>1</tessellate><coordinates>
-74.80285894,40.04829283 
-74.79589908,40.03385055 
-74.80738894,40.00362252 
-74.83806325,39.99522585 
-74.86519392,40.00059972
-74.88488128,40.00765293 
-74.80285894,40.04829283
</coordinates>
</LinearRing></outerBoundaryIs></Polygon></MultiGeometry>
</Placemark>
</Folder>
<Style id="lineColor">
<LineStyle><color>ff00b4ff</color><colorMode>normal</colorMode><width>3</width></LineStyle>
<PolyStyle><color>ff00b4ff</color><colorMode>normal</colorMode><fill>1</fill><outline>1</outline></PolyStyle>
</Style>
</kml>

**Comment by spyhunter99** [comment]
awesome. eagerly awaiting a fix ;)

**Comment by spyhunter99** [comment]
of if you know approximately where to look, i can look into it. unfortunately, i can't easily change the kml. It's generated at runtime (it's a long story)

**Comment by MKergall** [comment]
Yes, I know where it is. In [KmlDocument](https://github.com/MKergall/osmbonuspack/blob/master/OSMBonusPack/src/org/osmdroid/bonuspack/kml/KmlDocument.java), from line 544: 

			} else if (localName.equals("Style")){
				if (mCurrentStyleId != null)
					putStyle(mCurrentStyleId, mCurrentStyle);
				else {
					mCurrentStyleId = addStyle(mCurrentStyle);
					if (mKmlCurrentFeature != null){
						//this is an inline style. Set its style id to the KmlObject container:
						mKmlCurrentFeature.mStyle = mCurrentStyleId;
					}
				}
				mCurrentStyle = null;
				mCurrentStyleId = null;
			} else if (localName.equals("StyleMap")){

This was wrongly assuming that inline style was only when there was no style id. 
This simple change should fix the issue: 

			} else if (localName.equals("Style")){
				if (mCurrentStyleId != null)
					putStyle(mCurrentStyleId, mCurrentStyle);
				else {
					mCurrentStyleId = addStyle(mCurrentStyle);
				}
				if (mKmlCurrentFeature != null && mKmlCurrentFeature != mKmlRoot){
					//this is an inline style. Set its style id to the KmlObject container:
					mKmlCurrentFeature.mStyle = mCurrentStyleId;
				}
				mCurrentStyle = null;
				mCurrentStyleId = null;
			} else if (localName.equals("StyleMap")){

Not tested yet.

**Comment by spyhunter99** [comment]
that did it!

**Comment by MKergall** [comment]
Now included in release v5.2
