### ISSUE TITLE
Kml Placemarks

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#123]
I have a KML file with a placemark with a name, style, and point defined, however there's no Icon href. Is it possible to render the text on screen (of the value of the Placemark/name) or is there some other transform I can perform to get the text to render?

**Comment by MKergall** [comment]
No ready-to-use solution for that. 
First of all, you will have to subclass the Marker with a MarkerWithLabel class to display the marker title on screen. 
But then, you will want to use the KML Styler mechanism, and you will notice that you cannot use your MarkerWithLabel... 

What you can do is to parse the KML structure yourself (as OSMBonusPack does with the various buildOverlay methods), and create MarkerWithLabel objects when/as needed. 

An alternative: convince me to add an option on the Marker, to render the title on screen...

**Comment by spyhunter99** [comment]
I'd absolutely like to help convince you to do so :). I can probably donate some time to help and test. I have sample kmls that i can share too. osm+bonus pack rocks. We can chat offline if you want some more background info

**Comment by spyhunter99** [comment]
I dug a bit into it today. It looks like IconStyle, line 89, function styleMarker(Marker, Context) is the part where we would need to generate some kind of bitmap for rendering. Does that sound accurate or am i barking up the wrong tree?

**Comment by spyhunter99** [comment]
Another update. I modified Marker.setIcon to do a null check for the title, then create a bitmap drawable from the title text. Works! but with some whacky font sizing issues

**Comment by MKergall** [comment]
Your method (setting to the marker an icon bitmap with the text) is interesting, and gave me an other idea: 
Using a customized KML Styler (see [tutorial §13.2](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4)) you could in the styler#onPoint method set the marker icon with a bitmap containing the title text. 

This way, no need to implement something directly inside OSMBonusPack :-)

If you have troubles to show a text in a bitmap, look at RadiusMarkerClusterer#buildClusterMarker.  Note that Paint.setAntiAlias(true) is quite important for proper text quality.
