### ISSUE TITLE
maneuverType for GoogleRoadManager RoadNodes?

### ISSUE THREAD

**Issue by hrsalehi** [MKergall/osmbonuspack#125]
I'm getting my routing from GoogleRoadManager but all maneuverTypes from RoadNodes are 0 so I can't set an appropriate icon for it. can anyone help with this one?

**Comment by MKergall** [comment]
answered on [StackOverflow](http://stackoverflow.com/questions/30405009/osmbonouspack-maneuvertype-for-googleroadmanager-roadnodes).
