### ISSUE TITLE
KML issue

### ISSUE THREAD

**Issue by balduzzi85** [MKergall/osmbonuspack#126]
Hi,

i follow this guide:

https://code.google.com/p/osmbonuspack/wiki/Tutorial_4

and i try in my method onCreate this:

String url = "http://mapsengine.google.com/map/kml?mid=z6IJfj90QEd4.kUUY9FoHFRdE";

        mToolbar = (Toolbar) findViewById(R.id.toolbar_actionbar);
        setSupportActionBar(mToolbar);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        MapView map = (MapView) findViewById(R.id.map);
        map.setTileSource(TileSourceFactory.MAPNIK);
        map.setBuiltInZoomControls(true);
        map.setMultiTouchControls(true);

        Drawable defaultMarker = getResources().getDrawable(R.drawable.ic_run);
        Bitmap defaultBitmap = ((BitmapDrawable)defaultMarker).getBitmap();
        Style defaultStyle = new Style(defaultBitmap, 0x901010AA, 3.0f, 0x20AA1010);

        KmlDocument mKmlDocument = new KmlDocument();
        mKmlDocument.parseKMLUrl(url);

        FolderOverlay kmlOverlay = (FolderOverlay)mKmlDocument.mKmlRoot.buildOverlay(map, defaultStyle, null, mKmlDocument);

        map.getOverlays().add(kmlOverlay);

        map.invalidate();

        map.zoomToBoundingBox(mKmlDocument.mKmlRoot.getBoundingBox());

but i have this error:

06-04 12:45:26.964  14787-14787/it... W/System.err﹕ 4 [main] INFO org.osmdroid.views.MapView - Using tile source: org.osmdroid.tileprovider.tilesource.XYTileSource@1dd0edd2
06-04 12:45:27.039  14787-14787/it... W/GAV4﹕ Thread[main,5,main]: IllegalStateException getting Ad Id Info. If you would like to see Audience reports, please ensure that you have added '<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />' to your application manifest file. See http://goo.gl/naFqQk for details.
06-04 12:50:03.825  14787-14787/it... I/Process﹕ Sending signal. PID: 14787 SIG: 9
06-04 12:52:56.056  17142-17142/it... I/MultiDex﹕ VM with version 2.1.0 has multidex support
06-04 12:52:56.338  17142-17164/it... I/OpenGLRenderer﹕ Initialized EGL, version 1.4

**Comment by MKergall** [comment]
These error logs do not seem to be related to OSMBonusPack. 
Start by an app as simple as possible: remove all the KML and overlay-related code, and check if the OSM map is properly displayed on your screen.

**Comment by MKergall** [comment]
Note that map.zoomToBoundingBox can not be called in onCreate. 
This is a known osmdroid issue. 
https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4 has been updated about that issue.
