### ISSUE TITLE
The best practice to display over 4 thousand markers

### ISSUE THREAD

**Issue by key4625** [MKergall/osmbonuspack#127]
First of all thanks to the software made ​​available.

I used the cluster as defined in tutorial, but the system slow down. I'm thinking a way to view only the markers in the region displayed by the map , but I suspect that it is more heavy and I must reiterate every displayed map changed.

There is a simple way to better manager my POI? I've stored in the sqllite database.

**Comment by MKergall** [comment]
How many POI do you want to handle?

**Comment by key4625** [comment]
about 4 thousand..

**Comment by MKergall** [comment]
Hum... 
Is it OK when zooming out (most markers inside few cluster markers), and slowing down when you are zooming in (markers with no clustering)?

**Comment by key4625** [comment]
The biggest problem for me is loading from db.. I have divided on category, each category has his own cluster, and with an asynctask I can load one category at a time but each category contain more than 500 pois so I have long time for loading..

**Comment by MKergall** [comment]
Out of my scope I'm afraid. 
You may try to ask for suggestions on StackOverflow. 
But you will have to provide much more details about your context, as optimizations may be very specific.

**Comment by ziem** [comment]
@MKergall is right. But I came up with idea to combine [MapListener](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/events/MapListener.java) and [MapView#getBoundingBox()](https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java#L252).

When event finishes:
 * remove previous markers
 * get current boundingbox
 * query database for markers inside boundingbox
 * add new markers to map

On lower zooms (like 7, 8, ...) you can just query database for count and display number as one marker. 

PS: In general loading 500 pois shouldn't take longer than few seconds on modern device.

**Comment by MKergall** [comment]
Just a hint: 
If you are using InfoWindows (bubbles), take care to set the same InfoWindow to all markers. 
Creating an InfoWindow for each marker takes a while, and consumes a lot of memory.

**Comment by spyhunter99** [comment]
ziem, i do something similar with large marker counts. remove items from the map view that are out of bounds after the map has been panned and just queries based on zoom levels.

**Comment by k3b** [comment]
sqllite can do the marker grouping for you using sql "group by"

    public static QueryParameterParcelable getQueryGroupByPlace(double groupingFactor) {
        String SQL_EXPR_LAT = "((round((" + SQL_COL_LAT + " * " + groupingFactor + ") - 0.5) /"
                + groupingFactor + ") + " + (1/groupingFactor/2) + ")";
        String SQL_EXPR_LON = "((round((" + SQL_COL_LON + " * " + groupingFactor + ") - 0.5) /"
                + groupingFactor + ") + " + (1/groupingFactor/2) + ")";

        QueryParameterParcelable result = new QueryParameterParcelable();

        result.setID(QUERY_TYPE_GROUP_PLACE)
                .addColumn(
                        "max(" + SQL_COL_PK + ") AS " + SQL_COL_PK,
                        SQL_EXPR_LAT + " AS " + SQL_COL_LAT,
                        SQL_EXPR_LON + " AS " + SQL_COL_LON,
                        "count(*) AS " + SQL_COL_COUNT)
                .addFrom(SQL_TABLE_EXTERNAL_CONTENT_URI.toString())
                .addGroupBy(SQL_EXPR_LAT, SQL_EXPR_LON)
                .addOrderBy(SQL_EXPR_LAT, SQL_EXPR_LON);

        return result;
    }

you have to restrict this query to the current visible map area

    public static void addWhereFilterLatLon(QueryParameter parameters, double latitudeMin, double latitudeMax, double logituedMin, double logituedMax) {
        if (!Double.isNaN(latitudeMin)) parameters.addWhere(SQL_COL_LAT + " >= ?", DirectoryFormatter.parseLatLon(latitudeMin));
        if (!Double.isNaN(latitudeMax)) parameters.addWhere(SQL_COL_LAT + " < ?", DirectoryFormatter.parseLatLon(latitudeMax));
        if (!Double.isNaN(logituedMin)) parameters.addWhere(SQL_COL_LON + " >= ?", DirectoryFormatter.parseLatLon(logituedMin));
        if (!Double.isNaN(logituedMax)) parameters.addWhere(SQL_COL_LON + " < ?", DirectoryFormatter.parseLatLon(logituedMax));
    }


the grouping factor depend on the zoomlevel

    // the bigger the smaller the area
    private static final double GROUPFACTOR_FOR_Z0 = 0.025;
    public static final double getGroupFactor(final int _zoomLevel) {
        int zoomLevel = _zoomLevel;
        double result = GROUPFACTOR_FOR_Z0;
        while (zoomLevel > 0) {
            // result <<= 2; //
            result = result * 2;
            zoomLevel--;
        }

        if (Global.debugEnabled) {
            Log.e(Global.LOG_CONTEXT, "FotoSql.getGroupFactor(" + _zoomLevel + ") => " + result);
        }

        return result;
    }

taken from https://github.com/k3b/AndroFotoFinder/blob/FDroid/app/src/main/java/de/k3b/android/androFotoFinder/queries/FotoSql.java
