### ISSUE TITLE
Kml with error

### ISSUE THREAD

**Issue by DianeSoares** [MKergall/osmbonuspack#128]
Hi,

i follow this guide:

https://code.google.com/p/osmbonuspack/wiki/Tutorial_4

and i try in my method onCreate this:

String url = "http://mapsengine.google.com/map/kml?mid=z6IJfj90QEd4.kUUY9FoHFRdE";

      MapView map = (MapView) findViewById(R.id.map);
        map.setTileSource(TileSourceFactory.MAPNIK);
        map.setBuiltInZoomControls(true);
        map.setMultiTouchControls(true);
       
        String url = "http://mapsengine.google.com/map/kml?mid=z6IJfj90QEd4.kUUY9FoHFRdE";

        KmlDocument kmlDocument = new KmlDocument();

        kmlDocument.parseKMLUrl(url);

        FolderOverlay kmlOverlay = (FolderOverlay)kmlDocument.mKmlRoot.buildOverlay(map, null, null, kmlDocument);

        map.getOverlays().add(kmlOverlay);

        map.invalidate();

        map.zoomToBoundingBox(kmlDocument.mKmlRoot.getBoundingBox());

and return this error:

     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.osmdroid.util.BoundingBoxE6.getLatitudeSpanE6()' on a null object reference

**Comment by MKergall** [comment]
Remove the last line: 
    map.zoomToBoundingBox(kmlDocument.mKmlRoot.getBoundingBox());
and try again. I suspect an osmdroid issue (calling map.zoomToBoundingBox in onCreate).

**Comment by DianeSoares** [comment]
![captura de tela de 2015-06-09 08 51 37](https://cloud.githubusercontent.com/assets/10669222/8057100/d68ac2e4-0e84-11e5-8c1e-f5e83d96f1aa.png)

don't work for me...

**Comment by MKergall** [comment]
I don't agree: the map is displayed, the app doesn't crash anymore => it works now. 
Just zoom down to Paris, and you should see the KML elements.

**Comment by DianeSoares** [comment]
I use parseKMLFile and works...
Your update to zoom in tutorial 4 works.

Thanks for help me!
