### ISSUE TITLE
RoadOverlay become invisible sometimes and in some deeper zoom levels

### ISSUE THREAD

**Issue by hrsalehi** [MKergall/osmbonuspack#129]
After I used RoadManager and get RoadOverlay and adding it to the map ,when I am moving the map or zooming in ,sometimes the road suddenly become invisible (or deleted from the map) and by moving a little bit or decreasing zoom level It become visible again. What is the problem?

the road is visible:
![1](https://cloud.githubusercontent.com/assets/6253428/8050816/41e4e352-0e63-11e5-9990-50fc1874885e.png)

by moving or dragging the map a little bit to the right the road become invisible:
![2](https://cloud.githubusercontent.com/assets/6253428/8050820/4bd9fa3c-0e63-11e5-8fca-ecffa8413e09.png)

and road always become invisible in zoom levels deeper than 16
I'm using OsmBonousPack v5.1

**Comment by ziem** [comment]
You need to disable hardware acceleration:

     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
         mapView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
     }

**Comment by hrsalehi** [comment]
Thanks. It worked
