### ISSUE TITLE
need a listener in CacheManager (onDownloadComplete)

### ISSUE THREAD

**Issue by djdance** [MKergall/osmbonuspack#130]
I want to download two sets of tiles from two providers (MAPNIK and PUBLIC_TRANSPORT for example).
Of course I can download it manually one by one via cacheManager. 

But how to listen for 1-st downloading complete? CacheManager has no listener.
Please add it or give me another possibility, thanks.

**Comment by MKergall** [comment]
Most methods are public or protected. So I guess it should be feasible to sub-class the CacheManager, to add your listener in onPostExecute. 

If not feasible, change the CacheManager as you would need it, and submit your change.
