### ISSUE TITLE
RoadManager and new API MapQuest

### ISSUE THREAD

**Issue by balduzzi85** [MKergall/osmbonuspack#133]
Hi,

I follow the tutorial_1, and i try to use https://developer.mapquest.com with the library to draw the path, but not work.. there is no error but not draw the path from start point to the end point.

The problem maybe is the new api key from https://developer.mapquest.com? in my account i see this:

Consumer Key 	************
Consumer Secret 	**** 

code:

 RoadManager roadManager = new MapQuestRoadManager("myAPIKEY");

        ArrayList<GeoPoint> waypoints = new ArrayList<GeoPoint>();
        waypoints.add(startPoint);
        GeoPoint endPoint = new GeoPoint(mLat, mLng);
        waypoints.add(endPoint);

        roadManager.addRequestOption("routeType=fastest");

        Road road = roadManager.getRoad(waypoints);
        Polyline roadOverlay = RoadManager.buildRoadOverlay(road, getActivity());
        
        map.getOverlays().add(roadOverlay);
        map.invalidate();

**Comment by MKergall** [comment]
I just checked: on various trials, I got 2 timeout errors. All other trials were OK. 
Did you got a valid API key from MapQuest?

**Comment by MKergall** [comment]
No feedback for a while => assuming configuration issue.
