### ISSUE TITLE
Why is target android version 4?

### ISSUE THREAD

**Issue by vashisthg** [MKergall/osmbonuspack#135]
Target and compile android version should be kept to the latest version 22. 

Also keeping minSdkVersion to 4 is also not good. There aren't any such devices anymore.

**Comment by juliocotta** [comment]
Hey, I am a user of this library and I have to keep it running in Android 2.3. While min API 4 is no good, updgrade the min level to 15 without the need to do so is harmfull to the developers using it. A good configuration would be something like

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        minSdkVersion 9
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }

**Comment by MKergall** [comment]
From v5.3, minSdkVersion and compileSdkVersion set to 15.

**Comment by juliocotta** [comment]
Would you mind to explain why?

**Comment by MKergall** [comment]
@juliocotta 
Sorry, I missed your need to support Android 2.3! 
I will set minSdkVersion to 10 in next release.

**Comment by juliocotta** [comment]
Thanks man!

**Comment by MKergall** [comment]
minSdkVersion=10 now commited

**Comment by vashisthg** [comment]
On google play only 6% of the devices are at api level 10 or below http://developer.android.com/intl/zh-CN/about/dashboards/index.html

**Comment by juliocotta** [comment]
It changes from country to country and app to app, mine is 10%.

**Comment by larsgrefer** [comment]
`minSdk` should be as low as possible and `compileSdk` should be as high as possible

**Comment by MKergall** [comment]
compile and target now set to 23.
