### ISSUE TITLE
Not compilable with Java 7

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#137]
There's a number of references to HashMap.Entry within the source code that are actually private access only. These need to be change to Map.Entry to fix.

**Comment by MKergall** [comment]
I never test with Java 7... 
Could you provide the desired fixes? I will integrate them.

**Comment by spyhunter99** [comment]
sure thing

**Comment by spyhunter99** [comment]
i just did a clean checkout and it no longer compiles.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':OSMBonusPackTuto'.
> Could not resolve all dependencies for configuration ':OSMBonusPackTuto:_debugCompile'.
   > Could not find :OSMBonusPack-release:.
     Searched in the following locations:
         https://jcenter.bintray.com//OSMBonusPack-release//OSMBonusPack-release-.pom
         https://jcenter.bintray.com//OSMBonusPack-release//OSMBonusPack-release-.aar
         https://repo1.maven.org/maven2//OSMBonusPack-release//OSMBonusPack-release-.pom
         https://repo1.maven.org/maven2//OSMBonusPack-release//OSMBonusPack-release-.aar
         file:/Users/alex/osmbonuspack137/OSMBonusPackTuto/libs/OSMBonusPack-release-.aar
         file:/Users/alex/osmbonuspack137/OSMBonusPackTuto/libs/OSMBonusPack-release.aar
         file:/Users/alex/Library/Android/sdk/extras/android/m2repository//OSMBonusPack-release//OSMBonusPack-release-.pom
         file:/Users/alex/Library/Android/sdk/extras/android/m2repository//OSMBonusPack-release//OSMBonusPack-release-.aar
         file:/Users/alex/Library/Android/sdk/extras/google/m2repository//OSMBonusPack-release//OSMBonusPack-release-.pom
         file:/Users/alex/Library/Android/sdk/extras/google/m2repository//OSMBonusPack-release//OSMBonusPack-release-.aar
     Required by:
         osmbonuspack137:OSMBonusPackTuto:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by spyhunter99** [comment]
I commented out the tutorial project to work around it.

**Comment by MKergall** [comment]
Fix merged. Thanks! 
About Tuto Build Failure => build.gradle assumes the lib is named "OSMBonusPack-release.aar". I just changed to "osmbonuspack_v5.3.aar" (in line with the installation guide).
