### ISSUE TITLE
How to keep the polygon stroke width fixed regardless the zoom level

### ISSUE THREAD

**Issue by porryman** [MKergall/osmbonuspack#141]
Hello

I'd like to show always the polygon's stroke in the same size regardless the zoom level.

I've tried to figure out how to do it but I give up.

Any suggestion? 

Thanks

**Comment by MKergall** [comment]
Well, the polygon stroke has the same size (in pixels), regardless the zoom level... 

Do you want to have a stroke with the same "geographical" size (= larger in pixels when we zoom-in)?

If yes, you can sub-class it, and recompute the stroke at the beginning of the draw method, according  to the zoom level.
