### ISSUE TITLE
Reverse Geocoding is not working with use of Geocoder Nominatim java class.

### ISSUE THREAD

**Issue by Tamizharasu** [MKergall/osmbonuspack#143]
Hi I have tried to save/dispaly the current location name in Text Box (Edit text) with use Geo coder Nominatim.But the Geo coder Nominatim gives only null values for reverse geocoder.

**Comment by MKergall** [comment]
I just tried: it was working perfectly fine. 
Please provide much more details: SDK used, relevant code sample.

**Comment by MKergall** [comment]
No feedback - assuming configuration issue.
