### ISSUE TITLE
Displaying POi's in app from Database

### ISSUE THREAD

**Issue by aleesaeed** [MKergall/osmbonuspack#144]
MKergall, first of all thanks for the android library to build the map. I've created my own map.
Now I'm just stuck in a problem. I wanna make my own POI database for my app. But I didn't get any solution on my problem. My app will get the lan. and lon. from database and will show the marker in the map, I'm not able to do it. Please help me.

**Comment by MKergall** [comment]
Ask such request for help in StackOverflow. 
Be more explicit about your difficulty, as we cannot really understand currently what is blocking you.
