### ISSUE TITLE
Is there an event that detects the movement and move the camera, such as google onLocationChanged

### ISSUE THREAD

**Issue by manufuentescr** [MKergall/osmbonuspack#149]
Hello, I need to create a map that detect my movement, as it progresses on the map Points of interest are loaded, there is something?

like onLocationChanged event of google.

**Comment by spyhunter99** [comment]
I suppose you mean "Is there an event...". The answer is yes. It's baked into osmdroid (it mirrors the google map api v1)

**Comment by manufuentescr** [comment]
is an override method MapEventsOverlay?

for example

     @ Override public boolean singleTapConfirmedHelper (GeoPoint p)
     {
         Toast.makeText (this, "Tapped" Toast.LENGTH_SHORT) .Show ();
         InfoWindow.closeAllInfoWindowsOn (map);
         return true;
     }


I need to execute a process every time the person moves or changes location

Sorry for my bad English xD

**Comment by spyhunter99** [comment]
Sorry, I'm confused. You want an event to fire every time the device running your app moves?
https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/views/MapView.java

MapView.setMapListener

**Comment by MKergall** [comment]
Standard LocationListener.onLocationChange is fully available, you can use it. 
An example here: https://github.com/MKergall/osmbonuspack/blob/master/OSMNavigator/src/main/java/com/osmnavigator/MapActivity.java

Please use StackOverflow for requesting help.
