### ISSUE TITLE
Voice Navigation for Directions.

### ISSUE THREAD

**Issue by Tamizharasu** [MKergall/osmbonuspack#151]
Is there possible to give voice navigation for directions in osmbonuspack

**Comment by MKergall** [comment]
For each node, instructions are in RoadNode.mInstructions
You can use Android TextToSpeech to "say" these instructions as voice navigation.

**Comment by Tamizharasu** [comment]
How to do activate automatic voice navigation when navigator reaches the particular route node in directions?.

**Comment by Tamizharasu** [comment]
I have tried on setOnMarkerClickListener when user clicks the particular route node it will "say" the instructions.But I need automatic voice navigation when navigator reaches the particular node.

**Comment by MKergall** [comment]
There is no "navigation service" implemented in OSMBonusPack, to follow where the user is on the route, and to trigger instructions when the user reaches a node. If you need that, you will have to implement it. 

You may have a look at [OsmAnd](https://github.com/osmandapp/Osmand) - but it's not a lib, it's a complete application.
