### ISSUE TITLE
MapEventsReceiver Conflicts with Spinner.setOnItemSelectedListener

### ISSUE THREAD

**Issue by hoseinit** [MKergall/osmbonuspack#153]
Hi
I am struggling to add a MapEventsReceiver while I have a Spinner.setOnItemSelectedListener.
While Spinner's listener is enabled no event is received on the map by MapEventsReceiver.
Please guide me how to use these two simultaneously.

**Comment by MKergall** [comment]
Please ask questions on StackOverflow (osmdroid tag).
