### ISSUE TITLE
LGPL licensing in the Android ecosystem

### ISSUE THREAD

**Issue by somehibs** [MKergall/osmbonuspack#154]
Hi,

We're using OSMBonusPack as part of a commercial product, and I have lawyers chewing paper about how we might not meet LGPL compliance.
Android doesn't really play nice with LGPL, and I can appreciate and understand the moral reasons for LGPL (encourages users to add improvements to the code back to the library). I was wondering if you'd consider either changing the licenses or making an explicit statement that your JAR releases may be packaged with commercial Android apps WITHOUT distributing source code or the library as a separate APK or other hare brained schemes to comply with LGPL.

http://source.android.com/source/licenses.html#why-apache-software-license
http://blog.xebia.com/2014/10/10/the-lgpl-on-android/

Thanks,
Alex.

**Comment by MKergall** [comment]
Hi Alex, 

Your lawers are good - and not only at chewing papers: 
I didn't noticed this issue about providing final users a way to "update" their application with a modified version of an LGPL lib. 
Effectively, in the context of a commercial app on Android, this is a major issue. 

So, I added a chapter at the end of the project front page about licencing, stating that this LGPL constraint is discarded for this project. 
You can ask your lawyers if it's OK.

**Comment by paul-ridgway** [comment]
Nice, thanks.
