### ISSUE TITLE
Android 6 compatibility

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#157]
GridMarkerClusterer uses an API that no longer exists in Android 6

android.support.v4.util.LongSparseArray

**Comment by spyhunter99** [comment]
Android was also nice enough to remove apache httpclient from ADK too. so we also need to add 

android { userLibrary 'org.apache.http.legacy' } to the build file

**Comment by MKergall** [comment]
Effectively, for Android 6, apache httpclient removal has to be solved. 
But I've not found any issue around android.support.v4.util.LongSparseArray...

**Comment by larsgrefer** [comment]
I'd like to suggest to use okhttp (https://github.com/square/okhttp) as replacement for apache httpclient

**Comment by larsgrefer** [comment]
You are already using okhttp.
So this issue can be closed, can't it?

**Comment by MKergall** [comment]
apache httpclient now replaced by okhttp. Closing issue.
