### ISSUE TITLE
Can we have clickListener/onTap for Polygon to return list of polygon overlayed?

### ISSUE THREAD

**Issue by biratrai** [MKergall/osmbonuspack#159]
I am building an application with lot of polygons and some of which overlaps, hence I want to be able to know which Polygon is overlayed on map where I have clicked/tap.

**Comment by MKergall** [comment]
Call: Polygon.contains(MotionEvent event)

Now you will have difficulties to do this call, as whole osmdroid tap detection strategy is focused on ending at the first overlay for which onSingleTapConfirmed returns true. 
What you could do: a custom overlay similar to FolderOverlay, containing all your Polygons, and implementing onSingleTapConfirmed. But inside this onSingleTapConfirmed, you will check tap for ALL Polygons.
