### ISSUE TITLE
Clustering markers in imported kml file

### ISSUE THREAD

**Issue by andrejsoucek** [MKergall/osmbonuspack#160]
Is there any way to cluster the markers in FolderOverlay after importing a kml document by 
FolderOverlay kmlOverlay = (FolderOverlay)kmlDocument.mKmlRoot.buildOverlay(this, map, null, null, kmlDocument); ?

**Comment by MKergall** [comment]
Good point. The difficulty is that a Kml Folder can contain various overlays, not only Markers. 

A suggestion: 
After calling buildOverlay, parse recursively the resulting FolderOverlay, and: 
- if it contains only Markers, build a RadiusMarkerClusterer, put inside all those Markers, and return the RadiusMarkerClusterer. 
- if it contains other overlays, let as is (return this). 
- and for all FolderOverlays it contains, do a recursive call.

**Comment by sobolvb** [comment]
no solution yet?

**Comment by MKergall** [comment]
The proposed solution is applicable by all users. 
I don't think the choice to put KML markers in clusters should be the default mechanism.

**Comment by sobolvb** [comment]
@MKergall you wrote: "After calling buildOverlay, parse recursively the resulting FolderOverlay", I do not quite understand how to do this. In my case, after buildOverlay, I can’t access the type of objects in it and find out if it is a point or something else. 
May I have a little hint?

**Comment by MKergall** [comment]
little hints: 

<List>Overlay overlays = folderOverlay.getItems();
onlyMarkers = true;
foreach (Overlay overlay in overlays) {
    if (!(overlay instanceof Marker)){
      onlyMarkers = false;
      break;
    }
}
if (onlyMarkers)
   rebuild FolderOverlay as a RadiusMarkerClusterer...
