### ISSUE TITLE
Support Runtime Permission WRITE_EXTERNAL_STORAGE for Android 6

### ISSUE THREAD

**Issue by grote** [MKergall/osmbonuspack#161]
In order to use this library with apps that target Android 6 (API 23), it is necessary that this library supports getting the permission ```android.permission.WRITE_EXTERNAL_STORAGE``` at run-time. More information for how to do this, is available here:

https://developer.android.com/training/permissions/requesting.html

However, I am not sure how libraries typically handle this or whether they leave it to the user of the library to ask for the permission by documentation.

**Comment by MKergall** [comment]
Effectively, following the new behaviour with Android 6 and SDK >= 23, something should be done to check permissions at runtime. 

For WRITE_EXTERNAL_STORAGE => main place to check this permission at runtime is the tiles cache mechanism inside osmdroid. So the issue should be raised in osmdroid project. 

For ACCESS_FINE_LOCATION and ACCESS_COARSE_LOCATION => check to do inside MyLocationOverlay and GpsMyLocationProvider. osmdroid issue.

**Comment by spyhunter99** [comment]
It's already been covered in osmdroid sample app. Runtime permissions are
an application level thing, not an android library imo.

**Comment by grote** [comment]
Yes, I agree.

**Comment by MKergall** [comment]
OK, seen in the code (OpenStreetMapViewer MainActivity.java => checkPermissions()). 

I added an explanation in the osmdroid wiki How-to-use-the-osmdroid-library, mentionning which osmdroid-related permissions should be requested at runtime.
