### ISSUE TITLE
Wiki needs a minor fix

### ISSUE THREAD

**Issue by karussell** [MKergall/osmbonuspack#162]
The [wiki here](https://github.com/MKergall/osmbonuspack/wiki/WhichRoutingService#graphhopper) needs a minor fix as we've now a simple dashboard with a free package since a year. No manual intervention necessary :)

**Comment by MKergall** [comment]
OK, updated.

**Comment by karussell** [comment]
Thanks! BTW: the free packages are currently for development or none-commercial projects
