### ISSUE TITLE
Support for OSMDroid 5.0.1

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#165]
@MKergall just a heads up, OSMDroid 5.0.1 was cut today and should be in maven central + play store. It's unlikely that there will be issues with the upgrade of bonuspack but just in case there are, you know where to find me.

The task for this issue is really to confirm compatibility with bonus pack and to update dependencies as necessary. SLF4j is no longer needed, too

**Comment by MKergall** [comment]
OK, thanks for the notice. I will do the upgrade very soon.

**Comment by MKergall** [comment]
KO... 

I updated my build.gradle files, putting:
     compile 'org.osmdroid:osmdroid-android:5.0.1@aar'
     //compile 'org.slf4j:slf4j-android:1.6.1-RC1'

When compilling, all imports of osmdroid classes are in error. 
I searched for a while, I really don't understand what is the problem. 

I was using jcenter => osmdroid-android-5.0.1.aar is available. 
I tried moving to mavenCentral, same errors.

**Comment by spyhunter99** [comment]
looking at it now...

**Comment by spyhunter99** [comment]
i'll have a PR open shortly, the gradle files are the root problem you are seeing. however it's also not building

**Comment by MKergall** [comment]
Great job, thanks! 

Tested, it seems OK. 
Just one issue found so far: MapBox tile source is not working anymore. I will investigate later. 

OSMBonusPack V5.5 is now released.

**Comment by spyhunter99** [comment]
Anytime. It's a mutually beneficial problem set so I don't mind putting in
the time. The only changes made to that was the removal of the resource
proxy string in the constructor, which wasn't actually used anywhere

**Comment by rastikw** [comment]
Hello, after the update I cannot build OSMNavigator.
OSMNavigator/src/main/res/layout/main.xml references @drawable/btn_sharing, but it is not there.
Same for OSMNavigator/src/main/res/menu/option_menu.xml and @drawable/ic_menu_sharing.

**Comment by MKergall** [comment]
Sorry. Added now.
