### ISSUE TITLE
Polyline disapearing at low zoom level

### ISSUE THREAD

**Issue by MKergall** [MKergall/osmbonuspack#168]
Polyline disapears at low zoom level (typically zoom levels 15 to 18). 
Issue seems to start at osmdroid 5.0.1 / OSMBonusPack 5.5. 

Observed on Samsung with Android 4.1.2. 

Not observed at all using the emulator with Android 4.0.4

**Comment by MKergall** [comment]
Found: android:hardwareAccelerated="false" was not set.

**Comment by spyhunter99** [comment]
Is there a reason to set it to false? osmdroid has been set to true for
quite a while

**Comment by MKergall** [comment]
Yes: it is solving the issue. I've not identified the root cause. 

Some issues have been reported in the past related to HW accelerated mode: 
https://code.google.com/p/osmdroid/issues/detail?id=413
https://code.google.com/p/osmdroid/issues/detail?id=454 => related to PathOverlay.

**Comment by grote** [comment]
I'm seeing this issue as well. Rather than turning off hardware acceleration for the entire app, you can also turn it off for your map view like this:
```java
mapView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
```
However, I'd be interested in fixing the root cause, so I can remove this workaround.

**Comment by grote** [comment]
@spyhunter99 Has this been resolved with the move to osmdroid?

**Comment by spyhunter99** [comment]
I doubt it. Did you try setting it to non hardware accelerated?

**Comment by spyhunter99** [comment]
should be resolved in osmdroid v6.0.0 pending performance tests

**Comment by MKergall** [comment]
Now fixed in osmdroid.
