### ISSUE TITLE
PolyLine bug for long polylines

### ISSUE THREAD

**Issue by stellardeveloper** [MKergall/osmbonuspack#170]
There is a bug concerning long Polylines.  I already placed a screenshot on [issue 167](https://github.com/MKergall/osmbonuspack/issues/167#issuecomment-159042346).
Example: 
1) A geodetic = false Polyline from Chile (-44.0, -76.0) to Japan (+35.0, +140.0) will not cross the Pacific Ocean as expected  if the map is centered to the prime meridian. It will cross the Atlantic, Africa and Asia instead.
2) A  geodetic line between those points will draw two segments, which is correct. But they are connected by a horizontal line crossing the whole map.
3) Scroll the map to the North Atlantic to (+83, 0) at zoomLevel 1: The non-geodetic line will go south from Chile, crossing the southern map border and will reach Japan from North. 
The geodetic line will be dran in several  segments between  the upper and the lower map, which are  connected by vertical lines crossing the poles.

The cause of theses bug are the corrections in the method osmdroid.views.Projection.adjustForDateLine.

To fix the this bug, the Polyline.draw method should check, whether two following points are shifted by more than the half map size in X, corresponding to 180°, and whether lines are crossing the southern border of a map in y. 
My proposal for a new Polyline.draw method:

```
protected void draw (final Canvas canvas, final MapView mapView, final boolean shadow) {

    if (shadow) {
        return;
    }

    final int size = mPoints.size();
    if (size < 2) {
        // nothing to paint
        return;
    }

    final Projection pj = mapView.getProjection();
    final int halfMapSize = TileSystem.MapSize(mapView.getProjection().getZoomLevel())/2; // 180° in longitude in pixels
    final int southLimit  = pj.toPixelsFromMercator(0, halfMapSize*2, null).y;            // southern Limit of the map in Pixels

    // precompute new points to the intermediate projection.
    precomputePoints(pj);

    Point projectedPoint0 = mPoints.get(0); // points from the points list

    Point screenPoint0 = pj.toPixelsFromProjected(projectedPoint0, mTempPoint1); // points on screen
    Point screenPoint1;

    mPath.rewind();
    mPath.moveTo(screenPoint0.x, screenPoint0.y);

    for (int i = 1; i < size; i++) {
        // compute next points
        Point projectedPoint1 = mPoints.get(i);
        screenPoint1 = pj.toPixelsFromProjected(projectedPoint1, this.mTempPoint2);

        if (Math.abs(screenPoint1.x - screenPoint0.x) + Math.abs(screenPoint1.y - screenPoint0.y) <= 1
               || projectedPoint1.y == 0 ||  projectedPoint1.y == 0x3FFFFFFF) {
            // skip this point, too close to previous point or too close to pole
            continue;
        }

        // check for lines exceeding 180° in longitude, cut line into two segments
        if  (  (Math.abs(screenPoint1.x - screenPoint0.x) > halfMapSize) 
                // check for lines crossing the southern limit
                || (screenPoint1.y >= southLimit) != (screenPoint0.y >= southLimit)) {
            // handle x and y coordinates separately
            int x0 = screenPoint0.x;
            int y0 = screenPoint0.y;
            int x1 = screenPoint1.x;
            int y1 = screenPoint1.y;

            // first check x
            if  (Math.abs(screenPoint1.x - screenPoint0.x) > halfMapSize) {// x has to be adjusted  
                if (screenPoint1.x < mapView.getWidth() /2) { 
                    // screenPoint1 is left of screenPoint0
                    x1 += halfMapSize*2; // set x1 360° east of screenPoint1
                    x0 -= halfMapSize*2; // set x0 360° west of screenPoint0
                } else {
                    x1 -= halfMapSize*2;
                    x0 += halfMapSize*2;
                }                               
            }

            // now check y
            if ((screenPoint1.y >= southLimit) != (screenPoint0.y >= southLimit)) {
                // line is crossing from one map to the other
                if (screenPoint1.y >= southLimit) {                     
                    // screenPoint1 was switched to map below
                    y1 -= halfMapSize*2;  // set y1 into northern map
                    y0 += halfMapSize*2;  // set y0 into map below                      
                } else {
                    y1 += halfMapSize*2;
                    y0 -= halfMapSize*2;
                }               
            }
            mPath.lineTo(x1, y1);    
            mPath.moveTo(x0, y0);
        } // end of line break check

        mPath.lineTo(screenPoint1.x, screenPoint1.y);

        // update starting point to next position
        screenPoint0.x = screenPoint1.x;
        screenPoint0.y = screenPoint1.y;
    }

    canvas.drawPath(mPath, mPaint);
}   
```

This will solve wrong orientations of non-geodetic lines and will avoid connection lines crossing maps between the segments of geodetic lines. There is also inserted a check, whether a point is too close to the pole outside the Mercator map area.
However, especially in lower zoom levels, there might remain small line segments of geodetic lines distributed over several maps, which do not look fine, depending on zoom and scroll. 
This can be solved by drawing multiple lines, shifted by one map size. Just insert the following code after the canvas.drawPath call:

```
    if (repeatPath) {
        Path mPathCopy = new Path (mPath);
        mPathCopy.offset(-halfMapSize*2, 0);                 // create left shifted copy of mPath
        if (halfMapSize*2 < mapView.getWidth()) {      
            mPathCopy.addPath(mPath, halfMapSize*2, 0);      // add right shifted copy of mPath
        }
        if (halfMapSize*2 < mapView.getHeight()) {  
            mPathCopy.addPath(mPathCopy, 0,  halfMapSize*2); // duplicates mPathCopy one map south
            mPathCopy.addPath(mPath, 0, halfMapSize*2 );         // add right shifted copy of mPath
        }
        mPathCopy.addPath(mPath, 0, -halfMapSize*2);         // add up shifted copy of mPath
        canvas.drawPath(mPathCopy, mPaint);
    }
```

There is a public boolean repeatPath variable, which can be set to true to enable repeated drawings of the path. Setting this variable to false by default will block path repetition.

**Comment by stellardeveloper** [comment]
Related to the bug above is the behaviour of the method osmdroid.views.Projection.adjustForDateLine

I would like to suggest a modification which keeps points and lines together at lower zoomLevels, if the mapView height is exceeding the mapSize:

	protected Point adjustForDateLine (int x, int y, Point reuse) {
		final Point out = reuse != null ? reuse : new Point();
		out.set(x, y);
		out.offset(-mMapViewWidth / 2, -mMapViewHeight / 2);     //
		final int mapSize = TileSystem.MapSize(getZoomLevel());
		final int absX = Math.abs(out.x);
		final int absY = Math.abs(out.y);
		final int yCompare = mapSize > mMapViewHeight ? mapSize : mMapViewHeight;  // avoid too early vertical adjusting
		if (absX > Math.abs(out.x - mapSize)) {
			out.x -= mapSize;
		}
		if (absX > Math.abs(out.x + mapSize)) {
			out.x += mapSize;
		}

		if (absY > Math.abs(out.y - yCompare) && mMapViewHeight < 2* mapSize) {  // use yCorrection instead of mapSize
			out.y -= mapSize;
		}
		if (absY > Math.abs(out.y + yCompare) || mMapViewHeight >= 2* mapSize) {  // use yCorrection instead of mapSize
			out.y += mapSize;
		}
		out.offset(mMapViewWidth / 2, mMapViewHeight / 2);
		return out;
	}

**Comment by MKergall** [comment]
Excellent! I will test your fix and include. 
For osmdroid.views.Projection.adjustForDateLine fix, you should create an Issue on osmdroid project. You can provide a reference to this one so that the context/need is easy to understand.

**Comment by MKergall** [comment]
A doubt: is your fix still valid if the map is rotated with map.setMapOrientation() ?

**Comment by stellardeveloper** [comment]
The polyline fix is also working for rotated maps, as the "screen coordinates" are not really screen coordinates, but canvas coordinates. After calling the canvas.rotate (...) method  the whole stuff send to the canvas afterwards will be displayed rotated on the screen. 

The adjustForDateLine mehtod will get a non-fitting mMapViewHeight, which will not change with map.setMapOrientation(). But, in the worst case, it will work like it is working now :-)

**Comment by MKergall** [comment]
"There is also inserted a check, whether a point is too close to the pole outside the Mercator map area."
=> I don't understand the reason for this test. Which issue is it solving? 
Suppose I have the non-geodetic line (0, +90) to (0,-90) => it's going to draw nothing.

**Comment by MKergall** [comment]
"line cutting" and "repeat" commited. 
"check pole" not commited yet.

**Comment by stellardeveloper** [comment]
The Pole check was not correct, you are right. 
However, a non-geodetic line (0, +90) to (0,-90) will  draw nothing because the two points are often placed side by side,  one at the bottom of the upper map, the other at the top of the lower map, separated only by one pixel. The

       if (Math.abs(screenPoint1.x - screenPoint0.x) + Math.abs(screenPoint1.y - screenPoint0.y) <= 1) {
				// skip this point, too close to previous point
				continue;

will skip point number 1 in consequence.

I introduced the pole check, because a geodetic line exceeding the upper mercator map limits drew weird vertical lines and  partially ran along the sout pole.

**Comment by MKergall** [comment]
normally fixed now in osmdroid
