### ISSUE TITLE
R.drawable.marker_cluster

### ISSUE THREAD

**Issue by 2ndGAB** [MKergall/osmbonuspack#172]
Hello,

Excuse me but I don't understand why I have problem with R.drawable.marker_cluster which cannot be resolved in 5.5 version.

I'm surprised that I didn't see anything with such problem on Internet.

What do I miss?

**Comment by MKergall** [comment]
There is no default cluster marker in the lib. 
Just put a cluster marker in the drawable resources of your apk project.

**Comment by 2ndGAB** [comment]
Ah!
Is it possible to find a template somewhere?
