### ISSUE TITLE
Polyline should use IGeoPoint, not GeoPoint

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#179]

**Comment by MKergall** [comment]
Internally, Polyline do not use GeoPoints, but a matrix of int. This avoids creation of numerous objects. 
getPoints() cannot return IGeoPoints, it must return actual objects. 
setPoints() could get IGeoPoints. But why?

**Comment by spyhunter99** [comment]
It's just the common pattern used in osmdroid. When using the google maps
wrapper, the implementation is different

that said, I'm not sure if anyone actually uses it
