### ISSUE TITLE
Polyline gridlines don't render if both points are offscreen, even if it intersects the current view

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#180]
i'm attempting to use polylines to make a lat/lon and mgrs grid line overlay. I'm basically making lines every 10 degrees vertically and horizontally by creating a poly line with two points at opposite ends of the globe. When zooming in past a zoom level in which the whole globe is visible, the lines disappear. Is this an osmdroid issue or a bonus pack issue?

edit, i've also noticed similar issue when basically running the same process with more points. The sections of the lines that start off screen and end on screen are not visible.

**Comment by MKergall** [comment]
We have open issues on: 
- very long Polylines
- Polylines when poles are shown

See #167, #169, #170, #171. 
And also: https://github.com/osmdroid/osmdroid/issues/197

Code currently commited should solve most of them. 
You must also ensure you set android:hardwareAccelerated="false" in your app. 

All those issues also affect osmdroid PathOverlay.

**Comment by spyhunter99** [comment]
Gotcha. I actually found a work around for my particular use case. Listen to map movements and zoom events, then only create polylines that are without the current bounds of the view. I'm working pretty much off of master and still ran into the issue. I can record a short screen cast of this if you want.

Turning off hardware acceleration is not an option for me as I also have web views in the app. HA=off kills the performance of web views. It's shocking actually.

**Comment by spyhunter99** [comment]
I think it's actually two different issues. One is lines whose points are off screen but intersect the screen are not shown. The other is when the date line is visible, all polylines and polygons disappear until the date line is off screen again.

**Comment by spyhunter99** [comment]
Edit: it appears that vertical lines disappear, horizontal lines are ok

**Comment by spyhunter99** [comment]
yup it was my code. thanks for looking into this
