### ISSUE TITLE
gradle build fails with lint errors

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#181]
FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':OSMBonusPack:lint'.
  
  > Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.32 secs

with the following errors in the report
Correctness
1   Error InvalidPackage: Package not included in Android
Correctness:Messages
5   Error MissingTranslation: Incomplete translation

we either need to turn off the checks for those bits, or fix the problem

**Comment by MKergall** [comment]
obsolete
