### ISSUE TITLE
Add support for Mapzen Turn-by-Turn service

### ISSUE THREAD

**Issue by MKergall** [MKergall/osmbonuspack#186]
See https://mapzen.com/projects/valhalla

Supports most of expected features: 
- instructions with a good level of detail
- car, bike, pedestrian profiles
- alternate routes

Advice or interest about adding this service to OSMBonusPack will be welcomed.

**Comment by jpaseneta** [comment]
i was about to ask if this feature is already implemented, because i wanted to use osmbonuspack on my android app to be like somewhat a gps moving display in cars(like waze). Is it also possible to have a 3d zoom/rotate view?

**Comment by MKergall** [comment]
Not implemented yet, but you can use anyone of the 3 available routing services. Look at the tutorial. 
3D zoom/rotate view (tilting?) is not available under osmdroid.

**Comment by spyhunter99** [comment]
Minor clarification osmdroid can rotate the map, but not tilt.

**Comment by jpaseneta** [comment]
yep, i've already tried the mapquest road manager to give me routes. :+1:

**Comment by MKergall** [comment]
MapZen services shutdown.
