### ISSUE TITLE
Bad scaling for btn_moreinfo

### ISSUE THREAD

**Issue by arminus** [MKergall/osmbonuspack#188]
I'm using a CustomInfoWindow as documented in the tutorials. Works great, except that the btn_moreinfo is scaled way too big:

![2015-12-23_143933](https://cloud.githubusercontent.com/assets/683680/11977474/7feda056-a983-11e5-9c9f-4879454760bb.png)

Any ideas?

**Comment by MKergall** [comment]
Did you change the layout.xml? 
Which resolution?

**Comment by arminus** [comment]
No, I didn't change anything. Resolution is 768x1280 for the emulator screenshot.

**Comment by MKergall** [comment]
Obsolete? Reopen if still valid, with code sample.
