### ISSUE TITLE
2 questions on marker clustering

### ISSUE THREAD

**Issue by arminus** [MKergall/osmbonuspack#189]
1) Is it possible to zoom in on a click on a marker cluster?
2) What do I do when I have 2 POIs at exactly the same position? I've seen Leaflet based solutions where the cluster "explodes" the 2 markers into distinct clickable markers, any solution for something like that in this package?

**Comment by MKergall** [comment]
1) Answer is yes... but please use StackOverflow for advice. 
2) I also like the Leaflet "explode" mechanism. It's not implemented yet in OSMBonusPack.

**Comment by arminus** [comment]
ok, thanks.
