### ISSUE TITLE
Crash inside RoadManager

### ISSUE THREAD

**Issue by evansgelist** [MKergall/osmbonuspack#190]
Hi. After updating the library to version v5.6.1. I constantly have a crash in the code

    RoadManager roadManager = new OSRMRoadManager(getContext());
    roadManager.getRoad(mWayPoints);

Before that was the version v5.4 and everything was fine

Crash log
https://gist.github.com/evansgelist/a052481b4abbde9c087f
I will be glad of any help

**Comment by spyhunter99** [comment]
Looks like in infamous gradle aar transitive dependency bug.  You'll need
to add okhttp to your dependencies lost

**Comment by evansgelist** [comment]
thanks for the answer
I added
    compile 'com.squareup.okhttp:okhttp:2.7.0'
it works now
