### ISSUE TITLE
Android 6.0 Permissions

### ISSUE THREAD

**Issue by ZKjellberg** [MKergall/osmbonuspack#192]
The two applications do not implement the new Android 6.0 permissions.

1. OSMBonusPackTuto launches, but is unable to display tiles without storage access. Location set in the permissions, but I am unsure if this demo ever calls it.
2. OSMNavigator crashes on launch with a NullPointerException attempting to view storage.

**Comment by ZKjellberg** [comment]
For a sample implementation, here is [the osmdroid pemission code](https://github.com/osmdroid/osmdroid/blob/master/OpenStreetMapViewer/src/main/java/org/osmdroid/MainActivity.java#L86)

Both applications have very busy onCreate() methods which has me a bit unsure how to approach implementation. I'd recommend implementing some code checks to prevent the crashes, or move this code to a method and [use a similar approach to this permission check to execute the code](https://github.com/SandroMachado/openalpr-android/blob/master/Sample/OpenALPRSample/app/src/main/java/com/sandro/openalprsample/MainActivity.java#L122) Note the method takePicture() in both the checkPermission() & onRequestPermission.

**Comment by ZKjellberg** [comment]
Crash is restricted to the Location calls in OSMNavigator. This can easily be abstracted using the above code. I may attempt to fix this soon.

**Comment by MKergall** [comment]
Thanks for this feedback and the PR code. 
Fixes committed now: 
- OSMBonusPackTuto by targeting SDK 22 (the limit to avoid implementing new permissions granting)
- OSMNavigator by handling permissions.
