### ISSUE TITLE
RoadManager crash

### ISSUE THREAD

**Issue by Patrick7893** [MKergall/osmbonuspack#195]
Hi, i have a library version 5.6.1 and okhttp:2.7.0
got crash on:
RoadManager roadManager = new OSRMRoadManager(App.getContext());
 return roadManager.getRoad(waypoints);

But this crash get not always, only sometimes, i dont know what is the problem

Crash log: 

01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:299)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:  Caused by: java.lang.NullPointerException
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at org.osmdroid.bonuspack.utils.HttpConnection.getContentAsString(HttpConnection.java:90)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at org.osmdroid.bonuspack.utils.BonusPackHelper.requestStringFromUrl(BonusPackHelper.java:75)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoads(OSRMRoadManager.java:176)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:236)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at com.pkdevelopment.RusCabDriver.view.fragments.client.PreorderPlaceFragment$GetRoadLength.doInBackground(PreorderPlaceFragment.java:417)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at com.pkdevelopment.RusCabDriver.view.fragments.client.PreorderPlaceFragment$GetRoadLength.doInBackground(PreorderPlaceFragment.java:399)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:287)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:137) 
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230) 
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
01-08 13:39:35.210 4153-4704/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)

**Comment by Patrick7893** [comment]
also sometimes got this:

01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err: java.net.SocketTimeoutException
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at okio.Okio$2.read(Okio.java:139)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:79)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:909)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:93)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:894)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:748)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:277)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:79)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at org.osmdroid.bonuspack.utils.HttpConnection.doGet(HttpConnection.java:62)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at org.osmdroid.bonuspack.utils.BonusPackHelper.requestStringFromUrl(BonusPackHelper.java:74)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoads(OSRMRoadManager.java:176)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:236)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at com.pkdevelopment.RusCabDriver.view.fragments.client.MapRoutingFragment$3.run(MapRoutingFragment.java:146)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/System.err:     at java.lang.Thread.run(Thread.java:856)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver W/dalvikvm: threadid=21: thread exiting with uncaught exception (group=0xa6260288)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver E/AndroidRuntime: FATAL EXCEPTION: Thread-286
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver E/AndroidRuntime: java.lang.NullPointerException
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at org.osmdroid.bonuspack.utils.HttpConnection.getContentAsString(HttpConnection.java:90)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at org.osmdroid.bonuspack.utils.BonusPackHelper.requestStringFromUrl(BonusPackHelper.java:75)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoads(OSRMRoadManager.java:176)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:236)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at com.pkdevelopment.RusCabDriver.view.fragments.client.MapRoutingFragment$3.run(MapRoutingFragment.java:146)
01-08 15:36:46.618 7391-10808/com.pkdevelopment.RusCabDriver E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:856)

**Comment by MKergall** [comment]
I confirm: big issue with OSRMRoadManager (crash).

**Comment by MKergall** [comment]
OK, so we have 2 bad issues: 

1) OSRM Server API is currently completely down. I raised this issue: https://github.com/Project-OSRM/osrm-frontend-v2/issues/151

2) In this context, on OSMBonusPack side, OKHttp response can be null. This case was not checked in the code, causing an NPE. I just commited the fix (ab477aa37029ae3225ccb4d1254ddde3f2554ba3).

**Comment by MKergall** [comment]
OSRM Server API is working again.
