### ISSUE TITLE
How to display several MapsForge .map files?

### ISSUE THREAD

**Issue by 2ndGAB** [MKergall/osmbonuspack#196]
Hello,
I'm using the MapsForgeForOSMDroid module and I'd like to display several MapsForge .map files at the same time because France is cutted out in several regions.
I tried the code below. I don't know if it's the good way to it anyway, I have a problem with it.
When I zoom in and out, I briefly see all maps but I finally see only the last overlay because they are rendered with a with background instead of a transparent one.
So how to use several .map files?

And I also see that rendering such offline map seems to be slower than rendering online default one. Strange, why?

So my code is:

    boolean setMapsForgeTileProvider(){

        String path = Environment.getExternalStorageDirectory().getPath()+"/mapsforge/";
        File folder = new File(path);
        File[] listOfFiles = folder.listFiles();

        if (listOfFiles == null)
            return false;

        File mapFile = null;
        for (File file:listOfFiles){
            if (file.isFile() && file.getName().endsWith(".map")){
                mapFile = file;
                MapsForgeTileProvider mfProvider = new MapsForgeTileProvider(new SimpleRegisterReceiver(getActivity()), mapFile);
                final TilesOverlay tilesOverlay = new TilesOverlay(mfProvider, getActivity());
                tilesOverlay.setLoadingBackgroundColor(Color.TRANSPARENT);
                mMapView.getOverlays().add(tilesOverlay);
            }
        }

        if (mapFile == null)
            return false;

        mMapView.setUseDataConnection(false);
        return true;
    }

Before my application calls ``setMapsForgeTileProvider()``, it calls ``setStdTileProvider()`` below:

    void setStdTileProvider(){
        if ((mMapView == null) || !(mMapView.getTileProvider() instanceof MapTileProviderBasic)){
            GenericMapView genericMap = (GenericMapView) rootView.findViewById(R.id.mapview);
            MapTileProviderBasic bitmapProvider = new MapTileProviderBasic(getActivity().getApplicationContext());
            genericMap.setTileProvider(bitmapProvider);
            mMapView = genericMap.getMapView();
            mMapView.setTileSource(TileSourceFactory.MAPQUESTOSM);
        }
    }

Another question is about the ``mapsforge-map-0.3.1-SNAPSHOT-jar-with-dependencies`` you provide. It's a quite old and not released version. Do you plan to upgrade it?

 
Regards,
Alain

**Comment by MKergall** [comment]
Several .map files are not supported. Logically, you could build a map file with all regions needed. 

About the version => this MapsForge integration is experimental, done "quick and dirty" from this mapsforge-map-0.3.1-SNAPSHOT-jar-with-dependencies. 
I'm not fully convinced this osmdroid/MapsForge integration really makes sense...

**Comment by 2ndGAB** [comment]
Mapsforge support seems that's the only way to use offline maps no?

**Comment by spyhunter99** [comment]
Mapsforge is designed for offline use using their map file format. It renders the map tiles on device.

Personally, I like the osmdroid mapforge integration and I'd love it if it were maintained. Makes sense to me to have a common api for display map imagery, kml, points, etc.

**Comment by MKergall** [comment]
@2ndGAB 
With osmdroid, you can have offline maps using bitmap tiles packed in various formats (zip, sqlite, ...). Now, MapsForge map files are much much smaller. But also a little bit slow. 

@spyhunter99 
osmdroid/MapsForge integration has been based on work picked here: 
http://www.salidasoftware.com/how-to-render-mapsforge-tiles-in-osmdroid
http://www.sieswerda.net/2012/08/15/upping-the-developer-friendliness

This work should be done again on recent MapsForge versions. 
If you think it worth it, it could make sense to add it as a project in osmdroid, or in osmdroid-third-party. 
Current integration lacks interesting features: get map bounding box, and define a custom rendering.

**Comment by spyhunter99** [comment]
roger that

**Comment by 2ndGAB** [comment]
Hmm well, a wonderfull thing could be to port your ClusterManager implementation to MapsForge. Because the MapsForge one is really not fine...
Or to port the MapsForge MultiDataStore to OSMDroid....

**Comment by spyhunter99** [comment]
@2ndGAB I've reopened the ticket on osmdroid and made some progress already. The APIs are significantly different from @MKergall's implementation. I'm working on a few other osmdroid issues at the moment, but this one is next on the list. Provided it can be worked out, this will let you use osmbonuspacks clustermanager with osmdroid with mapforge's on device rendered map. That's the magic of open source

**Comment by 2ndGAB** [comment]
That's wonderfull spyhunter99

**Comment by spyhunter99** [comment]
@MKergall @2ndGAB good news! I was able to get it working. Two options....
I can open a PR to osmbonuspack and retaining the LGPL licensing since i based the adapter off of the code in this repo.

I can also push it to osmdroid. This complicates the licensing since osmdroid is ASF, with exceptions on 3rd party code and, at least the 3 class files that were adopted from the obp repo, would have to be LGPL licensed.

As a side note, I also contacted the original author to ask about licensing. Waiting for a response.

**Comment by spyhunter99** [comment]
received response from original author. it's license free. @MKergall if you don't want the burden of maintaining it, we can move it over to osmdroid's repo. Otherwise i can open a PR for here

**Comment by MKergall** [comment]
It makes sense to move it to osmdroid repo. 
But as third party: as it requires Mapsforge lib, it will increase the code size significantly.

**Comment by 2ndGAB** [comment]
@MKergall OK but waiting for an OSMDroid solution for embedded maps, I think it could be acceptable. An Mapsforge lib is in several parts. Maybe we only needs core and reader spyhunter99 no?

**Comment by spyhunter99** [comment]
Pushed to osmdroid branch 245. It won't make the next release, which should be today, but it will probably be in the following one. if you don't minding building from source @2ndGAB then you can give it a shot. See the example app. I've got it boiled down to nearly a 2 lines. Feel free to pick up the conversation on issue 245 with osmdroid. 

@MKergall i think the only action for you would be to optionally remove the mapsforge adapter from your branch and provide a pointer to where the newer stuff is. That's at your discretion.

**Comment by 2ndGAB** [comment]
@spyhunter99 ok, many thanks for this job. I'm going to try it.

**Comment by MKergall** [comment]
@spyhunter99 Yep. As soon as it's available in osmdroid, I will remove it from "OBP" :-) and link to the new stuff.

**Comment by rastikw** [comment]
You can check implementation at https://github.com/Arman92/Mapsforge-OsmDroid-GraphHopper, where the author used mapsforge 0.5.1. I think it already has all the changes from 0.3.1, so it can be used with current mapsforge lib. It uses different way of caching generated tiles than @spyhunter99. I've further updated it to my needs and I'm pretty happy with performance of the implementation.

**Comment by 2ndGAB** [comment]
@rastikw, does it use MultiMapDataStore?

**Comment by rastikw** [comment]
@2ndGAB originally no, but after replacing it with MultiMapDataStore, it works. But I run into same issues with RETURN_FIRST/RETURN_ALL as you mentioned in https://github.com/osmdroid/osmdroid/issues/245. I'll write more about the problem there.

**Comment by MKergall** [comment]
Mapsforge integration removed from OBP and moved to osmdroid, with various improvements (support multiple map files, support custom rendering, better performance).
