### ISSUE TITLE
Why i can't display kml file?

### ISSUE THREAD

**Issue by paulskvortsov** [MKergall/osmbonuspack#197]
Hi @MKergall 
I'd try to draw route from kml file but it didn't work. My code looks like in your example:
```
KmlDocument kmlDocument = new KmlDocument();
kmlDocument.parseKMLUrl(url);
FolderOverlay kmlOverlay = (FolderOverlay) kmlDocument.mKmlRoot.buildOverlay(detailsTrackMap, null, null, kmlDocument);
detailsTrackMap.getOverlays().add(kmlOverlay);
detailsTrackMap.invalidate();
BoundingBoxE6 bb = kmlDocument.mKmlRoot.getBoundingBox();
detailsTrackMap.getController().setCenter(bb.getCenter());
```
When i try to get route from http://mapsengine.google.com/map/kml?forcekml=1&mid=z6IJfj90QEd4.kUUY9FoHFRdE - it looks good, but when I try to draw a route for my KML file, nothing happens. I have no idea why it happened, maybe you can help me?
My KML file: https://www.dropbox.com/s/22af1z0g2po8h6g/08AutumnalMarathon200km%28start6Sep2008%29.kml?dl=0

Thanks

**Comment by paulskvortsov** [comment]
@MKergall or how can i get array of GeoPoints from my kml file after parsing?

**Comment by MKergall** [comment]
I loaded your KML under OSMNavigator: KML is properly loaded, no error. The bike icon is displayed. The issue is that the path do not appear. 
The cause is the color settings on gpsiesStyle LineStyle => no color specified, but a colorMode random. OSMBonusPack defaults the color to black and ... to 100% transparent. 

Set a color, or just remove the colorMode line, and you will see your path. 

Which tool did you use to create your KML file?

**Comment by MKergall** [comment]
"or how can i get array of GeoPoints from my kml file after parsing?"

=> Can you explain a little bit more what you want?

**Comment by paulskvortsov** [comment]
@MKergall Thanks a lot
>Set a color, or just remove the colorMode line, and you will see your path.
I can't edit KML file, can i set a color in my code?

>Which tool did you use to create your KML file?
I got it from api, i can't edit file.

**Comment by MKergall** [comment]
Yes, you can set a color in your code. Look at the tutorial about KML, various solutions are described. 

From which API? Google Maps?

**Comment by paulskvortsov** [comment]
@MKergall wow, it works fine

> From which API? Google Maps?
No, from gpsies.com

> "or how can i get array of GeoPoints from my kml file after parsing?"
> => Can you explain a little bit more what you want?
it is necessary to calculate the remaining track distance. I have no idea how i can do it without geopoints

**Comment by MKergall** [comment]
> "or how can i get array of GeoPoints from my kml file after parsing?"

Look at your KML file on one side, and on OSMBonusPack KML objects on the other side. And dig...

This path is in the second Placemark of the KML root element:
`KmlPlacemark placemark = kmlDocument.mKmlRoot.mItems[1];`

It is a LineString, inside a MultiGeometry:
```
KmlMultiGeometry multiGeom = (KmlMultiGeometry)placemark.mGeometry;
KmlLineString lineString = (LineString)multiGeom.mItems[0];
```

`ArrayList<GeoPoint> myListOfPoints = lineString.mCoordinates;`

You have it. 

And you can also fix the color issue: 
`placemark.mStyle = null; //to remove this strange style and apply default one. `

**Comment by paulskvortsov** [comment]
@MKergall thanks for answer
when i trying to get KmlPlacemark placemark = kmlDocument.mKmlRoot.mItems[1] i have error:
`Array type expected; found: 'java.util.ArrayList<org.osmdroid.bonuspack.kml.KmlFeature>`
also i trying to get KmlPlacemark as `KmlPlacemark placemark = (KmlPlacemark) kmlDocument.mKmlRoot.mItems.get(1);` but then i got error in `KmlLineString lineString = (LineString) multiGeom.mItems;` as 'Cannot resolve symbol 'LineString'
Thanks

**Comment by MKergall** [comment]
Fixes: 
    KmlPlacemark placemark = (KmlPlacemark)kmlDocument.mKmlRoot.mItems.get(1);
    KmlMultiGeometry multiGeom = (KmlMultiGeometry)placemark.mGeometry;
    KmlLineString lineString = (KmlLineString)multiGeom.mItems.get(0);
    ArrayList<GeoPoint> myListOfPoints = lineString.mCoordinates;
