### ISSUE TITLE
Custom Marker Icon

### ISSUE THREAD

**Issue by jpaseneta** [MKergall/osmbonuspack#198]
Is there any simpler way besides making a custom resource proxy to just change the default DirectedLocationOverlay icon(ResourceProxy.bitmap.direction_arrow) to , for example, my own car icon drawable?

**Comment by MKergall** [comment]
Excellent question... 
But this is an osmdroid overlay, not an OSMBonusPack one. Nothing I can do, ask in osmdroid project.

**Comment by spyhunter99** [comment]
@jpaseneta looks like you can just extend DirectedLocationOverlay and provide your own bitmap

**Comment by jpaseneta** [comment]
@spyhunter99 that seems the only way to do it. Thank you also @MKergall

**Comment by spyhunter99** [comment]
if you'd like to suggest a change to the way osmdroid works, feel free to
open an issue

**Comment by jpaseneta** [comment]
@spyhunter99 yep i'll ask them there about this. I seem to be barking at the wrong tree with my questions, how do i know if a feature is osmbonuspack related and osmdroid related only? so i don't keep bothering the wrong person/s. As far as i've seen the code, osmbonuspack features relate mostly on the routing services, and all other UI stuff is osmdroid related? Thank you.

**Comment by spyhunter99** [comment]
osmbonuspack gives you kml support, icon clustering, online routing
services. At least i think those are the primary functions. everything else
is osmdroid

**Comment by MKergall** [comment]
The exact split between osmdroid and OSMBonusPack is not always obvious - particulary for overlays. 

A simple way to be sure is to check package name: 
All OSMBonusPack classes are under "org.osmdroid.bonuspack"
Everything else starting with "org.osmdroid" is from osmdroid.
