### ISSUE TITLE
How to keep current osmbonuspack sourcecode updated if i use gradle dependency build

### ISSUE THREAD

**Issue by jpaseneta** [MKergall/osmbonuspack#199]
With bug fixes being committed and pushed every now and then, how do i keep my reference to osmbonuspack up to date with the latest changes if i use the gradle dependecy build in the tutorial? Do you always update the version everytime?

Thanks

**Comment by MKergall** [comment]
If you want to always use the latest commits, a simple way is to clone the repo in your Android Studio, and reference your local lib (as I do for OSMNavigator). And you pull from GitHub to upgrade. 
Note that not fully tested work can be commited. That's the difference between the current Snapshot and a version.
