### ISSUE TITLE
migrate Polyline to osmdroid?

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#200]
Just throwing a thought out there. osmdroid has a few overlays, such as the PathOverlay is that is deprecated and recommends the Polyline class from OBP as the replacement. It would be nice if that was included with osmdroid. This would help clear up the functional dependency cycle. Thoughts?

**Comment by MKergall** [comment]
OBP Polyline inherits from OverlayWithIW, for InfoWindow support. 
So we should also move to osmdroid: OverlayWithIW, InfoWindow, and BasicInfoWindow. 

Now, from a more functional point of view, my thoughts: 
Marker, Polyline and Polygon are the 3 common overlays. I implemented them in OBP to mimic Google Maps API V2. If Polyline moves to osmdroid, why not the 2 others? Marker (with its bubble) is certainly used much more than Polyline. 
Once the 3 moved to osmdroid. Then you could progressively deprecate the ItemizedOverlay mess. 

OBP scope would be restricted to "extensions": 
- online services: routing, POI services, geocoding
- KML and GeoJSON support
- Marker Clustering
- some more specific overlays like GroundOverlay
Then, we have the OBP FolderOverlay case. No equivalent in Google Maps or other API. But so useful!

**Comment by spyhunter99** [comment]
sounds like you're on board with this. cool. I wanted to make sure before attempting anything, especially with the licensing difference between the projects. I'll raise an issue on osmdroid and get it scheduled for the release after next.

**Comment by spyhunter99** [comment]
i've got the following staged for merge (with git history!)
overlays (without ground overlay)
utils
cache manager.

I'm not sure about the last two, are they something that should be migrated or no?

**Comment by MKergall** [comment]
- utils: not needed for others. Should not be migrated. 
- cache manager: why not. And if osmdroid cache mechanism evolves, it should evolve as well.

**Comment by spyhunter99** [comment]
ok it has been pushed. waiting for ci, then the merge

**Comment by spyhunter99** [comment]
merged. FYI 5.1 was cut yesterday
