### ISSUE TITLE
gradle install, needs version information

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#201]
long story short, you need to set the pom version number. it installs local as "unspecified" which is less than useful

**Comment by MKergall** [comment]
Setting this pom.version: why not. But what is the exact purpose/need? 

Setting versionCode and versionName globally is not acceptable: versions of each module are changing separately. And OSMNavigator version code is now strategic for automatic updates on Google Play.

**Comment by spyhunter99** [comment]
When you deploy to a repository, such as maven local, or nexus, you have to
set the pom version, other it's listed as "unspecified" and it will always
be "unspecified". The pom version is what both maven and gradle need to
properly identify artifacts. You don't have to take the whole PR, I won't
be offended

**Comment by spyhunter99** [comment]
As far as purpose, please can then download the latest and greatest, run `gradle install`, and then pick up the artifact in their project using mavenLocal()

When you publish to jitpack, don't you have to version everything?

**Comment by MKergall** [comment]
Change just commited. Tell me if OK. 

For jitpack: I just have to create a GitHub release, setting the version in the tag version, and add the aar file. And then, it appears as a new version in jitpack. Magic.

**Comment by spyhunter99** [comment]
looks good, thanks!
