### ISSUE TITLE
Could you please provide information how to implement "sharing"?

### ISSUE THREAD

**Issue by stan2100** [MKergall/osmbonuspack#205]
Hi,
thank you so much for your great work! 
My app is getting better and better thanks to your osmbonuspack :-).
I’d like to implement position sharing. Could you give me so information how to implement sharing with my own server? That would be really great. For now, I share locations via email. It works, but your setup (in osmnavigator) seems to be much better :-).

**Comment by MKergall** [comment]
Well, my friends sharing service was not intended to be open source... 

Contact me by direct email, and explain what you intend to do.

**Comment by stan2100** [comment]
Hi :-).
I'd love to, but I can't find your email address. Could you provide any further details, how to contact you?

**Comment by MKergall** [comment]
mathieu kergall, at gmail
(hoping spammers will not detect that)
