### ISSUE TITLE
peer not authenticated when including from JitPack

### ISSUE THREAD

**Issue by grote** [MKergall/osmbonuspack#206]
It is great that OSMBonusPAck is now available for easy gradle includes. Unfortunately, I get this error when trying to include it as described in the wiki:
```
      > Could not resolve com.github.MKergall.osmbonuspack:OSMBonusPack:v5.7.
         > Could not get resource 'https://jitpack.io/com/github/MKergall/osmbonuspack/OSMBonusPack/v5.7/OSMBonusPack-v5.7.pom'.
            > Could not GET 'https://jitpack.io/com/github/MKergall/osmbonuspack/OSMBonusPack/v5.7/OSMBonusPack-v5.7.pom'.
               > peer not authenticated
```
This is on Debian sid and the reason might the that JitPack's SSL certificate coming from COMODO is not trusted by its java installation.

**Comment by MKergall** [comment]
Exceeding my competencies, I'm afraid. 
Either you are able to identify the solution, or you can include the jar locally in your libs.

**Comment by grote** [comment]
I had already filed this as jitpack/jitpack.io#423 as well and could solve it there. Thanks for answering!

Btw. [grote/Transportr](https://github.com/grote/Transportr/) is using your library as well, if you want to add it to the wiki.
