### ISSUE TITLE
where can I download a latest jar? no gradle

### ISSUE THREAD

**Issue by djdance** [MKergall/osmbonuspack#207]
in android studio without gradle I can not add aar.
Can you make a old good jar?
thanks

**Comment by MKergall** [comment]
I will not go back to jar, as the jar cannot include resources. 

If you don't use Gradle in Android Studio, what are you using? 

You can fork OSMBonusPack in your Android Studio, and then include it in your apk project as a "lib" project.

**Comment by djdance** [comment]
> I will not go back to jar, as the jar cannot include resources.

i know, but old osmbonuspacks distributed in jar wihtout problems.

> If you don't use Gradle in Android Studio, what are you using?

99% of tens projects works well, excluding some rare cases, such as osm :-(

> You can fork OSMBonusPack in your Android Studio, and then include it in your apk project as a "lib" project.

too hard, simpler is to get old osm :-(
