### ISSUE TITLE
Info window will not show when marker is clicked

### ISSUE THREAD

**Issue by btmcnellis** [MKergall/osmbonuspack#209]
My understanding is that, by default, Markers should display their info windows when tapped. For some reason, that behavior isn't working for me, so I tried implementing my own `OnMarkerClickListener` instead:

```
myMarker.setOnMarkerClickListener(new Marker.OnMarkerClickListener() {
            public boolean onMarkerClick(Marker marker, MapView map) {
                marker.showInfoWindow();
    		map.getController().animateTo(marker.getPosition());
        	return true;
            }
        });
```

I've confirmed that the listener is called correctly (for one thing, the map pans to the marker correctly), but the info window still isn't showing.

I can get the info window to show and the normal behavior to work correctly if I call `myMarker.showInfoWindow()` outside of the listener, but then the window shows by default when the marker first appears, which isn't necessarily what I want (I can't imagine that looking good if there are a lot of markers showing up at the same time). I tried following the show call with `myMarker.closeInfoWindow()`, but then I have the same problem as before.

Am I missing something obvious here, or is there a bug? I've tried this on a Samsung Galaxy S4 running Android 5.0.1 and a few different models running Android 6.0 in a Genymotion simulator. I'm using OSMDroid 5.1 and Bonus Pack v5.7.

**Comment by MKergall** [comment]
I never got that issue. Yes, Markers should definitely open their infowindow when tapped. 
What is the targetSdkVersion of your apk project? 
Could you try the same code on a 4.x device?

**Comment by btmcnellis** [comment]
compileSdkVersion is 23, targetSdkVersion is 22.

I tried it on 4.4.4 and had the same behavior.

**Comment by MKergall** [comment]
Maybe the infowindow resources missing. 
How do you include the OSMBonusPack aar in your project?
