### ISSUE TITLE
Friendly note about upcoming OSRM API changes

### ISSUE THREAD

**Issue by daniel-j-h** [MKergall/osmbonuspack#212]
We're seeing OsmBonusPack hitting the OSRM demo server, so I just wanted to drop a note about upcoming breaking API changes.

We had to break the API at one point in time to enable better guidance, a type-safe library interface, and other important features. Over at osrm-backend the v5 branch is on rewrite/new-api and you can already play around with it.

This pull request tracks the progress so far:
https://github.com/Project-OSRM/osrm-backend/pull/1935

And this is the v5 API spec, which you have to transition your implementation to:
https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api

And here's the original announcement mail:
https://lists.openstreetmap.org/pipermail/osrm-talk/2016-February/001127.html

I assume the new API will ship during the next weeks / beginning of April.

Please note that at some point in time we may switch over the demo server to this API.

**Comment by MKergall** [comment]
First commit to handle the new API: 
https://github.com/MKergall/osmbonuspack/commit/e5526bcfbccfc92b1593bc5079266b20b564c2c2

**Comment by MKergall** [comment]
New OSRM API supported in OBP 5.8.

**Comment by danpat** [comment]
Just a follow up on this - we've held off on shutting down the 4.x server for 6+ months, but it's finally time.  In the next couple of days, any user hitting the 4.x `router.project-osrm.org` API will begin seeing failing requests.

@MKergall A review of our logs shows that OSMBonusPack-based apps seem to be responsible for *huge* number of calls to the 4.x API still.  If you have any way of letting SDK-users know about this upcoming change, please do so.

**Comment by MKergall** [comment]
Thanks for this warning. 
OSMBonusPack lib has been upgraded to handle the new OSRM API in V5.8 in May, 4 months ago now. 
I will put a warning on the home page, to push applications using the lib to accelerate their upgrade.
