### ISSUE TITLE
If markers overlap, the clicked one is the one behind.

### ISSUE THREAD

**Issue by 2ndGAB** [MKergall/osmbonuspack#213]
Hi,
I'm a bit annoyed because I've implemented an extension to `RadiusMarkerClusterer()` because, from my point of view, few close markers (2 or 3), shouldn't be clustered.

So my implementation is this one:

```
package com.example.alain.overlappedmarkers;

import android.content.Context;
import android.graphics.Rect;

import org.osmdroid.bonuspack.clustering.RadiusMarkerClusterer;
import org.osmdroid.bonuspack.clustering.StaticCluster;
import org.osmdroid.bonuspack.overlays.Marker;
import org.osmdroid.util.BoundingBoxE6;
import org.osmdroid.util.GeoPoint;
import org.osmdroid.views.MapView;

import java.util.ArrayList;
import java.util.Iterator;

/**
 * Created by Alain on 03/02/2016.
 */
public class MyRadiusMarkerClusterer extends RadiusMarkerClusterer {

    public int getMinNumOfMarkersInCluster() {
        return minNumOfMarkersInCluster;
    }

    public void setMinNumOfMarkersInCluster(int minNumOfMarkersInCluster) {
        this.minNumOfMarkersInCluster = minNumOfMarkersInCluster;
    }

    int minNumOfMarkersInCluster = 1;   // Initialized to 1 to keep the default behavior

    public MyRadiusMarkerClusterer(Context ctx) {
        super(ctx);
    }

    @Override public ArrayList<StaticCluster> clusterer(MapView mapView) {

        ArrayList<StaticCluster> clusters = super.clusterer(mapView);

        ArrayList<StaticCluster> myClusters = new ArrayList<>();

        Iterator<StaticCluster> itClusters = clusters.iterator();

        while(itClusters.hasNext()) {
            StaticCluster cluster = itClusters.next();

            if (cluster.getSize() < minNumOfMarkersInCluster) {
                for (int i = 0; i < cluster.getSize(); i++) {
                    StaticCluster newCluster = new StaticCluster(cluster.getItem(i).getPosition());
                    newCluster.add(cluster.getItem(i));
                    myClusters.add(newCluster);
                }
            } else {
                myClusters.add(cluster);
            }
        }

        return myClusters;
    }
}
```

But I get a strange problem when 2 markers are overlapped because when I click on them the one which gets the click is not the topmost one but the one behind!?!

Can you guess what could cause this problem please?

Test application is [here](https://github.com/2ndGAB/OverlappedMarkers)

**Comment by 2ndGAB** [comment]
Hi Michael,
Can I have your point of view please?

**Comment by MKergall** [comment]
Effectively, there is an issue, and the bug is in MarkerClusterer: all event-detection loops are done following normal order, instead of reverse order. 

	@Override public boolean onSingleTapConfirmed(final MotionEvent event, final MapView mapView){
		for (StaticCluster cluster:mClusters){
			if (cluster.getMarker().onSingleTapConfirmed(event, mapView))
				return true;
		}
		return false;
	}

So events are always raised on markers behind, instead of markers on top. 
I never noticed because clustering was "cleaning" all overlappings. 

I will fix that in the next release. 
In the meantime, you can override onSingleTapConfirmed in your MyRadiusMarkerClusterer, to have it fixed quickly.

**Comment by 2ndGAB** [comment]
Very cool, Thanks a lot Mickael.
