### ISSUE TITLE
cachemanager osmbonuspack vs osmdroid

### ISSUE THREAD

**Issue by kojinanjo** [MKergall/osmbonuspack#214]
Hi
Why the version of cachemanager in osmdroid is updated compared to the version of this repository?

https://github.com/osmdroid/osmdroid/blob/master/osmdroid-android/src/main/java/org/osmdroid/bonuspack/cachemanager/CacheManager.java

It's posible to update it and add it to gradle?

thanks!

**Comment by 2ndGAB** [comment]
I wonder if osmbonuspack is not supposed to be included in osmdroid soon.
But maybe it's time to clean everything and tell us where official releases are suppose to be.
Maybe this [repo](https://github.com/grote/OSMBonusPack/tree/master/src/org/osmdroid/bonuspack) could be deleted also no?

And what about the issues, I wonder if Mathieu still answers here !?!

**Comment by MKergall** [comment]
See https://github.com/osmdroid/osmdroid/issues/291
