### ISSUE TITLE
KmlDocument.parseGeoJSONUrl

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#215]
There's a parse URL for Kml, but not GeoJson or Kmz. Think we can add that some point?

**Comment by MKergall** [comment]
For GeoJSON, here is the solution: 
    String jsonString = BonusPackHelper.requestStringFromUrl(url);
    kmlDocument.parseGeoJSON(jsonString);

For KMZ, ... it's not so simple. The KMZ parser is based on Android ZipFile API. So I think we would have to download the KMZ file first.
