### ISSUE TITLE
Wiki on Kml import doesn't match api

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#216]
wiki says
FolderOverlay kmlOverlay = (FolderOverlay)kmlDocument.mKmlRoot.buildOverlay(this, map, null, null, kmlDocument);

as of 5.7, this appears to be correct
FolderOverlay kmlOverlay = (FolderOverlay)kmlDocument.mKmlRoot.buildOverlay(mapView, null, null, kmlDocument);

**Comment by MKergall** [comment]
That's right. Fixed now. 
Thanks!
