### ISSUE TITLE
PolyLine with Label and Direction

### ISSUE THREAD

**Issue by grote** [MKergall/osmbonuspack#217]
Hi,

I am using OSMBonusPack for Transportr and the PolyLine in different colors to show where the bus will go. For this, it would be nice to have little direction arrows and a label that could be the bus line for example.

Thanks for your consideration!
Torsten

**Comment by spyhunter99** [comment]
Are you creating the polyline programmatically or via KML? You can always attach a marker at or near the line with the label

**Comment by grote** [comment]
I am creating the polyline programmatically. Here's an example:
![Screenshot](https://cloud.githubusercontent.com/assets/244947/14973405/a80ff2c2-10bd-11e6-83af-0ecf2a347547.png)

As you can see I am already using markers, but for others things. I don't think markers are suitable for a line label or to indicate the direction of the line.

**Comment by grote** [comment]
@spyhunter99 I noticed that Polyline and other things were moved over to osmdroid. That's something I really appreciate! :)

Do you want me to recreate this issue in the osmdroid issue tracker?

**Comment by spyhunter99** [comment]
up to you, there's a few examples with labels on polylines there. Check out the lat/lon grid line sample

**Comment by MKergall** [comment]
to handle in osmdroid
