### ISSUE TITLE
polyline.isCloseTo

### ISSUE THREAD

**Issue by Mantj** [MKergall/osmbonuspack#219]
In the class Ployline,the Method polyline.isCloseTo(GeoPoint point, double tolerance, MapView mapView) is use to judge if my location is close to my polyline.

but I don not know the parameter ## "double tolerance" means what.
The doc says ## tolerance - in pixels ,but why I need pixels,What's the use of it?

please forgive my poor English.

**Comment by MKergall** [comment]
"tolerance" is the max distance from the GeoPoint to the line. 
As mentioned in javadoc, as detection is done in screen coordinates, tolerance is in pixels. It's main purpose is touch event detection (see onSingleTapConfirmed). 

Using it to judge if a position is close to a polyline - in meters - may not be very easy. Maybe this way:

    meters = pixels * (float) TileSystem.GroundResolution(mapView.getBoundingBox().getCenter().getLatitude(),
				zoomLevelProjection);

**Comment by Mantj** [comment]
thank you very much.
i get what i want !
love you ~

**Comment by MKergall** [comment]
You're welcome!
