### ISSUE TITLE
Polyline disappears when zoom in (V5.7)

### ISSUE THREAD

**Issue by ShawnHsiung** [MKergall/osmbonuspack#220]
The problem describe:
 
When the destination is very near to the start point, it do not disappears when zoom in, but as the destination point farther from the start point, the event of disappearing of polyline happens at lower zoom level. Is the line too long to display?

Looking for some solutions for this problem.  thank you very much.

**Comment by Mantj** [comment]
I use this command :
map.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
to solve this problem，but I don't know why .Maybe you can try.

**Comment by ShawnHsiung** [comment]
@Mantj  it's works, thanks a lot

**Comment by MKergall** [comment]
The reason: on Android SDK >= 14, 2D drawing is using by default hardware acceleration, which is based on OpenGL. 
http://developer.android.com/guide/topics/graphics/hardware-accel.html

But OpenGL API has limitations on large coordinates values - causing this issue typically on long lines at low zoom levels. 

So, yes, blocking Harware accelation is the solution.
