### ISSUE TITLE
How to use multi language?

### ISSUE THREAD

**Issue by Imakerinfosoft** [MKergall/osmbonuspack#221]
I use your library for offline and online map and poi  but my application has three different languages link Dutch,Spanish,French,English user can switch languages according to their requirement but my problem is that map language is default English,so how can i change language of map according to user need,example please .Reply me asap. Thank you !!

**Comment by MKergall** [comment]
This issue is a real issue. 
But it's related to OpenStreetMap itself, not to OSMBonusPack. 
And it's also redundant with your [request on StackOverflow](http://stackoverflow.com/questions/36908738/i-want-to-add-multi-language-in-osmdroid). 
So I close this one.

**Comment by Imakerinfosoft** [comment]
Sir but i not get proper answer in  StackOverflow
<http://stackoverflow.com/questions/36908738/i-want-to-add-multi-language-in-osmdroid>
so
i directly ask you ,so please do not close my question please give me
proper answer in your github or StackOverflow,Thank you !!

**Comment by spyhunter99** [comment]
if you are referring to the language written for roads/cities/etc on the map background, you'll have to find map sources (osmdroid ITileSource) that match the desired language. I think OpenStreetMap tile servers produce tiles in many languages. The solution is for you to find the correct url's for osm for the user's langauge and switch to that source.

**Comment by Imakerinfosoft** [comment]
ok Thank you i will try to find (osmdroid ITileSource) for change Language

**Comment by spyhunter99** [comment]
My point is that it doesn't exist. there's tons of tile sources that
osmdroid comes preconfigured with it, but they are all english. You'll have
to find an online tile source for the languages you need, then configure
your app to use your own tile sources within osmdroid

**Comment by Imakerinfosoft** [comment]
Ok thank you for your suggestion i will try to create my own tile of
different language form online  tile server and attach with osmdroid.
