### ISSUE TITLE
Not compatible with osmdroid 5.2

### ISSUE THREAD

**Issue by sirkalmi** [MKergall/osmbonuspack#223]
Error: cannot access ResourceProxy
class file for org.osmdroid.ResourceProxy not found

**Comment by MKergall** [comment]
osmbonuspack 5.7 is compatible with osmdroid 5.1. 
Compatibility with osmdroid 5.2 will be done in next release.

**Comment by sirkalmi** [comment]
When is the next release?

**Comment by MKergall** [comment]
very soon I hope.

**Comment by MKergall** [comment]
commit #f7af470 available. Still to be fully tested before release.

**Comment by sirkalmi** [comment]
Thank you!

**Comment by MKergall** [comment]
osmbonuspack 5.8.1 compatible with osmdroid 5.2 now released.
