### ISSUE TITLE
Kml style doesn't work

### ISSUE THREAD

**Issue by virux84** [MKergall/osmbonuspack#224]
Hi,
I've written some code using your library.
`{@Override
	public void onActivityCreated(Bundle savedInstanceState) {
		super.onActivityCreated(savedInstanceState);

		//open memory overlay
		kmlOverlay = (FolderOverlay)kmlFile.mKmlRoot.buildOverlay(mMapView, null, null, kmlFile);
		mMapView.getOverlays().add(kmlOverlay);
		//open file choose by user
		String filepath = (String) SP.getString("filepicker", "NA");
		Log.d("TAG", filepath);
		if(filepath!="NA") {
			Log.d("TAG", "openfileopen");
			File fileOpen = new File(filepath);
			kmlFileOpen.parseKMLFile(fileOpen);

			Drawable defaultMarker = getResources().getDrawable(R.drawable.greendot);
			Log.d("TAG", defaultMarker.toString());
			Bitmap defaultBitmap = ((BitmapDrawable)defaultMarker).getBitmap();
			Log.d("TAG", defaultBitmap.toString());
			Style kmlStyle = new Style(defaultBitmap,0x901010AA, 3.0f, 0x20AA1010);
			Log.d("TAG", kmlStyle.toString());
			kmlOverlayOpen = (FolderOverlay)kmlFileOpen.mKmlRoot.buildOverlay(mMapView, kmlStyle, null, kmlFileOpen);
			mMapView.getOverlays().add(kmlOverlayOpen);
		}

`
I use kmlFile and KmlOverlay to store and restore overlay putted by user, while kmlFileOpen and kmlOverlayOpen to load overlay from a kml choosed by user.

I apply the style only to kmlOverlayOpen, but it doesn't change the style. In fact it draw only a thin black line.

Thank you for your answer

**Comment by MKergall** [comment]
As explained in the [Tutorial_4](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4), your kmlStyle will be applied as a default style, only when the KML Placemark has no style defined. 

In your KML file, check if your PlaceMarks have a style (you can provide the KML file here if you want me to have a look).

**Comment by virux84** [comment]
Hi,
thank you for your fast answer.
This is the file.
Is not there a solution to overwrite the style of the kml with mine?
Thank you

[PercorsoSora.zip](https://github.com/MKergall/osmbonuspack/files/249989/PercorsoSora.zip)

**Comment by spyhunter99** [comment]
After the kml has been parsed and turned into the FolderOverlay structure,
you can iterate though the data structure and make whatever changes you
need before adding it to the map view

**Comment by MKergall** [comment]
@virux84 yes, you can. 
One method is to use the KML "Styler". 
This is described in details in the [Tutorial_4](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4#132-advanced-styling-with-the-styler).

**Comment by virux84** [comment]
Thank you very much for all the answer.
I use the "Styler" solution and it works great!
