### ISSUE TITLE
onMarkerDrag problem

### ISSUE THREAD

**Issue by virux84** [MKergall/osmbonuspack#225]
Hello,
I want to use the onMarkerDrag, onMarkerDragStart, onMarkerDragEnd methods, but when I drag a marker on the map any of the above methods start.

`public  class BaseSampleFragment extends Fragment implements MapEventsReceiver, Marker.OnMarkerDragListener {

	@Override
	public void onMarkerDrag(Marker marker) {
		Log.d("TAG", "marker drag ");
	}

	@Override
	public void onMarkerDragStart(Marker marker) {
		Log.d("TAG", "marker drag start");
	}

	@Override
	public void onMarkerDragEnd(Marker marker){
		Log.d("TAG", "marker drag end");
		marker.setTitle(Double.toString(marker.getPosition().getLatitude())+"   "+Double.toString(marker.getPosition().getLongitude()) );

	}
`

Thank you for your answer

**Comment by MKergall** [comment]
How do you "set" this OnMarkerDragListener to your Markers? Please provide related code.

**Comment by virux84** [comment]
Exscuse me, it's my fault because I'm am a newbie.
I've to study more Android programming.
Thank you very much
