### ISSUE TITLE
Error dependency

### ISSUE THREAD

**Issue by thalissondev** [MKergall/osmbonuspack#226]
Error:Module 'com.github.MKergall.osmbonuspack:OSMBonusPack:v5.7' depends on one or more Android Libraries but is a jar

Does anyone know how I solve this problem?
Thank you.

**Comment by thalissondev** [comment]
Succces with compile 'com.github.MKergall.osmbonuspack:OSMBonusPack:v5.7@aar' add @arr

Thank you.

**Comment by milad7111** [comment]
compile 'com.github.MKergall.osmbonuspack:6.3@aar' does not work for me, help?
