### ISSUE TITLE
Marker Subdescription and KmlDocument

### ISSUE THREAD

**Issue by virux84** [MKergall/osmbonuspack#227]
Hi,
I set a Marker with Title, Snippet and Subdescription and finally save it to a kmldocument.
When I retrive the Marker it  automatically has the title and snippet setted but not the subdescription.
Is it my fault? What I can do to overcome this?
Thank You for your time and help.

`//saveMarker
addedMarker.setTitle("Title");
addedMarker.setSnippet("Snippet");
addedMarker.setSubDescription("SubDescription");
kmlFile.mKmlRoot.addOverlay(addedMarker, kmlFile);
kmlFile.saveAsKML(filefile);

//loadMarker
filefile = new File(this.getActivity().getFilesDir(), "memory.kml");
kmlFile = new KmlDocument();
kmlFile.parseKMLFile(filefile);
kmlOverlay = (FolderOverlay)kmlFile.mKmlRoot.buildOverlay(mMapView, null, null, kmlFile);
mMapView.getOverlays().addAll(kmlOverlay.getItems());`

**Comment by MKergall** [comment]
see #228
