### ISSUE TITLE
Does the library support GPX

### ISSUE THREAD

**Issue by diabloo** [MKergall/osmbonuspack#229]
hi,
i'am working in an app that need to read a gpx file , i tested the library with kml files and it works very well , but i was wondering if the library supports  gpx files or i'll have to convert it to a kml file ?

**Comment by MKergall** [comment]
No, it doesn't. 
If you can convert your files to KML, that's probably the easiest solution. 
Take care in this conversion that KML extensions gx:Track and gx:MultiTrack are not supported. Convert to KML LineStrings or Placemarks.

**Comment by diabloo** [comment]
I tried converting it works well , thank you for the answers
