### ISSUE TITLE
Registering to CacheManager

### ISSUE THREAD

**Issue by 2ndGAB** [MKergall/osmbonuspack#231]
Hello,
That could be useful to register to the CacheManager to be informed that tiles downloading is finished.

Also the problem is that your progress dialog is cancellable. That could be the best choice in some cases but not always.

Maybe a better implementation would be to specify to the CacheManager our own dialog, or yours if we pass null.

That way we could use our own dialog with our title, message and options like not cancelable.

**Comment by MKergall** [comment]
I agree the CacheManager UI should be much more customizable (to allow translations for instance). 

But it has been integrated in osmdroid now (yes, I still have to remove it completely from OBP...). 
So you should raise these points in osmdroid.

**Comment by spyhunter99** [comment]
This feature already exists in osmdroid

**Comment by 2ndGAB** [comment]
you mean in 5.2? But it seems that OSMBonusPack is not fully compatible with 5.2 right?

**Comment by MKergall** [comment]
OBP 5.8.1 is fully compatible with osmdroid 5.2

**Comment by MKergall** [comment]
Closed on OBP side.
