### ISSUE TITLE
Trouble with a simple kml file

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#233]
@MKergall I hope you can help me out. I have a really simple kml file that i'm unable to get rendered. Unfortunately i can't give you the exact file as is (waiting on permission from a customer) but I think i can give you enough information to recreate.

```xml
<kml>
<Document>
<!-- with some styles and a style map here -->
<Style id="blue">
<LineStyle><width>1.0</width><color></color>00ff0000</LineStyle>
<PolyStyle><color>00ff0000</color><outline>0</outline>

</Style>

<StyleMap>
<Pair><key>normal</key><styleUrl>#blue</styleUrl></Pair>
</StyleMap>
<Placemark>
<name>asd</name>
<styleUrl>#blue</styleUrl>
<MultiGeometry>
<!-- just a made up location -->
<Point><coordinates>-77.0, 40.0</coordinates></Point>
<Polygon>
<tessellate>1</tessellate>
<altitudeMode>clampToGround</altitudeMode>
<outerBoundaryIs>
<LinearRing>
<coordinates>
<!-- 
a bunch of points here (around 10) in the format
lat, lon, alt
-->
 76.0, 39.0, 0
 78.0, 39.0, 0
 78.0, 41.0, 0
 76.0, 41.0, 0
</coordinates>
</LinearRing>
</outerBoundaryIs>
</Polygon>
</MultiGeometry>
</Placemark>
</Document>
</kml>
```

**Comment by spyhunter99** [comment]
hang on hit enter too soon

**Comment by spyhunter99** [comment]
oh bummer, just read through the wiki, LinearRing isn't on the list.

**Comment by MKergall** [comment]
Inside Polygon, LinearRing are used to define outerBoundaryIs (border) and innerBoundaryIs (holes). 
In this context, yes, they are supported. 
As this is your use case, it should work. 

So your issue is somewhere else... 

If you can provide a simplified KML sample, still having the issue?

**Comment by spyhunter99** [comment]
right off of a develop, i'm getting an NPE. So there's that. This is a different behavior than I'm seeing with the older version.

06-07 06:54:31.385 8718-8718/com.example.osmbonuspacktuto W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.drawable.BitmapDrawable.getIntrinsicWidth()' on a null object reference
06-07 06:54:31.385 8718-8718/com.example.osmbonuspacktuto W/System.err:     at org.osmdroid.bonuspack.kml.IconStyle.styleMarker(IconStyle.java:97)
06-07 06:54:31.385 8718-8718/com.example.osmbonuspacktuto W/System.err:     at org.osmdroid.bonuspack.kml.KmlPoint.applyDefaultStyling(KmlPoint.java:76)
06-07 06:54:31.385 8718-8718/com.example.osmbonuspacktuto W/System.err:     at org.osmdroid.bonuspack.kml.KmlPoint.buildOverlay(KmlPoint.java:97)
06-07 06:54:31.385 8718-8718/com.example.osmbonuspacktuto W/System.err:     at org.osmdroid.bonuspack.kml.KmlMultiGeometry.buildOverlay(KmlMultiGeometry.java:69)
06-07 06:54:31.385 8718-8718/com.example.osmbonuspacktuto W/System.err:     at org.osmdroid.bonuspack.kml.KmlPlacemark.buildOverlay(KmlPlacemark.java:126)
06-07 06:54:31.385 8718-8718/com.example.osmbonuspacktuto W/System.err:     at org.osmdroid.bonuspack.kml.KmlFolder.buildOverlay(KmlFolder.java:163)
06-07 06:54:31.385 8718-8718/com.example.osmbonuspacktuto W/System.err:     at com.example.osmbonuspacktuto.MainActivity.onCreate(MainActivity.java:240)

**Comment by spyhunter99** [comment]
same issue on 5.7 release. i'll update the description with some of the styling information. maybe that will help

**Comment by spyhunter99** [comment]
I've also tried playing around with the alpha color flags but that didn't make a difference.

**Comment by spyhunter99** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <Style id="transBlue">
      <LineStyle>
        <width>1.0</width>
        <color>00ff0000</color>
      </LineStyle>
      <PolyStyle>
        <color>00ff0000</color>
        <outline>0</outline>
      </PolyStyle>
      <IconStyle><Icon></Icon></IconStyle>
    </Style>
    <Style id="highlightTransBlue">
      <LineStyle>
        <width>1.0</width>
        <color>80ff0000</color>
      </LineStyle>
      <PolyStyle>
        <color>80ff0000</color>
        <outline>1</outline>
      </PolyStyle>
      <IconStyle><Icon></Icon></IconStyle>
    </Style>
    <StyleMap id="transBlueMap">
      <Pair>
        <key>normal</key>
        <styleUrl>#transBlue</styleUrl>
      </Pair>
      <Pair>
        <key>highlight</key>
        <styleUrl>#highlightTransBlue</styleUrl>
      </Pair>
    </StyleMap>
    <Placemark>
      <name>1048</name>
      <styleUrl>#transBlueMap</styleUrl>
      <MultiGeometry>
        <Point>
          <coordinates>-76.123,39.4493,0</coordinates>
        </Point>
        <Polygon>
          <tessellate>1</tessellate>
          <altitudeMode>clampToGround</altitudeMode>
          <outerBoundaryIs>
            <LinearRing>
             <coordinates>
          -76.0624, 39.4493, 200
          -75.9896, 39.5462, 200
          -76.1112, 39.4857, 200
          -76.1417, 39.5066, 200
          -76.199, 39.5045, 200
          -76.1849, 39.4493, 200
          -76.1853, 39.4041, 200
          -76.1335, 39.4171, 200
          -76.0938, 39.3593, 200
          -76.0287, 39.3808, 200
             </coordinates>
            </LinearRing>
          </outerBoundaryIs>
        </Polygon>
      </MultiGeometry>
    </Placemark>
  </Document>
</kml>

```

**Comment by spyhunter99** [comment]
I added a simple null check in IconStyle.java:97 which yielded just the marker and no polygon.

**Comment by MKergall** [comment]
You hit a case that was not handled: there is a style, the style has an icon, but the icon has no href. 
So, yes, the null check at IconStyle.java:97 has to be added. 
But then you will have no marker displayed at all. 

So, in your KML, either remove the IconStyle, or give it an href to an actual image.

**Comment by spyhunter99** [comment]
True but still no polygon.  Are they Co dependant?

**Comment by spyhunter99** [comment]
With the null check, I get the standard osm icon, which is fine

**Comment by MKergall** [comment]
OK, found: coordinates parsing not tolerant enough to spaces. 
Try this: 
<coordinates>-76.0624,39.4493,200 -75.9896,39.5462,200 -76.1112,39.4857,200 -76.1417,39.5066,200 -76.199,39.5045,200 -76.1849,39.4493,200 -76.1853,39.4041,200 -76.1335,39.4171,200 -76.0938,39.3593,200 -76.0287,39.3808,200</coordinates>

**Comment by spyhunter99** [comment]
Nice I figured it was something simple.  Will test shortly. Thanks!

**Comment by MKergall** [comment]
Your KML file doesn't work properly on Google Earth, for the same reason: 
"-76.0287, 39.3808, 200" is not valid, as spaces are separators of points. 

Other issue: 00ff0000 is fully transparent. So the polygon is not visible at all.

**Comment by spyhunter99** [comment]
I was wondering about that too. Thanks for looking into this

**Comment by spyhunter99** [comment]
oh and your fixes fixed the problem. thanks!
