### ISSUE TITLE
My Polyline disappears on high zoom Level

### ISSUE THREAD

**Issue by anto2b** [MKergall/osmbonuspack#234]
My config
osmdroid 5.2
osmbonuspack 5.8.1

I created my Polyline like this : 

```
Polyline pathOverlay = new Polyline(context);
pathOverlay.setPoints(points);
pathOverlay.setColor(Color.RED);
pathOverlay.setWidth(15.0f);
mapView.getOverlays().add(pathOverlay);
mapView.invalidate();
```
My polilyne is drawn in small zoom levels, but when I zoom in high zoom level my polilyne disappears on the map.

In my logcat I have this message

> Shape too large to be rendered into a texture (7268x9145, max=8192x8192)

**Comment by navarrete0** [comment]
android:hardwareAccelerated="false" solve your problem? [#168](https://github.com/MKergall/osmbonuspack/issues/168)

**Comment by anto2b** [comment]
Thanks you 
Solved !
