### ISSUE TITLE
Get 4 geopoint of mapview

### ISSUE THREAD

**Issue by kenk11** [MKergall/osmbonuspack#235]
Hi @MKergall ,
I'm using osmbonuspack for detect restaurant in area on screen,
How I can get 4 point of current mapview ?  I tried getBoundingBox but it didn't worked

**Comment by MKergall** [comment]
MapView.getBoundingBox doesn't work in onCreate, because the view has not been drawn yet. 
But later, it works fine. Look at OSMNavigator source code, you will  see plenty of examples.
