### ISSUE TITLE
NominatimGeocoder with mapquestkey doesn't work

### ISSUE THREAD

**Issue by milovanderlinden** [MKergall/osmbonuspack#237]
I have checked the code of the Nominatim Geocoder. It is not possible to set the mapquest key and the url that gets constructed does not check for any key. If I manually add the key to the serviceURL, the resulting url becomes invalid.

**Comment by MKergall** [comment]
Effectively, I see that MapQuest now imposes a key to use its Nominatim service (https://open.mapquestapi.com/nominatim)
I just added support for this key: GeocoderNominatim.setKey(appKey), in commit #5f50023

(BTW, do you really plan to use this MapQuest service, instead of the regular Nominatim?)
