### ISSUE TITLE
Straight line instead of road

### ISSUE THREAD

**Issue by Isratmity01** [MKergall/osmbonuspack#239]
I've been trying to use  routing api 
"http://router.project-osrm.org/route/v1/driving/X1,Y1;X2,Y2?alternatives=false&overview=full&steps=true"

I'm not receiving any result. Is the API functioning? viaroute one works but I guess that one is old. Your roadmanager code is for new version I guess on which I get no result. Can you suggest any way to fix this up?

**Comment by MKergall** [comment]
I don't understand your issue. 
Which OSMBonusPack routing API are you using exactly (the one working and the one not working)? 
(Provide relevant code section). 
With which version of OSMBonusPack?
