### ISSUE TITLE
Is Polyline gone?

### ISSUE THREAD

**Issue by maxq13** [MKergall/osmbonuspack#241]
Hi,
I've been using osmdroid 4.3 + osmbonuspack 5.1, and was using overlays/Polyline and MapEventsReceiver classes (see tutorials 1 and 5). Everything was fine.

Today I have updated to osmdroid 5.2 and osmbonuspack 5.8.1, and I see that these are no longer there.
What should be used instead?

**Comment by MKergall** [comment]
They have been moved to osmdroid lib, along with Marker and some other classes. 
Just update your imports, and everything should be fine again.

**Comment by maxq13** [comment]
Thanks for reply. Everything's working now.
