### ISSUE TITLE
OSMNavigator - Rendering problem 

### ISSUE THREAD

**Issue by kodalo** [MKergall/osmbonuspack#246]
OSMNavigator compiles and works fine, but I cant view design in  main.xml. Error is: 

The following classes could not be instantiated:
- com.osmnavigator.AutoCompleteOnPreferences 
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.

Exception Details java.lang.ClassNotFoundException: org.json.JSONException

As I said, it works fine on emulators, but I can edit layout.

**Comment by MKergall** [comment]
OSMNavigator is not the core lib, just my test app, and I personally don't care about designing main.xml. So, I cancel this one.
