### ISSUE TITLE
InfoWindow's button

### ISSUE THREAD

**Issue by 2ndGAB** [MKergall/osmbonuspack#247]
Hi Mickael,

Is there a good reason to display this blue button on the right of the infoWindow to generate the click event?

It seems that lot of users click on the infoWindow itself which closes it and so don't see that a specific feature is supposed to be accessed from this window.

Isn't it better to remove it?

Regards,
Alain

**Comment by MKergall** [comment]
In many use cases, you need a way from an infowindow to get "more info". This is the purpose of this blue arrow button. Examples can be found in the tutorials. 
It is hidden by default, so it has no impact for all infowindows not needing that.

**Comment by 2ndGAB** [comment]
I agree with that but 'more info', if it exists, could be accessed directly clicking the infoWindow instead of a specific button which seems not so obvious for most people.

**Comment by MKergall** [comment]
I cannot implement "more info" in the default button, as it's specific on each need. 
Users can easily customize the bubble so that clicking the bubble performs their "more info", instead of closing the pop-up.

**Comment by 2ndGAB** [comment]
ok I agree
