### ISSUE TITLE
Update dependencies for osmdroid-android:5.4:release@aar

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#248]
org.osmdroid:osmdroid-android:5.4:release@aar

**Comment by shubyana** [comment]
hello brother i have same prob.

**Comment by MKergall** [comment]
OSMBonusPack 5.9 has been released, using osmdroid 5.4.1 (yes, 5.4.1, not 5.4). 
The dependency to upgrade in your build.gradle: 

`compile 'com.github.MKergall:osmbonuspack:5.9'
`
