### ISSUE TITLE
Error response(Error code 404.)

### ISSUE THREAD

**Issue by moonandroid** [MKergall/osmbonuspack#250]
Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI. 

http://router.project-osrm.org/route/v1/driving/10.451525,51.16569;12.3850986,50.8100321?alternatives=true&overview=full&steps=true

Before 35-45 minutes it's working well but now not working.
Can you help me for this issue ?

**Comment by MKergall** [comment]
Osrm seems broken currently.

**Comment by MKergall** [comment]
Working again.

**Comment by mancj** [comment]
I get the same error. how to fix it?

**Comment by MKergall** [comment]
OSRM service is broken again. Try any route on http://map.project-osrm.org to check that. 
Please report such issues on OSRM service directly to OSRM project. 

You can wait, or you can switch to another route provider (GraphHopper).
