### ISSUE TITLE
map using geojson is very slow

### ISSUE THREAD

**Issue by Rhtyme** [MKergall/osmbonuspack#252]
Hi, firstly thank you very much for this great library. It's really very useful. I've cloned your 'osmbonuspack' project into my local machine and tried to load geoJson objects into map and it works fine. Then I created new project and tried to load geoJson into map:

	private void setupGeoJson() {
                String gJson = null;
		try {
			gJson = getGeoString();
		} catch (IOException e) {
			e.printStackTrace();
		}

		mKmlGeoJson = new KmlDocument();
		mKmlGeoJson.parseGeoJSON(gJson);
		FolderOverlay myOverLay = (FolderOverlay) mKmlGeoJson.mKmlRoot.
				buildOverlay(map, null, null, mKmlGeoJson);
		map.getOverlays().add(myOverLay);
		map.getController().setZoom(16);
		map.getController().setCenter(new GeoPoint(2.9691, 101.7146));
		map.invalidate();
	}

	private String getGeoString() throws IOException {
		InputStream is = getResources().openRawResource(R.raw.json_lg1);
		Writer writer = new StringWriter();
		char[] buffer = new char[1024];
		try {
			Reader reader = new BufferedReader(new InputStreamReader(is, "UTF-8"));
			int n;
			while ((n = reader.read(buffer)) != -1) {
				writer.write(buffer, 0, n);
			}
		} finally {
			is.close();
		}

		String jsonString = writer.toString();
		return jsonString;
	}

All other piece of code is such as MainActivity in OSMBonusPackTuto. I'm calling  `setupGeoJson()`  method at the end of onCreate() method. But the map is working very slow when zooming out/in (when loading). If I switch off using `setupGeoJson()` method the map is working fine. How to solve it?

**Comment by MKergall** [comment]
Looks like you found the solution: 
http://stackoverflow.com/questions/39932857/android-osm-map-using-geojson-is-very-slow

**Comment by Rhtyme** [comment]
It turned out that I had forgotten to disable hardware accelerations. And this problem is solved via disabling hardware acceleration. Now it works fine even with hundreds of GeoJson elements. Thanks again for this great library))
