### ISSUE TITLE
PathOverlay not working with API Version 5.

### ISSUE THREAD

**Issue by moonandroid** [MKergall/osmbonuspack#253]
Before version 5,i have used below code snippet but it's now not working with version-5

  PathOverlay myPath = new PathOverlay(Color.BLUE, getActivity());
            Paint pPaint = myPath.getPaint();
            pPaint.setStrokeWidth(5);
            myPath.setPaint(pPaint);
ArrayList<GeoPoint> listPoints = new ArrayList<>();
            for (int i = 0; i < mArrayListmLatLng.size(); i++) {//mArrayListmLatLng have lat-long array list
                String[] str = mArrayListmLatLng.get(i).toString().split("lat/lng: ");
                String str1 = str[1].toString().substring(1, str[1].length() - 1);
                String[] str2 = str1.toString().split(",");
                double startLat = Double.valueOf(str2[0].trim()).doubleValue();
                double startlong = Double.valueOf(str2[1].trim()).doubleValue();
                GeoPoint geoStart = new GeoPoint(startLat, startlong);
                listPoints.add(geoStart);
               myPath.addPoint(geoStart);
            }
            mapView.getOverlays().add(myPath);

So,i have updated code and used Polyline with RoadManager 

   Polyline roadOverlay;
            RoadManager roadManager = new OSRMRoadManager(getActivity(),userAgent);
            ArrayList<GeoPoint> listPoints = new ArrayList<>();
            for (int i = 0; i < mArrayListmLatLng.size(); i++) {//mArrayListmLatLng have lat-long array list
                String[] str = mArrayListmLatLng.get(i).toString().split("lat/lng: ");
                String str1 = str[1].toString().substring(1, str[1].length() - 1);
                String[] str2 = str1.toString().split(",");
                double startLat = Double.valueOf(str2[0].trim()).doubleValue();
                double startlong = Double.valueOf(str2[1].trim()).doubleValue();
                GeoPoint geoStart = new GeoPoint(startLat, startlong);
                listPoints.add(geoStart);
                myPath.addPoint(geoStart);
            }
            Road road = roadManager.getRoad(listPoints);
            roadOverlay = RoadManager.buildRoadOverlay(road,Color.BLUE,5);
            mapView.getOverlays().add(roadOverlay);

When i used above updated code then route will change means displaying wrong route.
Can you please help me what is wrong over here ?

**Comment by moonandroid** [comment]
Before version 5,i have used below code snippet but it's now not working with version-5

PathOverlay myPath = new PathOverlay(Color.BLUE, getActivity());
Paint pPaint = myPath.getPaint();
pPaint.setStrokeWidth(5);
myPath.setPaint(pPaint);
ArrayList listPoints = new ArrayList<>();
for (int i = 0; i < mArrayListmLatLng.size(); i++) {//mArrayListmLatLng have lat-long array list
String[] str = mArrayListmLatLng.get(i).toString().split("lat/lng: ");
String str1 = str[1].toString().substring(1, str[1].length() - 1);
String[] str2 = str1.toString().split(",");
double startLat = Double.valueOf(str2[0].trim()).doubleValue();
double startlong = Double.valueOf(str2[1].trim()).doubleValue();
GeoPoint geoStart = new GeoPoint(startLat, startlong);
listPoints.add(geoStart);
myPath.addPoint(geoStart);
}
mapView.getOverlays().add(myPath);

So,i have updated code and used Polyline with RoadManager

Polyline roadOverlay;
RoadManager roadManager = new OSRMRoadManager(getActivity(),userAgent);
ArrayList listPoints = new ArrayList<>();
for (int i = 0; i < mArrayListmLatLng.size(); i++) {//mArrayListmLatLng have lat-long array list
String[] str = mArrayListmLatLng.get(i).toString().split("lat/lng: ");
String str1 = str[1].toString().substring(1, str[1].length() - 1);
String[] str2 = str1.toString().split(",");
double startLat = Double.valueOf(str2[0].trim()).doubleValue();
double startlong = Double.valueOf(str2[1].trim()).doubleValue();
GeoPoint geoStart = new GeoPoint(startLat, startlong);
listPoints.add(geoStart);
myPath.addPoint(geoStart);
}
Road road = roadManager.getRoad(listPoints);
roadOverlay = RoadManager.buildRoadOverlay(road,Color.BLUE,5);
mapView.getOverlays().add(roadOverlay);

When i used above updated code then route will change means displaying wrong route.
Can you please help me what is wrong over here ?

**Comment by MKergall** [comment]
There are 2 different concepts: Polyline overlay, and Road/RoadManager mechanism: 

- Polyline is a replacement of PathOverlay, just bringing better compatibility with Google Maps API (and support for bubbles if needed). 

- Road/RoadManager is a method to request an online service, giving you the shortest route between 2 points. It is ususally displayed with a Polyline. 

Just remove all the stuff you added about Road/RoadManager, just use Polyline instead of PathOverlay, and everything should be as before.

**Comment by moonandroid** [comment]
Thanks for reply,

But Polyline not working for add GeoPoint.
I got below error for  myPath.addPoint(geoStart);.

'addPoint(org.osmdroid.util.GeoPoint)' has protected access in 'org.osmdroid.views.overlay.Polyline'


My code snippet :

 Polyline  myPath = new Polyline (getActivity());
            myPath.setWidth(5);
            myPath.setColor(Color.BLUE);

            ArrayList listPoints = new ArrayList<>();
            for (int i = 0; i < mArrayListmLatLng.size(); i++) {//mArrayListmLatLng have lat-long array list
                String[] str = mArrayListmLatLng.get(i).toString().split("lat/lng: ");
                String str1 = str[1].toString().substring(1, str[1].length() - 1);
                String[] str2 = str1.toString().split(",");
                double startLat = Double.valueOf(str2[0].trim()).doubleValue();
                double startlong = Double.valueOf(str2[1].trim()).doubleValue();
                GeoPoint geoStart = new GeoPoint(startLat, startlong);
                listPoints.add(geoStart);
                myPath.addPoint(geoStart);
            }
            mapView.getOverlays().add(myPath);

**Comment by MKergall** [comment]
add all your points in an ArrayList, then: myPath.setPoints(list)

**Comment by moonandroid** [comment]
Thanks
