### ISSUE TITLE
Android app started to be busy when route api is not awailable

### ISSUE THREAD

**Issue by avlopatin** [MKergall/osmbonuspack#254]
We are using this url for route http://router.project-osrm.org/route/v1/driving/
Right now it's not available - returns 504 response.

It was bad surprise for us when our Android app had started to be busy.

Please, let's know how we can avoid such situations in future

**Comment by MKergall** [comment]
If availability of OSRM free demo service is not sufficient to your needs, you can: 
- Install and manage OSRM on your own server
- or switch to GraphHopperRoadManager or MapQuestRoadManager
