### ISSUE TITLE
RadiusMarkerClusterer and deprecated 1E6 variables

### ISSUE THREAD

**Issue by SQ5TB** [MKergall/osmbonuspack#255]
I have problem with osmbonuspack and new API 5.5
Application stops when RadiusMarkerClusterer is used. In this API BoundingBoxE6 is deprecated. 
Method convertRadiusToMeters(MapView mapView) is using not existing in this version 
function BoundingBoxE6 mapView.getBoundingBox();

**Comment by MKergall** [comment]
osmdroid 5.5 must be used with at least OSMBonusPack 5.9. 
In 5.9, RadiusMarkerClusterer is not using BoundingBoxE6, and is working fine. 
You are probably using an outdated OSMBonusPack version.

**Comment by SQ5TB** [comment]
Thanks. Now works fine. I was using 5.8.1 version. It would be nice to add current stable version number at the top of the readme file / page.

**Comment by spyhunter99** [comment]
If gradle and the android plugin actually honored AAR project dependencies,
this wouldn't have ever been an issue. But it doesn't.

On Sat, Oct 15, 2016 at 11:38 AM, Bogusław Ciastek <notifications@github.com
