### ISSUE TITLE
Make draggable false

### ISSUE THREAD

**Issue by skyritsis** [MKergall/osmbonuspack#256]
Hello, I've been using your library, and I'm able to fetch a kml file, and put it on an overlay in my mapping application. I just wanted to ask you, if and how, I could make the resulting points, to be not draggable. I've been searching for such a feature, the same way it is implemented for markers, but I have not been able to locate it.

Thank you in advance,
-SK

**Comment by MKergall** [comment]
Implement your own "Styler": 
https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4#132-advanced-styling-with-the-styler

**Comment by skyritsis** [comment]
Thank you for the reply.
