### ISSUE TITLE
Try removing the @aar for osmdroid dependency

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#257]
@MKergall I've been reading up on gradle dependency nonsense. It looks like if you the @ aar  bit is added, none of the transitive dependencies are included. If it's stripped, and people use your library, gradle 'should' bring in the correct dependency for osmdroid too.

**Comment by MKergall** [comment]
In fact, this is already what I've recommended, here: https://github.com/MKergall/osmbonuspack/wiki/HowToInclude#11-including-using-jitpack
and in the build.gradle of the tutorial. 

Or am I missing something?

**Comment by spyhunter99** [comment]
I think i was referring to this line
https://github.com/MKergall/osmbonuspack/blob/master/OSMBonusPack/build.gradle#L25

but i don't think it matters too much since osmdroid doesn't have any
dependencies. feel free to close
