### ISSUE TITLE
The cluster is counting itself

### ISSUE THREAD

**Issue by 2ndGAB** [MKergall/osmbonuspack#260]
Hi Mickael,
I just discovered that the cluster is counting itself so when you include 4 markers in a cluster, you display 5.

**Comment by MKergall** [comment]
I don't see what you describe, neither in the code, not in actual use cases (I just tried with 4 markers in a RadiusMarkerClusterer, it was displaying 4). 
Which clusterer are you using?

**Comment by 2ndGAB** [comment]
Ok, I've extended RadiusMarkerClusterer, so I'm going to see if something can explain it in my code.

**Comment by MKergall** [comment]
any news?

**Comment by 2ndGAB** [comment]
I think I was wrong, on some test I just made this morning, everything is normal. But I overloaded the cluster to exclude some kind og markers from it and I think the problem could come fromt that.
But I didn't find a clear case to investigate at the moment.
I think you can close the issue anyway.
Sorry.
