### ISSUE TITLE
"buildRoadOverlay" cannot be resolved

### ISSUE THREAD

**Issue by TheGlave** [MKergall/osmbonuspack#261]
Hello,

i am trying to create a route just like in your tutorial. Everything looks fine, except that Android Studio wont resolve the method `Polyline roadOverlay = RoadManager.buildRoadOverlay(road, this);`. "(road, this)" is underlined in red.

Do you know what I can do about this?

Here is the full method:
```
    public void findLocation(int view){
        //This gets me a place I got out of my database
        DB_Verladestellen db = new DB_Verladestellen(this);
        DB_Place place = new DB_Place();
        place = db.getDBPlace(view);

        //Points to the place on the map
        MapView map = (MapView) findViewById(R.id.map);
        IMapController mapController = map.getController();
        mapController.setZoom(17);
        GeoPoint Location = new GeoPoint(Double.parseDouble(place.getLongitude())  , Double.parseDouble(place.getLatitude()));
        mapController.animateTo(Location);

        //Creates the marker
        Marker startMarker = new Marker(map);
        startMarker.setPosition(Location);
        startMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
        map.getOverlays().add(startMarker);
        startMarker.setTitle(place.getName());

        //creates the route
        RoadManager roadManager = new OSRMRoadManager(this);
        ArrayList<GeoPoint> waypoints = new ArrayList<GeoPoint>();
        GeoPoint myLocation = new GeoPoint(51.488978, 6.746994);
        waypoints.add(Location);
        waypoints.add(myLocation);
        Road road = roadManager.getRoad(waypoints);
        Polyline roadOverlay = RoadManager.buildRoadOverlay(road, this);
        map.getOverlays().add(roadOverlay);
    }
```

**Comment by MKergall** [comment]
Probably a configuration issue (in gradle files?). 
Compare your files with those from the tutorial project.

**Comment by Duodecimus** [comment]
I've noticed that when I lookup RoadManager.java that buildRoadOverlay only takes one arguement of type Road. There isn't any handling of 'this' at all.

**Comment by TheGlave** [comment]
I checked and my gradle files are identical to your tutorial. I already used markers in my projekt. I have to admit I am not the most experienced programmer and I do not understand the "this" statement completely. 

But if there is no handling of "this" in the roadmanager, as Duodecimus said, is there another way to do what I want to do?

**Comment by Duodecimus** [comment]
It actually works fine if you just pass it a Road. 
`Polyline roadOverlay = RoadManager.buildRoadOverlay(road);` 
Generates a line just fine for me.

**Comment by TheGlave** [comment]
If I do that the app crashes as soon as I click on the button for the route: 

> E/AndroidRuntime: FATAL EXCEPTION: main
>                   Process: com.example.ahok.thyssenkrupp_navigation, PID: 14399
>                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ahok.thyssenkrupp_navigation/com.example.ahok.thyssenkrupp_navigation.UI_MainActivity}: android.os.NetworkOnMainThreadException
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
>                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>                       at android.os.Handler.dispatchMessage(Handler.java:102)
>                       at android.os.Looper.loop(Looper.java:148)
>                       at android.app.ActivityThread.main(ActivityThread.java:5417)
>                       at java.lang.reflect.Method.invoke(Native Method)
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                    Caused by: android.os.NetworkOnMainThreadException
>                       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
>                       at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
>                       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
>                       at java.net.InetAddress.getAllByName(InetAddress.java:215)
>                       at okhttp3.Dns$1.lookup(Dns.java:39)
>                       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
>                       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
>                       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
>                       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
>                       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
>                       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
>                       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
>                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>                       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
>                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>                       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
>                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
>                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
>                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
>                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
>                       at okhttp3.RealCall.execute(RealCall.java:60)
>                       at org.osmdroid.bonuspack.utils.HttpConnection.doGet(HttpConnection.java:68)
>                       at org.osmdroid.bonuspack.utils.BonusPackHelper.requestStringFromUrl(BonusPackHelper.java:70)
>                       at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoads(OSRMRoadManager.java:192)
>                       at org.osmdroid.bonuspack.routing.OSRMRoadManager.getRoad(OSRMRoadManager.java:284)
>                       at com.example.ahok.thyssenkrupp_navigation.UI_MainActivity.findLocation(UI_MainActivity.java:198)
>                       at com.example.ahok.thyssenkrupp_navigation.UI_MainActivity.onCreate(UI_MainActivity.java:98)
>                       at android.app.Activity.performCreate(Activity.java:6237)
>                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
>                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
>                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>                       at android.os.Handler.dispatchMessage(Handler.java:102) 
>                       at android.os.Looper.loop(Looper.java:148) 
>                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                       at java.lang.reflect.Method.invoke(Native Method) 
>                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by TheGlave** [comment]
The [waypoints](http://www.pic-upload.de/view-32091806/debugger.png.html) look fine, dont they?

**Comment by Duodecimus** [comment]
Yeah, you should do all networky things on an async task so your UI doesn't hang while you wait for a response.

`Road road = roadManager.getRoad(waypoints);`
`Polyline roadOverlay = RoadManager.buildRoadOverlay(road, this);`
These lines of code specifically.

This is beyond the scope of this issue though.

**Comment by TheGlave** [comment]
Alright, thankyou for your help, after extensive research on AsyncTasks I somehow made it work. I will close this, but also open a different issue.

**Comment by MKergall** [comment]
Back to the initial issue: Context (the "this") parameter is not needed anymore in buildRoadOverlay. 
I just updated the tutorial page.
