### ISSUE TITLE
Can you create own nodes and can the routing overlays be costumized?

### ISSUE THREAD

**Issue by TheGlave** [MKergall/osmbonuspack#262]
1. Can I make the road overlay thicker? [It is really hard to see](http://www.pic-upload.de/view-32094927/routing.png.html).

2. Is there anyway to create own nodes? The purpose of my app is to make it possible to navigate on the factory premises of my work. As you can see in my linked image above, the route stops where the public roads stop and the factory premises starts. Ideally it should create a route all the way to the marker.

**Comment by MKergall** [comment]
Please ask questions on StackOverflow, not as project issues.
