### ISSUE TITLE
Getting the KML/Json value to store in specific variable ?

### ISSUE THREAD

**Issue by rahullab** [MKergall/osmbonuspack#264]
I am working on Overpass API as given in example

     //13.1 Simple styling
            Drawable defaultMarker = ResourcesCompat.getDrawable(getResources(), R.drawable.marker_kml_point, null);
            Bitmap defaultBitmap = ((BitmapDrawable) defaultMarker).getBitmap();
            Style defaultStyle = new Style(defaultBitmap, 0x911010AA, 50.0f, 0x20CC1010);
            //13.2 Advanced styling with Styler
            KmlFeature.Styler styler = new MyKmlStyler(defaultStyle);

            FolderOverlay kmlOverlay = (FolderOverlay) mKmlDocument.mKmlRoot.buildOverlay(map, defaultStyle, styler, mKmlDocument);

            map.getOverlays().add(kmlOverlay);
            BoundingBox bb = mKmlDocument.mKmlRoot.getBoundingBox();

        }`

how can i store the mname in some variable. And how is the popup information displayed when touched on the Marker ? What can I do if I want to show only the marker and name but not the description ?

**Comment by MKergall** [comment]
Duplicated with [StackOverflow question](http://stackoverflow.com/questions/40715139/how-could-i-display-only-name-when-pressing-the-marker).
