### ISSUE TITLE
Slow zoom/swipe  with huge kml or geojson data

### ISSUE THREAD

**Issue by trandinh135** [MKergall/osmbonuspack#265]
I have a map file( geojson/kml ) ~5000/5.5mb LineString Features . It was displayed on mobile, but not smooth in gesture with map. how can i fix it

**Comment by MKergall** [comment]
No simple solution. You are reaching the limits of your device performance. 

You could try to simplify your LineStrings. 
Either in your app once the file is loaded, using the [DouglasPeucker reducer](https://github.com/MKergall/osmbonuspack/blob/master/OSMBonusPack/src/main/java/org/osmdroid/bonuspack/utils/DouglasPeuckerReducer.java) included in OSMBonusPack. 
Or - even better - on your KML/Geojson file itself.

**Comment by trandinh135** [comment]
ok. thanks
