### ISSUE TITLE
Read KML file from Assets directory using parseKMLFile

### ISSUE THREAD

**Issue by israel05** [MKergall/osmbonuspack#266]
Hi!
I am unable to read a example.kml file stored in assets directory. Whenever I try kmlDocument.parseKMLFile("file:///android_assets/example.kml") or kmlDocument.parseKMLFile("file:///assets/example.kml") or 
kmlDocument.parseKMLFile("android_assets/example.kml") or
kmlDocument.parseKMLFile("assets/example.kml") 
I get an ENOENT (no file or directoy error)
IF i try the kmlDocument.parseKMLUrl("file:///example.kml") or any other combinations I get an exceptions.

Could you help us, please?

**Comment by MKergall** [comment]
Android Assets cannot be read as regular system Files. You have to use the [AssetManager](https://developer.android.com/reference/android/content/res/AssetManager.html). 
See for instance [this post](http://stackoverflow.com/questions/8495908/android-assetmanager). 

So a possible solution:
```
InputStream inputStream = AssetManager.open(myfileName);
myKml.parseKMLStream(stream, null);
```

**Comment by israel05** [comment]
Thank you very much for the answer, but what if I try to use parseKMLFile from the "res" directory, In some places they put a "RAW" folder inside the "res" directory.
If I try to load the KML using the code you give us it says "Non-static method 'open(java.lang.String)' cannot be referenced form a static context.
We are realy stuck at this point. Reading the Demo files does not specify how to read a file directly from a directory but from an previosly downloaded file. What if we want to work totally offline? Wouldnt be better to store the KML in the APK?

Thanks again

**Comment by israel05** [comment]
Ok, so far i find the file but I get a Parser error

> I/OsmDroid: sdcard state: mounted
W/System.err: org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: no element found
W/System.err:     at org.apache.harmony.xml.ExpatParser.finish(ExpatParser.java:545)
W/System.err:     at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:475)
W/System.err:     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
W/System.err:     at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
W/System.err:     at javax.xml.parsers.SAXParser.parse(SAXParser.java:390)
W/System.err:     at javax.xml.parsers.SAXParser.parse(SAXParser.java:187)
W/System.err:     at org.osmdroid.bonuspack.kml.KmlDocument.parseKMLStream(KmlDocument.java:307)
W/System.err:     at com.example.israel.egurenalfa.Mapa$override.onCreate(Mapa.java:242)
W/System.err:     at com.example.israel.egurenalfa.Mapa$override.access$dispatch(Mapa.java)
W/System.err:     at com.example.israel.egurenalfa.Mapa.onCreate(Mapa.java:0)
W/System.err:     at android.app.Activity.performCreate(Activity.java:6575)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3137)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3294)
W/System.err:     at android.app.ActivityThread.access$1000(ActivityThread.java:210)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:     at android.os.Looper.loop(Looper.java:145)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6938)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)


I took the KML from here https://developers.google.com/kml/documentation/KML_Samples.kml so I suppose it must be a good formed KML file

and the code to read it is 
`        KmlDocument kmlDocument = new KmlDocument(); //creamos el KML

        AssetManager assetManager=getAssets();
        InputStream streamDeKml;
        try {
            streamDeKml=assetManager.open("raw/KML_Samples.kml");
            int size=streamDeKml.available();
            byte[] buffer=new byte[size];
            streamDeKml.read(buffer);
            kmlDocument.parseKMLStream(streamDeKml, null); // lo mentemos en el mapa
           streamDeKml.close();   // como hemos terminado con el Stream ddel KML ya lo podemos borrar.


        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
        }

`

Any ideas? thanks again

**Comment by MKergall** [comment]
Remove those strange lines: 
```
int size=streamDeKml.available();
        byte[] buffer=new byte[size];
        streamDeKml.read(buffer);

```
Note that in your Google KML sample, every folder and placemark is set as invisible - not very practical to see the result. But I tried, it loads correctly. 

If you have such issues to load from assets, you could just put your KML file somewhere on the SD card, and use kml.parseKMLFile.

**Comment by israel05** [comment]
And now all is working like a charm. I see that you have commented the tutorial, it is amazing the job you are doing. Is there anyway we can compensate your effort?

**Comment by MKergall** [comment]
No paypal account yet :-)

Raising positive feedback (as you did) is an excellent way to compensate our efforts. 
You can also provide information to complement this page: [ApplicationsUsingOSMBonusPack].
