### ISSUE TITLE
OverpassAPIProvider: Allow to specify custom tags or return list of all tags

### ISSUE THREAD

**Issue by scaidermern** [MKergall/osmbonuspack#268]
`getPOIsFromUrl()` looks at a pre-defined list of tags. Sometimes we want to obtain information contained in other tags like `operator`, `opening_hours`, `addr:*` and so on. Either allow to pass a custom list of tags to return or alternatively store a set of all tags in the returned POI object.

**Comment by MKergall** [comment]
Why not use the KML flavor addInKmlFolder()? It is pushing all tags in ExtendedData. 
I would like to let getPOIsFromUrl() as much simple and user-friendly as possible.

**Comment by scaidermern** [comment]
> Why not use the KML flavor addInKmlFolder()?

I guess that's a valid alternative. Thanks.

**Comment by scaidermern** [comment]
The Wiki still misses a nice example for `addInKmlFolder()` and `buildOverlay()`. It would be nice if you can add one.
