### ISSUE TITLE
OverpassAPIProvider: Support queries with the around keyword

### ISSUE THREAD

**Issue by scaidermern** [MKergall/osmbonuspack#269]
Currently `urlForPOISearch()` requires a bounding box. It would be nice to have an alternative method using the `around` query and thus requiring a position and a radius instead of a bounding box as arguments.

**Comment by MKergall** [comment]
If urlForPOISearch() doesn't match your need, you can build your own query url (it' just a string building), and then use it in getPOIsFromUrl(). 

Now, looking in Overpass QL doc, I didn't found a filter based on position+radius. 
There is a "By polygon" filter, so if you transform your "circle" area to the approaching polygon, it should do the job. Maybe with a performance impact?

**Comment by scaidermern** [comment]
> If urlForPOISearch() doesn't match your need, you can build your own query url (it' just a string building), and then use it in getPOIsFromUrl().

Yes. However this requires knowledge about Overpass API.

> Now, looking in Overpass QL doc, I didn't found a filter based on position+radius.

See https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Relative_to_other_elements_.28around.29

Here is a simple example: `node(around:10000.0,50.7,7.1)[amenity=cinema];out;` (see it on [overpass turbo](http://overpass-turbo.eu/s/kGp).

**Comment by scaidermern** [comment]
Has this been implemented or rejected? Please add a short description when closing issues.

**Comment by MKergall** [comment]
Not implemented. 
You can build your own query url for specific needs, it' just a string building.
