### ISSUE TITLE
How to remove nodeMarkers

### ISSUE THREAD

**Issue by Mantj** [MKergall/osmbonuspack#270]
I show my nodeMarker by using:
```
Drawable nodeIcon = getResources().getDrawable(R.drawable.marker_node);
        for (int i=0;i<il.getSize();i++){
            nodeMarkerOffNav = new Marker(map);
            nodeMarkerOffNav.setPosition(new     GeoPoint(il.get(i).getPoints().getLatitude(0),il.get(i).getPoints().getLongitude(0)));
            nodeMarkerOffNav.setIcon(nodeIcon);
            nodeMarkerOffNav.setTitle(il.get(i).getName());
            map.getOverlays().add(nodeMarkerOffNav);
```

But when I want to remove them with:
`map.getOverlays().remove(nodeMarkerOffNav);`
There is nothing happen.What's wrong?How could I do?
Thank you~

**Comment by spyhunter99** [comment]
Hmm, try sticking in a map.invalidate call.

**Comment by Mantj** [comment]
Sorry, I haven't notice your answer.
I add map.invalidate(); so my code looks like:
```
map.getOverlays().remove(nodeMarkerOffNav);
map.invalidate();
```
But nothing change,just the last node remove, but the other nodes still stay on the map.

**Comment by spyhunter99** [comment]
uhhh oh. You can call map.getOverlays().clear(); to remove all of them.

**Comment by MKergall** [comment]
Was more a request for help (=> to ask on StackOverflow)
