### ISSUE TITLE
Broken link in Tutorial_2 wiki page

### ISSUE THREAD

**Issue by scaidermern** [MKergall/osmbonuspack#271]
This page contains a dead link pointing to http://code.google.com/p/osmbonuspack/source/browse/trunk/OSMNavigator/res/values/poi_tags.xml. However the correct URL is https://github.com/MKergall/osmbonuspack/blob/master/OSMNavigator/src/main/res/values/poi_tags.xml.

**Comment by MKergall** [comment]
Fixed. Thanks.
