### ISSUE TITLE
Bing REST API support?

### ISSUE THREAD

**Issue by spyhunter99** [MKergall/osmbonuspack#275]
Doesn't look like this is in the code base at the moment, but if implemented it can provide both POI and routing directions

**Comment by MKergall** [comment]
I had a look. Some points I don't like: 

1) [T&C](https://www.microsoft.com/maps/product/terms.html), long enough to require a lawyer to work with. I'm even not sure we are allowed to use it for an Android app. 

2) On Route API features: 
  - Alternate routes ("maxSolutions") only available on few countries (and not including mine)
  - Route path returned as a list of points => time consuming to parse on very long paths. 

3) My "most expected feature" for such a service - compared with the features in the free services we already have - is the route calculation depending on real-time traffic info. This feature is not available (their "traffic incident data" is far from what I expect).

**Comment by spyhunter99** [comment]
well thanks for looking into it.
