### ISSUE TITLE
Routes don't draws sometimes.

### ISSUE THREAD

**Issue by lander1337** [MKergall/osmbonuspack#276]
Hello.

I have a problem. Some times my application can't draw route, it's just show a direct line and some times it's works fine. This "bug" start since this week. I feels like it's a problem with a OSRM routes service, it's just shutdown for some reason and dont give the response. So how can i get where is a problem?  

Using:
'osmdroid-android:5.4.1'
'osmbonuspack:5.9'

**Comment by MKergall** [comment]
If it's occasional, probably an issue on OSRM server. 
See here to see how to analyze this kind of issue: http://stackoverflow.com/questions/21213224/roadmanager-for-osmdroid-error
