### ISSUE TITLE
RoadManager - OSRMRoadManager not working

### ISSUE THREAD

**Issue by trandinh135** [MKergall/osmbonuspack#279]
I tested two routing methods,  OSRMRoadManager  and MapQuestRoadManager,
MapQuestRoadManager work but OSRMRoadManager  don't. OSRMRoadManager  return a straight line between two points
ArrayList<GeoPoint> waypoints = new ArrayList<GeoPoint>();
        GeoPoint startPoint = new GeoPoint(21.016185, 105.597010);
        waypoints.add(startPoint);
        GeoPoint endPoint = new GeoPoint(21.100669, 106.524611);
        waypoints.add(endPoint);

**Comment by Deepakb9292** [comment]
Open street map is returning straight line between two locations. Can you please help with this.

**Comment by MKergall** [comment]
See here: http://stackoverflow.com/questions/21213224/roadmanager-for-osmdroid-error

OSRM routing on their public site is currently down.
