### ISSUE TITLE
ParseJSON - com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject 

### ISSUE THREAD

**Issue by zolden** [MKergall/osmbonuspack#282]
Hi, I need consume my GeoJSON which is represent route from my service. GeoJSON looks like this:
http://pastebin.com/GJWYNkAq

Here is my function for display GeoJSON in OsmDroid MapView (map variable):
```
public void viewRoute(String geoJson) {
    KmlDocument kmlDocument = new KmlDocument();
    kmlDocument.parseGeoJSON(geoJson); //application is crashed here
    FolderOverlay myOverLay = (FolderOverlay) kmlDocument.mKmlRoot.buildOverlay(map, null, null, kmlDocument);
    map.getOverlays().add(myOverLay);
    map.invalidate();
}
```

For consume my Rest api I am using OkHTTP client, after recieved GeoJSON in string, I pass it into function  viewRoute, and I got following issues:

> java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:191) at org.osmdroid.bonuspack.kml.KmlPlacemark.(KmlPlacemark.java:89) at org.osmdroid.bonuspack.kml.KmlFeature.parseGeoJSON(KmlFeature.java:237) at org.osmdroid.bonuspack.kml.KmlFolder.(KmlFolder.java:62) at org.osmdroid.bonuspack.kml.KmlFeature.parseGeoJSON(KmlFeature.java:235) at org.osmdroid.bonuspack.kml.KmlDocument.parseGeoJSON(KmlDocument.java:1097) at org.osmdroid.bonuspack.kml.KmlDocument.parseGeoJSON(KmlDocument.java:1112) at bachelor.vsb.martin.osmdroidclient.MainActivity.viewRoute(MainActivity.java:137) at bachelor.vsb.martin.osmdroidclient.MainActivity$1.onResponse(MainActivity.java:127) at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135) at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) at java.lang.Thread.run(Thread.java:761)

**Comment by MKergall** [comment]
"geometry": null is not supported. I never noticed it was part of the GeoJSON spec!

I will add support for that - probably by ignoring such Features. 
In the meantime, just remove this Feature from your file and it will work fine.

**Comment by MKergall** [comment]
#2cb85bc pushed. It now supports your file. 

At saving, "geometry:null" is not in the file produced. To be investigated.

**Comment by MKergall** [comment]
Similar issue will occur with "properties:null". 

The spec says: "The value of the properties member is an object (any JSON object or a JSON null value)", 
but JSON null value is not supported yet.
