### ISSUE TITLE
Problem with including osm bonus pack library 

### ISSUE THREAD

**Issue by elisavetkaramtzioti** [MKergall/osmbonuspack#283]
Hello,

I'm trying to include the osmbonuspack library to my android studio project according to your instructions so I :
downloaded osmbonuspack_v6.3.aar (https://github.com/MKergall/osmbonuspack/releases),
I created a folder "libs" and moved the .aar there and 
in my app's build.gradle file I added the following: 
compile(name:'osmbonuspack_v6.3', ext:'aar')
compile 'org.osmdroid:osmdroid-android:5.6.4'
compile 'org.apache.commons:commons-lang3:3.3.2'
compile 'com.google.code.gson:gson:2.7'
compile 'com.squareup.okhttp3:okhttp:3.4.1' 

and I updated the "repositories" too, as you suggest.
But when I sync the project it fails and appears an error with a message "Failed to resolve osmbonuspack_v6.3.aar". I also tried the other way, including using jitpack, but the same happened, while the error mesage was : Failed to resolve:com.github.MKergall:osmbonuspack:6.2 

I can't understand what is going wrong in both ways of including the library since I wasn't able to find anything more helpful than your repository to start with. 

I really appreciate any help you can provide,
Elisavet

**Comment by MKergall** [comment]
Try using jitpack following this: https://github.com/MKergall/osmbonuspack/wiki/HowToInclude#11-including-using-jitpack

There are sometimes strange errors with gradle. Try also to clean/rebuild your project.
