### ISSUE TITLE
Markers when map rotation

### ISSUE THREAD

**Issue by mlendl** [MKergall/osmbonuspack#285]
Hi,
I have markers like pins with ANCHOR_CENTER, ANCHOR_BOTTOM. When map is rotating, the markers are rotating as well and remain in the same vertical position, what is OK. But it seems, that clicking area is not moved, and result is, that click on the marker has no effect. I have to click somewhere around the marker. E. g. if map orientation is 180 degrees, I have to click below the marker. Can I solve this somehow or is it Osmbonuspack issue?

**Comment by MKergall** [comment]
Yes this is a known issue. Mentionned in the javadoc.
