### ISSUE TITLE
Marker Clusters Not Working

### ISSUE THREAD

**Issue by ventenni** [MKergall/osmbonuspack#286]
It seems that a few of the functions have been deprecated in the last couple of years and the tutorial for making clusters no longer applies. I'm able to place single markers on the map but can't get further than that.

I'll add that this is the first time I've used osmbonuspack and Android Studio so apologies if it's something simple.

**Comment by MKergall** [comment]
Which functions are deprecated? What is not applying anymore? 
You can see the clustering in action by copying/building the tutorial project. I can confirm it works!

**Comment by ventenni** [comment]
The getDrawable function is deprecated. It still kind of works but requires another parameter input. 

I think I may be doing it slightly wrong. I've done the first marker overlay tutorial and skipped to try and implement the Places of Interest and Marker Clusters. Should I be doing all of the tutorial for it to work?

**Comment by MKergall** [comment]
The tuto on clustering assumes and states you followed tutos 1 and 2. 
This said, if you prefer not to use tutos, you can do as you want. You can also look straight at the final code in the tutorial project.

**Comment by ventenni** [comment]
You can close this one. It's all sorted now. 

Cheers for the help.
