### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by HaniKu** [MKergall/osmbonuspack#287]
Im developing android app on android 2.3 where minSdkVersion is 9. Is it possible to set osmbonuspack work on this SdkVersion?

**Comment by MKergall** [comment]
SDK 9 has now disapeared from the radar of Google [Dashboard](https://developer.android.com/about/dashboards/index.html), with a distribution below 0.1%. 

I don't remember why I moved to min=10, but I had a reason. 

If you definitely need that, it's open source: get the code, and build the lib yourself.
