### ISSUE TITLE
OSRMRoadManager (url not available)

### ISSUE THREAD

**Issue by guenn** [MKergall/osmbonuspack#288]
Hello,

I'm trying to implement the tutorial_1. All work correctly but i have a direct line between the two points of my way.

On this forum, i see how to activate the trace, anc the getroad function throws TimeoutExecption.

The url generated is : http://router.project-osrm.org/route/v1/driving/-1.59309555,48.15622935;-1.692208,48.13274?alternatives=false&overview=full&steps=true

If i try this url on my PC, i receive a blank page.

Do you know why ?
Yesterday, the same code works well but not this morning. Is a change on project-osrm.org side ?

**Comment by MKergall** [comment]
OSRM public server is down again.

**Comment by guenn** [comment]
Ok. Thanks you for the reply.
