### ISSUE TITLE
kmldocument

### ISSUE THREAD

**Issue by HaniKu** [MKergall/osmbonuspack#291]
when im trying read from kml file a got error like "FATAL EXCEPTION: main java.lang.VerifyError: org/osmdroid/bonuspack/kml/KmlDocument " But it worked right 2 weeks ago.
My code, where im working with kmldocument
`File text = (File) tagPOI.getSelectedItem(); kmlDocument = new KmlDocument();
 Log.v("tralala","som za deklaraciou kmldok"); 
File file = kmlDocument.getDefaultPathForAndroid(text.toString()); 
mKmlOverlay = null; 
try { putKMLAsync(file); }
catch(Exception e){ }
catch(Error e){ }`
Im using osmbonuspack 6.3 and osmdroid 5.6.4
I would greatly appreciate if you could give me a solution. Thank you in advance.
![screenshot_3](https://user-images.githubusercontent.com/17992073/27293475-ce9f0cc2-5516-11e7-8fda-9126cac1e48e.png)

**Comment by MKergall** [comment]
On which line of your code?

**Comment by MKergall** [comment]
closed as no feedback.
