### ISSUE TITLE
Network proxy

### ISSUE THREAD

**Issue by gsantner** [MKergall/osmbonuspack#293]
Hi there,
is there any way to use reverse geocoding via a proxy? I only found options to set type/address of geocoder, but no way to set a network proxy. This breaks functionality if apps using this library behind a restrictive firewall. osmdroid itself is supporting use of `java.net.Proxy` now.

**Comment by MKergall** [comment]
Is your need for apps running on emulator from Android Studio? If yes, are those posts helping: 
https://stackoverflow.com/questions/36803553/how-do-i-add-http-proxy-to-an-android-emulator-launch-from-android-studio-2-0

**Comment by gsantner** [comment]
No. It's about users of apps using this library. About the connection to the Reverse Geocoding service, which goes directly to the http host without any way to set a network proxy

**Comment by MKergall** [comment]
On a mobile phone, I never set a proxy... What is the actual use case?

**Comment by gsantner** [comment]
* Corporate proxy: No other way to internet to internet then over proxy
* To be able to use the service anonymously, e.g. over tor
* To be able to access those services if they are blocked by local providers

**Comment by gsantner** [comment]
Closing some old stuff nobody seems to care about
