### ISSUE TITLE
is there a way to change cluster icons when the cluster spits in two smaller clusters on zooming?

### ISSUE THREAD

**Issue by fightaadeshfight** [MKergall/osmbonuspack#294]
I am implementing Clustering in my map. Everything works fine. The thing is when i zoom in and the cluster splits in smaller clusters the Icon remains the same. 

What i am trying to do is i want to set icons to the cluster based on the number of markers it has. Like it if the number is greater than 100: IMAGE A, Between 50-100: IMAGE B. and so on. How can i do that?

**Comment by MKergall** [comment]
Of course: follow the [tutorial](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_3).
