### ISSUE TITLE
why osmbonuspack not working on android 5,6 ?

### ISSUE THREAD

**Issue by DwiRomadon** [MKergall/osmbonuspack#296]
hai, i have a question,
Why osmbonuspack not working on android lolypop and marshmallow?
Thanks

**Comment by spyhunter99** [comment]
what versions of each exactly?

**Comment by spyhunter99** [comment]
you probably didn't prompt the user for permissions or you didn't declare the permissions per any of the guides.

**Comment by DwiRomadon** [comment]
oke thanks
