### ISSUE TITLE
How to set Drag Start and End listener on my custom osmdroid map?

### ISSUE THREAD

**Issue by himagaran** [MKergall/osmbonuspack#300]
> https://stackoverflow.com/questions/46191243/how-to-set-drag-start-and-end-listener-on-my-custom-osmdroid-map?noredirect=1#comment79385618_46191243
Looking for a working implementation, Thanks

**Comment by MKergall** [comment]
Drag of what? Marker? Map? Polyline?

**Comment by himagaran** [comment]
Its on Map, i need to set a toast message saying drag started on Drag-Start event and drag ended on Drag-End event.

**Comment by MKergall** [comment]
So it's pure osmdroid, not related to OSMBonusPack. I close this issue. 
Your StackOverflow question is the right way to request help.
