### ISSUE TITLE
android onRequestperm ok, but phone storage "crash" (android 6)

### ISSUE THREAD

**Issue by Berg230481** [MKergall/osmbonuspack#302]
Hello,
my problem is, when i install the app over android studio, load the tiles the first time, is all ok, i see the map, i see my telefonestorage at datamanager.

when i turn off the phone and restart, and look to the datamanger i can not see my telephone storage (intern storage)
an my app dont find the tile database!!!
camera ask my please insert sd card.

when i not turn off the phone all work perfekt.

Crash the database my storage???

`  private boolean checkPermission() {
        int result;
        List<String> listPermissionsNeeded = new ArrayList<>();
        for (String p : permissions) {
            result = ContextCompat.checkSelfPermission(this, p);
            if (result != PackageManager.PERMISSION_GRANTED) {
                Log.e("value", "value :"+p);
                listPermissionsNeeded.add(p);
              

            }
        }
        if (!listPermissionsNeeded.isEmpty()) {
            ActivityCompat.requestPermissions(this, listPermissionsNeeded.toArray(new String[listPermissionsNeeded.size()]), 100);
            maptrue=false;

            return false;
        }
        return true;

    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        if (requestCode == 100) {
            if (grantResults.length > 0
                    && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                Log.e("value", "value :Permission Granted, Now you can use local drive .");
                maptrue=true;

            }

        }

    }`

**Comment by spyhunter99** [comment]
hmm. funky android problem. I've seen all kinds of issues with storage devices being unexpectedly read only. I don't think osmdroid handles this scenario, It's a one startup, determine the best storage location at that time, then that's it. If a mount point is selected, that suddenly disappears, it's up to the app developer to detect this and switch on the fly.

**Comment by spyhunter99** [comment]
https://github.com/osmdroid/osmdroid/wiki/Important-notes-on-using-osmdroid-in-your-app#handling-cache-storage just added
