### ISSUE TITLE
Disabling showing info windows

### ISSUE THREAD

**Issue by aitbaali** [MKergall/osmbonuspack#303]
Hello, thank you for this great library.

I've successfully integrated the map and draw a KML document, now I want to disable all clicks on the map (except clicks on Markers) to prevent showing info windows that contains information about Placemark.

![capture d ecran 2017-10-09 a 09 20 02](https://user-images.githubusercontent.com/4213191/31330066-acd77aa0-acd4-11e7-858b-e39039759e13.png)

and customize the Marker info windows.

PlaceMark:
![capture d ecran 2017-10-09 a 09 40 10](https://user-images.githubusercontent.com/4213191/31330347-e8a13c14-acd5-11e7-92eb-f1aad9f69645.png)

**Comment by MKergall** [comment]
See #305 - similar question.

**Comment by jenia** [comment]
Unfortunately #305 is a completely different issue. Question #305 is asking "How to register a call back when user presses a feature". But I think the answer that MKergall has provided to #305 can be used here.
