### ISSUE TITLE
Href inclusion KMZ

### ISSUE THREAD

**Issue by namanmehta1997** [MKergall/osmbonuspack#304]
I want to create a KMZ file containing some images or videos. Is there any way to include href tag in kml file? If not how can I make it to do so?

**Comment by MKergall** [comment]
You want to create it, or you want to be able to read it in OSMBonusPack? I assume you create it "by hand" (text editor+zip, your own code, whatever...), and you read it using OSMBonusPack. 

Have a look here: https://github.com/MKergall/osmbonuspack/wiki/KML#kmz-support
This is answering this question.

**Comment by namanmehta1997** [comment]
I want to create it using bonuspack. The problem is to have a link between kml file and the associated image or videos. To create a link between kml and images is by using href reg, but there isn't any option of href tag to be added in a kml file using bonuspack. Creating a kmz file using ZIP utility is okay but my problem is to create a kml which contains a href tag, there is no provision to add a href tag in bonuspack

**Comment by MKergall** [comment]
KML model in OSMBonusPack is completely open: all members are public. 
So I really don't see the difficulty to set the IconStyle.mHref value as an external url:

`myIconStyle.mHref = "http://....";
`

During overlay building, IconStyle.setIcon will handle this value properly, to retrieve the actual bitmap and plot it as the Placemark icon. 

Now, are you speaking about description balloons? Then, images embedded in are not supported. And Videos are not supported at all. 
If this is what you need, you could implement it: define your own Styler, then, instead of opening an InfoWindow, open a full WebView.

**Comment by namanmehta1997** [comment]
So if I want to link an audio file with the kml so in kml schema this should look like
<gx:SoundCue>
  <href>files/Margaritaville.mp3</href>
</gx:SoundCue>
but I don't think there is gx:SoundCue tag in bonuspack

**Comment by MKergall** [comment]
No. Even more, there is no support at all for Tours. 
Have a close look here: https://github.com/MKergall/osmbonuspack/wiki/KML

Note that there is an Android version of Google Earth, which is pretty good. 
Can you explain your use case a little bit more?

**Comment by namanmehta1997** [comment]
In my case, I'm using osmdroid in offline mode. A user can share an image, a video, an audio or a text message to other users. Every media is associated with a geopoint and some explanation about the media like what it is or any other useful information. And at the end, I want to show all the received information on the map. So I am creating a kml file with respect to a geopoint and adding a media and finally packaging into kmz file. And the kmz file is transferred from one mobile to another mobile. So I need a link between the media and the kml file which is defined in the kml schema but not in the bonuspack

**Comment by MKergall** [comment]
I understand. 
gx:SoundCue is for tours - not really what you want to achieve. 
If you want to attach images/videos/text messages to a geopoint in KML, the regular method is to define a Placemark, and set its description with html tags including your  images/videos/text messages. 
Refer to "Sample Use of HTML Elements within a Description" in [KML reference](https://developers.google.com/kml/documentation/kmlreference#sample-use-of-html-elements-within-a-description). 

And you can do this using OSMBonusPack KML Placemark: set the description with proper (relative) href links, save the KML file, and then pack it with images/videos into KMZ file.

**Comment by namanmehta1997** [comment]
Yeah, I did that. Images are showing but videos and audio are not working.
I am using this description code for videos:
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>
But it instead of showing the video it is showing your browser does not support the video tag.
I am using google earth to plot to kmz and using the same type of reference in the image files also but images are showing but videos and audio are not playing
