### ISSUE TITLE
How to register a call back when user presses a feature

### ISSUE THREAD

**Issue by jenia** [MKergall/osmbonuspack#305]
Hello.

I need to be able to register a call back when the user has pressed on a Polygon for example.

How do I achieve that?

I noticed that when you press a feature on the map a tooltip appears. Is there no way to override that functionality with my logic?

**Comment by jenia** [comment]
I found that the popup logic is here: https://github.com/osmdroid/osmdroid/blob/0e63c3dd07fc9e43ba3c8b1ffb6c873d48515d2b/osmdroid-android/src/main/java/org/osmdroid/views/overlay/Polyline.java#L239
But my polylines and polygones are made by:

    kmlDocument.parseKMLUrl("...")

And it's not obvious for me how to override `OnClickListener` with my logic. Does anyone has any suggestions?

**Comment by MKergall** [comment]
Your polylines and polygons overlays are not made by
`kmlDocument.parseKMLUrl("...")
`
After this call, which is just building a KML structure, they are made by something like: 
`FolderOverlay kmlOverlay = (FolderOverlay)kmlDocument.mKmlRoot.buildOverlay(map, ...,  kmlDocument);
`

To customize the overlays, you will have to use: 
https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4#132-advanced-styling-with-the-styler

And then, inside your customized Styler, you will have to customize the default behaviour of those overlays for click handling.

**Comment by MKergall** [comment]
BTW, request for help should be done in StackOverflow.

**Comment by jenia** [comment]
MKergall, thanks for the tip but I don't need to style the feature. I need to capture the event when they are pressed. That's the problem: "How do I capture the event when a feature is pressed"?

**Comment by spyhunter99** [comment]
What I did was after converting from KML to a FolderOverlay, i recursively looped over the list looking for all polygons, then attached a click listener to each item

**Comment by namanmehta1997** [comment]
@spyhunter99 can you share a code snippet of how you added the click listener the polygon?
I need the exact same thing and I am currently building the overlay from the kmldocument.mKmlRoot.buildOverlay and then looking for polygons by folderoverlay.getItems() method
Now checking each item by instanceof keyword whether it is a polygon or not
If I find a polygon, I need to set some click event.
How to set a click listener to it?

**Comment by MKergall** [comment]
see https://stackoverflow.com/questions/32977376/how-to-get-ontap-in-polygon-in-osmdroid/33003302#33003302

**Comment by vincent-paing** [comment]
> @spyhunter99 can you share a code snippet of how you added the click listener the polygon?
> I need the exact same thing and I am currently building the overlay from the kmldocument.mKmlRoot.buildOverlay and then looking for polygons by folderoverlay.getItems() method
> Now checking each item by instanceof keyword whether it is a polygon or not
> If I find a polygon, I need to set some click event.
> How to set a click listener to it?

I would also like a example for this as well. I can't figure out how to add click event

**Comment by spyhunter99** [comment]
100% of the code i have is in the sample app. `Polygon.setOnClickListener(...)` is right. I think osm bonuspack has a styler class that can be used to adjust items as it's parsed from kml so you may be able to use that rather than parsing then walk the folderoverlay tree method.
