### ISSUE TITLE
id of the feature in the "onClick" callback not implemented?

### ISSUE THREAD

**Issue by jenia** [MKergall/osmbonuspack#306]
Hello.

Is the ID of the feature, loaded from GEOJson, not in the [callback](https://osmdroid.github.io/osmdroid/javadocAll/org/osmdroid/views/overlay/Polyline.OnClickListener.html) parameter object in `onClick`? I personally cannot find it.

If it's not I need to implement it. Please let me know one way or the other.

I see that in the function: `public boolean parseGeoJSON(JsonObject json){...`, the feature has the ID.

Thanks

**Comment by spyhunter99** [comment]
looks like it's missing the id field. I'll add it for osmdroid 6.0.0. @MKergall or perhaps if @jenia wants to write the changes for osmbonuspack

**Comment by jenia** [comment]
I can add it no problems. But I think I'll need to modify the file `KmlLineString` (among others) and set the id there. But as you noticed, that source code was made by the osmdroid project.

**Comment by spyhunter99** [comment]
well, technically, @MKergall wrote it all and somewhere around osmdroid 5.2 we agreed to migrate the base models for marker, line and polygon to the osmdroid repo, history included. The kml and geojson parsing, routing, icon clustering etc are still here.

**Comment by jenia** [comment]
@spyhunter99 Alright. Thanks for the info.

I'll try to set the ID for the next [release](https://github.com/osmdroid/osmdroid/milestone/9).
Right now I managed to avoid the problem by putting the ID into properties field :)
But it's not the best option at all.

**Comment by jenia** [comment]
@spyhunter99 I'd like to import the OSMBonusPack into my project as source code.

But I constantly get:

    Error:Unable to load class 
    'org.gradle.api.internal.artifacts.ImmutableModuleIdentifierFactory'.

Do you know how to fix this error?

Thanks

**Comment by spyhunter99** [comment]
uhh, no. revert that change?

**Comment by jenia** [comment]
@spyhunter99 Then I get another error:

    Error:Plugin with id 'com.github.dcendents.android-maven' not found.

**Comment by jenia** [comment]
I tried using 

plugins {
    id "com.github.dcendents.android-maven" version "2.0"
}

Now again I get:

    Error:Unable to load class 
    'org.gradle.api.internal.artifacts.ImmutableModuleIdentifierFactory'.

**Comment by MKergall** [comment]
When osmdroid 6.0 will be released, I can set this new id field in overlays (Marker, Polygon and Polyline) during buildOverlays, when the corresponding KML/GeoJson object has an id. 
That said, I don't really understand the need...
