### ISSUE TITLE
Failed to resolve: com.github.MKergall:osmbonuspack:6.4

### ISSUE THREAD

**Issue by Neofly4023** [MKergall/osmbonuspack#307]
![screenshot from 2017-10-27 21-01-38](https://user-images.githubusercontent.com/19911661/32122889-145abee2-bb5a-11e7-87c3-ec2fb97e27c3.png)

Hello guys , I don't know how to deal with this, I'm sorry if this isn't the right place to ask, but I can't find anyone with a similar error as mine

**Comment by mwshubham** [comment]
It shouldn't be closed like this. @Neofly4023 Please add the reference or tag for closure. That would be very helpful thanks.

**Comment by MKergall** [comment]
6.4 is obsolete now.
