### ISSUE TITLE
Does it support updates in Network link

### ISSUE THREAD

**Issue by namanmehta1997** [MKergall/osmbonuspack#311]
I am really interested to know whether bonuspack supports the update tag in network-link described in the link [https://developers.google.com/kml/documentation/updates?authuser=1](url)
If not can I make it to do so?

**Comment by MKergall** [comment]
Not supported. Read https://github.com/MKergall/osmbonuspack/wiki/KML#networklink
Far too complex. 

If you have a KML with evolving content, reload the KML root file.
