### ISSUE TITLE
Question:: Change cluster icon for different counts

### ISSUE THREAD

**Issue by mf-mindcrewtech** [MKergall/osmbonuspack#313]
Hi all,

How can we set the specific cluster icon for different sizes, like for <100 I want to use 1.png and for >100 and <1000 I want to use 2.png and so on. 

Any help really appreciate.

**Comment by MKergall** [comment]
Look at the [tutorials](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_3#112-advanced-customization), you will find everything you need.
