### ISSUE TITLE
Route with multiple wayponints

### ISSUE THREAD

**Issue by tmkhrg** [MKergall/osmbonuspack#317]
After doing the tutorial which draws a route between two locations, I would like to add a third one. My aim is to show the route from location A over to location B and then to location C. Location B is something like an additional stop on a road trip. I tried adding another GeoPoint to the waypoint array, but then it just draws a straight line from location A to location B and another straight line from location B to location C. Is there any possibility to solve my problem to show a calculated route from A over B to C?

**Comment by MKergall** [comment]
I just tried with the demo app (OsmNavigator): it works without any problem for OSRM, GraphHopper and Google services, with 1 and even 2 intermediate waypoints. 

Which roadmanager are you trying to use?

**Comment by tmkhrg** [comment]
Got it to work by putting the route calculation into an extra thread. The problem is now, that the route will only show up after I move the map a bit. I tried using map.invalidate() inside the thread, but that makes my app crash. Is there any other way to make the route draw instantly?

**Comment by MKergall** [comment]
map.invalidate, as any UI action, must be done in the onPostExecute of your AsyncTask. 
Look at OSMNavigator app source code (MapActivity, getRoadAsync method), it does exactly what you want to achieve.

**Comment by tmkhrg** [comment]
I will take a look at that. Thank you very much!
