### ISSUE TITLE
Spaces between lines in Polyline

### ISSUE THREAD

**Issue by XMouse007** [MKergall/osmbonuspack#318]
I'm trying to draw a track on the map by Polyline but on the sharp corners apper spaces

[https://i.stack.imgur.com/mkGyr.jpg](https://i.stack.imgur.com/mkGyr.jpg)

```
String points [] = routeModel.getLatlon().split("\\|");
String [] point;
ArrayList<GeoPoint> mTrace = new ArrayList<>();

for (String s : points) {
    point = s.split("-");
    GeoPoint gg = new 
    GeoPoint(Double.parseDouble(point[0]),Double.parseDouble(point[1]));
    mTrace.add(gg);
}

Polyline mPolyline  = new Polyline();
mPolyline.setColor(getResources().getColor(R.color.bonusColor));
mPolyline.setWidth(14.0f);
mPolyline.setPoints(mTrace);

mapView.getOverlays().add(polyline);
```

**Comment by MKergall** [comment]
Polyline has been moved in osmdroid => post this issue in osmdroid project. 

(BTW, suggested optimization: 
ArrayList<GeoPoint> mTrace = new ArrayList<>(points.length);
)

**Comment by spyhunter99** [comment]
@XMouse007 try reducing the draw width. For what it's worth, @monsieurtanuki did find a way to fix the issue you're referring to, however it was a significant performance impact and the change was rolled back

**Comment by monsieurtanuki** [comment]
@spyhunter99 Thinking again about it, I guess we could give the users the possibility to display `Polyline`s as `Path` (no sharp angle) instead of lines (best performances), as an option.

**Comment by XMouse007** [comment]
I found a solution and it's so simple =)

> mPolyline.getPaint().setStrokeJoin(Paint.Join.ROUND)
> mPolyline.getPaint().setStrokeCap(Paint.Cap.ROUND)

P.s. sorry for discussing of the problem in this thread

**Comment by spyhunter99** [comment]
Nice find, i may set that as the default
