### ISSUE TITLE
Errors in osmbonuspack demo project in Android Studio

### ISSUE THREAD

**Issue by mcastillo86** [MKergall/osmbonuspack#321]
Hello,

I have the following errors when building osmbonuspack in Android Studio:

Information:Gradle tasks [:OSMNavigator:assembleDebug, :OSMBonusPackTuto:assembleDebug]
F:\Work\osmbonuspack\OSMBonusPack\src\main\java\org\osmdroid\bonuspack\clustering\RadiusMarkerClusterer.java
Error:(106, 43) error: cannot find symbol method distanceTo(GeoPoint)
F:\Work\osmbonuspack\OSMBonusPack\src\main\java\org\osmdroid\bonuspack\kml\KmlPlacemark.java
Error:(62, 84) error: incompatible types: List<List<GeoPoint>> cannot be converted to ArrayList<ArrayList<GeoPoint>>
F:\Work\osmbonuspack\OSMBonusPack\src\main\java\org\osmdroid\bonuspack\kml\KmlGroundOverlay.java
Error:(114, 19) error: cannot find symbol method distanceTo(GeoPoint)
Error:(116, 20) error: cannot find symbol method distanceTo(GeoPoint)
Error:Execution failed for task ':OSMBonusPack:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

I did this changes so far 

main build.gradle file:
From: classpath 'com.android.tools.build:gradle:2.3.3'
to: classpath 'com.android.tools.build:gradle:3.0.1'

osmbonuspack build.graddle file:

from:    
    compile "com.android.support:support-v4:23.2.1"
    compile 'org.osmdroid:osmdroid-android:5.6.5'
    compile 'org.apache.commons:commons-lang3:3.3.2'
    compile 'com.google.code.gson:gson:2.7'
    compile 'com.squareup.okhttp3:okhttp:3.4.1'
to:
    compile "com.android.support:support-v4:23.4.0"
    compile 'org.osmdroid:osmdroid-android:6.0.1'
    compile 'org.apache.commons:commons-lang3:3.3.2'
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'com.squareup.okhttp3:okhttp:3.7.0'

**Comment by MKergall** [comment]
Yes, I forgot to push some commits in release 6.5. 
Should be fixed in release 6.5.1. Can you check, and close if OK?
