### ISSUE TITLE
 error: package com.google.android.maps does not exist

### ISSUE THREAD

**Issue by mickeycams** [MKergall/osmbonuspack#322]
What do i do??
Its troubling me a lot. Working on it for a long time. Didn't know what to do.

**Comment by spyhunter99** [comment]
What dependencies does your project have? Probably missing the Google api stuff from the android sdk manager

**Comment by mickeycams** [comment]
Error

**Comment by spyhunter99** [comment]
what is your goal? is this your first app? osmbonuspack does not use google maps. If you're new to android studio, most of the build in templates are not that great. Try starting from a empty activity. If you select a google map activity, you'll need to install all the google specific parts of the android sdk, using the sdk manager and that would probably cause your problem. In either case, to use osmbonuspack, you don't need any of that nonsense

**Comment by mickeycams** [comment]
I m doing project on pothole so I wanna edit maps thats possible on osm

**Comment by MKergall** [comment]
Nothing to do with OSMBonusPack. 
Please post such request for support in StackOverflow.
