### ISSUE TITLE
Route Distance

### ISSUE THREAD

**Issue by FisnikIbishi** [MKergall/osmbonuspack#323]
RoadManager does not return route length of long distances only short.
I am trying to get the length like the code below:

val roadManager = OSRMRoadManager(this)
val road: Road = roadManager.getRoad(waypoints)
var routeLength = road.mLength 

Variable waypoints is an ArrayList of GeoPoint

**Comment by MKergall** [comment]
Road.mLength is a double. 
Don't understand your issue. Provide a sample.

**Comment by FisnikIbishi** [comment]
Normally Road.mLength should return the whole route in km but it returns the correct value only for short distances.
If the route is lets say above 10 km it returns 0.0 km

**Comment by MKergall** [comment]
I just tried Nantes-Munchen with Osrm: 1300 km. Works like a charm.

**Comment by MKergall** [comment]
var routeLength = road.mLength 
is not a valid piece of code. Provide your actual code sample.
