### ISSUE TITLE
OSMBonusPack KMLDocument and Android 4.x

### ISSUE THREAD

**Issue by moonmanngr** [MKergall/osmbonuspack#325]
I'm using osmdroid 5.6.5 + osmbonuspack 6.4 to process a KML file and show the objects over a map. All this works fine on Android 5.x+ but fails on Android 4.x:

The code KmlDocument kmlDocument = new KmlDocument(); returns the error "java.lang.VerifyError: "

Anyone can help me to solve this?

Best regards,

NR.

**Comment by MKergall** [comment]
Maybe this: https://stackoverflow.com/a/5184091/3151518 ?

**Comment by moonmanngr** [comment]
Source of the problem: gson dependency missed on build.gradle.

Solution: add the following line on build.gradle:

implementation 'com.google.code.gson:gson:2.8.0'

**Comment by MKergall** [comment]
Normally, just defining: 

`compile 'com.github.MKergall:osmbonuspack:6.5.1'`

in your build.gradle dependencies is supposed to get all required dependencies, including gson (and even osmdroid). It was not sufficient?

**Comment by moonmanngr** [comment]
I'm importing osmbonuspack from a local lib because I have incompatibility of the last osmdroid (6.x) and other libraries that I use.

**Comment by MKergall** [comment]
OK. Effectively, in this case you need to add [all dependencies](https://github.com/MKergall/osmbonuspack/wiki/HowToInclude#2-including-as-a-local-lib).
