### ISSUE TITLE
Geonames service problem

### ISSUE THREAD

**Issue by mlendl** [MKergall/osmbonuspack#326]
The Geonames service provided by Osmbonuspack stopped giving mDescription recently, although it seems, that the web service returns something. Maybe an API change. Pls, take a look at it

**Comment by MKergall** [comment]
I tried using OSMNavigator (searching Feature="wikipedia"), which is based on GeoNamesPOIProvider.getPOIInside method. It works fine, description is set to Wikipedia summary. 

Which GeoNamesPOIProvider method are you using exactly?

**Comment by mlendl** [comment]
I use the code exactly according to Tutorial:

GeoNamesPOIProvider poiProvider = new
GeoNamesPOIProvider("YOUR_GEONAMES_ACCOUNT");ArrayList<POI> pois =
poiProvider.getPOIInside(map.getBoundingBox(), 30);


I get POI where poi.mType and poi.mUrl is OK, but poi.mDescription is
always empty

**Comment by mlendl** [comment]
Problem is on the side of WikiPedia, it returns empty summary element
