### ISSUE TITLE
Custom icon and clustering

### ISSUE THREAD

**Issue by captainepoch** [MKergall/osmbonuspack#327]
Hi there!

I set up a custom marker icon for points in the map, but when I do the clustering to group them, they appear with the default icon.

Those points were set up with `OverlayItem` and a `Drawable`. Then, the `GeoPoint` was added to another array so I can do a `Polyline`.

I attach a screenshot.

![](https://i.imgur.com/qSDj2xi.png)

**Comment by MKergall** [comment]
Clustering is available for Markers only. Neither for OverlayItems nor for Polylines.

**Comment by captainepoch** [comment]
Is it possible to customize the green marker?

**Comment by MKergall** [comment]
Of course. Follow the [tutorials](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_0).

**Comment by captainepoch** [comment]
Thank you, that worked perfectly 🙂

Another thing, and I stop. As you can see in the screenshot, there's a few singular points with the green marker. If I zoom out, the green marker disappears. Is it because of the clustering? And is there any way to put the marker even with a little zoom? 

Thank you again, @MKergall 🙂

**Comment by MKergall** [comment]
If those green markers are inside the MarkerClusterer, it's normal that they disapear when you zoom out: they are "clustered". 
If you don't want them to be clustered, don't put them in the MarkerClusterer.
