### ISSUE TITLE
How to use onLongPress on a Marker?

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [MKergall/osmbonuspack#328]
I am using osmdroid in a project. If I understood correctly, then osmdroid's Marker comes from osmbonuspack. On reading the documentation (javadocs) I came across a method on Marker called Marker.onLongPress (MotionEvent event, MapView view) method.

The default behaviour seems to return false. I am trying to delete a marker on long pressing the same. I hope this method's signature is synonymous with what I was looking for. But it lacks usage examples.

**Comment by MKergall** [comment]
Please ask for advice/help on StackOverflow, not as project issues.
