### ISSUE TITLE
issue with an integrate to my  app

### ISSUE THREAD

**Issue by sajith18** [MKergall/osmbonuspack#330]
list of include ':OSMBonusPack', ':OSMBonusPackTuto', ':OSMNavigator'
how to  put a button and run this full project in my app , and which layout or activity want to call?

**Comment by MKergall** [comment]
Requests for help/advice: on StackOverflow, please 
(OSMBonusPack is a lib, OSMBonusPack tuto is a tuto app, and OSMNavigator is a full-featured app - so answer to your question depends on what you want to achieve exactly)
