### ISSUE TITLE
Feature ID is not saved in KML file

### ISSUE THREAD

**Issue by namanmehta1997** [MKergall/osmbonuspack#331]
Setting an ID to a Polygon or Marker and then saving through `KmlDocument.saveAsKML()` method, the ID field just vanishes. No ID is saved in the KML file.

**Comment by MKergall** [comment]
You cannot save a Polygon or Marker with KmlDocument.saveAsKML(), but a KmlPlacemark (which can be a KmlPoint or KmlPolygon). 
Please explain your use case a little bit more.

**Comment by namanmehta1997** [comment]
I use marker object as : 
`KmlDocument kml = new KmlDocument();
Marker marker = new Marker(map);
 marker.setPosition(polygon_points.get(0));
 marker.setId(uniqueId);
 KmlPlacemark kmlPlacemark = new KmlPlacemark(marker);
 kml.mKmlRoot.add(kmlPlacemark);`
and Polygon object as : 
`polygon.setPoints(polygon_points);
 polygon.setId(uniqueId);
 kml.mKmlRoot.addOverlay(polygon,kml);`
and then finally save this using 
`kml.saveAsKML()`
But no id field is there when I open the saved KML file.

**Comment by MKergall** [comment]
OK, understood. Fix just pushed.

**Comment by namanmehta1997** [comment]
How much time should I expect for the next release?
And closing it since you have done it !!!

**Comment by MKergall** [comment]
I try to follow osmdroid releases, except if I introduce a major change or major fix. 
In the meantime, you can build the lib yourself from the head.
