### ISSUE TITLE
Mapzen shutdown: impact on class GeocoderMapzen

### ISSUE THREAD

**Issue by monsieurtanuki** [MKergall/osmbonuspack#335]
Mapzen is [shutting down](https://mapzen.com/blog/shutdown/) and provides a list of [alternate solutions](https://mapzen.com/blog/migration/) for geocoding:
* [geocode.earth](https://geocode.earth/)
* [Nominatim](http://nominatim.openstreetmap.org/) [already implemented in `osmbonuspack` as `GeocoderNominatim`]
* [OpenCage Data](https://geocoder.opencagedata.com/)
* [OSMNames](https://osmnames.org/)
* [Mapbox Search API](https://www.mapbox.com/geocoding/)

`GeocoderMapzen` should be at least `deprecated`, even removed.
Which of the alternate solutions are worth implementing?

**Comment by MKergall** [comment]
Removed. 
By the way, Nominatim made good progress and is a good fallback solution.
