### ISSUE TITLE
marker info window dont show after clustering markers

### ISSUE THREAD

**Issue by edalatfeizi** [MKergall/osmbonuspack#336]
I'm using osmdroid to display open street map in an android app the problem is when clustering markers when click on marker, info window of markers do not shows. this is how i add markers for clustering:

`RadiusMarkerClusterer poiMarkers = new RadiusMarkerClusterer(this);
     Drawable clusterIconD = getResources().getDrawable(R.drawable.marker_cluster);
     Bitmap clusterIcon = ((BitmapDrawable) clusterIconD).getBitmap();
     poiMarkers.setIcon(clusterIcon);
     poiMarkers.getTextPaint().setColor(Color.WHITE);
     poiMarkers.getTextPaint().setTextSize(12 * getResources().getDisplayMetrics().density);
     poiMarkers.mAnchorU = Marker.ANCHOR_CENTER;
     poiMarkers.mAnchorV = Marker.ANCHOR_CENTER;
     poiMarkers.mTextAnchorV = 0.40f;
     map.getOverlays().add(poiMarkers);

    for (int i = 0; i < places.size(); i++) {
        final Marker startMarker = new Marker(map);
        startMarker.setPosition(new GeoPoint(places.get(i).getLat(), places.get(i).getLng()));

        startMarker.setIcon(getResources().getDrawable(R.drawable.ic_new_loc));

        startMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_CENTER);
        MyInfoWindow infoWindow = new MyInfoWindow(R.layout.map_marker_info_window, map);
        infoWindow.setPlace(places.get(i));
        startMarker.setInfoWindow(infoWindow);
        poiMarkers.add(startMarker);
    }`

**Comment by MKergall** [comment]
As there are many markers "inside" a single cluster marker, when a cluster marker is tapped, what should should be shown in the infowindow? 
There is no generic solution to that question. 

If you have a solution in your particular use case, what you can do is sub-class the RadiusMarkerClusterer, redefine buildClusterMarker method, and set the infowindow you want.

**Comment by MKergall** [comment]
Cf. similar explanation by Josef Adamcik [here](https://stackoverflow.com/questions/50317047/osmdroid-marker-info-window-dont-show-after-clustering-markers/50319025#50319025)
