### ISSUE TITLE
Load Speed

### ISSUE THREAD

**Issue by Canoir** [MKergall/osmbonuspack#340]
how can i make my map load faster in move? 
many thanks.

**Comment by MKergall** [comment]
What do you mean ???

**Comment by Canoir** [comment]
load of map. the time that take to can see the full map on that zoom. for example : 
for me takes 8 second to show my place correctlly . i need to take down this time to around 2 second.
thanks.

**Comment by MKergall** [comment]
This is related to osmdroid => question to ask in osmdroid, not in OSMBonusPack. 

And you will have to provide much more details: device used, SDK, type and speed of Internet connexion, which tile source, online or offline, which application (yours, or a demo app) ...
