### ISSUE TITLE
Polygon Event Listeners

### ISSUE THREAD

**Issue by jcpatac** [MKergall/osmbonuspack#341]
So I just rendered my kml data and I want to go to another activity if one of the polygons is clicked. Basically, I want to attach a listener to every polygons in there, but I'm having problems doing it. Any insights on this?

**Comment by jcpatac** [comment]
I think I found a way. It's not the most efficient though. Another problem now is how do I get the ID (f_id) on every feature. Any comments? Thanks!

**Comment by MKergall** [comment]
KML id of a feature is myFeature.mId

Accessing this id in the overlay has been addressed in issue #306. Not in a release yet, use the master branch to have the fix.

**Comment by jcpatac** [comment]
Hello thanks for responding! I'm new to developing mobile apps so I'm having a hard time doing what you said because I imported it as a library (.jar). Any comments? Thanks!

**Comment by MKergall** [comment]
now released.
