### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by smkazemi** [MKergall/osmbonuspack#342]
Hi , i add `compile 'com.github.MKergall:osmbonuspack:6.5.1'` to gradle file and when build project in tab message shows :
 
>Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

also using google map : 
```
  implementation 'com.google.android.gms:play-services-location:15.0.1'
    implementation 'com.google.android.gms:play-services-maps:15.0.1'
```

**Comment by MKergall** [comment]
1) https://stackoverflow.com/questions/46267621/unable-to-merge-dex

2) or start from something working: the tutorial project.
