### ISSUE TITLE
Android 9 (API level 28) compatibility issues

### ISSUE THREAD

**Issue by brobe100** [MKergall/osmbonuspack#343]
If you set your `targetSdkVersion` to `28`, a couple of issues may occur.

If you update `com.android.support:appcompat-v7` to `com.android.support:appcompat-v7:28.0.0-rc01`, or update any of the `com.android.support` packages to API 28, you may get a `:app:transformDexArchiveWithExternalLibsDexMergerForDebug` error when building. This can occur because osmbonuspack is including a version of the com.android.support library that is not compatible with `com.android.support:appcompat-v7:28.0.0-rc01`, or any of the API 28 `com.android.support` libraries.  To fix this issue, add `implementation 'com.android.support:support-v4:28.0.0-rc01'` to your dependencies.

The other issue is that API 28, by default, does not allow clear traffic text with HTTP request. This will cause osmbonuspack to fail to retrieve data when it makes a HTTP request. To enable clear traffic text, declare `android:usesCleartextTraffic=”true”` attribute on the application element in your app’s AndroidManifest.xml. See [https://android-developers.googleblog.com/2016/04/protecting-against-unintentional.html](https://android-developers.googleblog.com/2016/04/protecting-against-unintentional.html).

**Comment by MKergall** [comment]
6.5.3 (now released) removes dependency with support-v4. 
This should solve your issue.
