### ISSUE TITLE
Android SDK 27 issue

### ISSUE THREAD

**Issue by anta40** [MKergall/osmbonuspack#344]
This is the content of my app's build.gradle:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "app.anta40.com.osmdemo"
        minSdkVersion 14
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.github.MKergall:osmbonuspack:6.5.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

I'm using Android Studio 3.1.4, and it complains that "All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 23.4.0. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:support-v4:23.4.0 more..."

Anyway, this is [my code](https://github.com/anta40/OSMDemo), which is esentially taken from [Tutorial 0](https://github.com/MKergall/osmbonuspack/wiki/Tutorial_0). Android Studio gives this compile error message:

> Program type already present: android.support.v4.app.ActionBarDrawerToggle$SlideDrawable

**Comment by MKergall** [comment]
OSMBonusPack 6.5.2 uses "com.android.support:support-v4:23.4.0". 
I imagine this is conflicting with 'com.android.support:appcompat-v7:27.1.1'. 

https://developer.android.com/topic/libraries/support-library/packages claims that v7 appcompat library depends on the v4 Support Library... The conflict is probably in sub-versions numbers. 

Can you get rid of this appcompat-v7 dependency in your app? 

If not, what you can do is download OSMBonusPack project as a lib in your own workspace, update its version of support-v4 to solve the conflict, and recompile.

**Comment by brobe100** [comment]
This is probably the same as issue https://github.com/MKergall/osmbonuspack/issues/343.

Try adding `implementation 'com.android.support:support-v4:support-27.1.1'` to your gradle file.

So your dependencies in your gradle file should be the following:
```
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:support-27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.github.MKergall:osmbonuspack:6.5.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

**Comment by monsieurtanuki** [comment]
I've just had a similar issue:
`  Program type already present: android.support.v4.app.FragmentTransitionCompat21$1`

I've found a solution in [SO](https://stackoverflow.com/questions/49837344/program-type-already-present-android-support-v4-app-backstackrecord#49837806) (at least in my case, it works):
````
implementation ('com.github.MKergall:osmbonuspack:6.5.2'){
	exclude group: 'com.android.support'
	exclude module: 'appcompat-v7'
	exclude module: 'support-v4'
}
````
Disclaimer: I don't understand anything about `gradle`, and I intend to keep it that way.

**Comment by MKergall** [comment]
6.5.3 (now released) removes dependency with support-v4. 
This should solve your issue.
