### ISSUE TITLE
Cluster Click listener

### ISSUE THREAD

**Issue by amirhh97** [MKergall/osmbonuspack#345]
Hi
im using your library how i can set click listner on RadiusMarkerCluster
Thanks for your answer

**Comment by MKergall** [comment]
It doesn't make sense, as a RadiusMarkerClusterer class is a container of Markers, not something you can touch. 

What you can easily do is set a click listener to the various Markers you put in the RadiusMarkerClusterer. 

If you also want to set a click listener on the markers used as "clusters of markers", you have to inherit from RadiusMarkerClusterer, and implement your own buildClusterMarker method (where this marker is built).
