### ISSUE TITLE
Polyline PathDashPathEffect problem at upgrade from 6.4 to 6.5.2

### ISSUE THREAD

**Issue by kichnamid** [MKergall/osmbonuspack#346]
Hello!
My prohect has a polyline with pathdashpatheffect. Everything was working fine: a polyline with arrow-shaped stamp. But after upgrading repositorie to 6.5.2, the polyline became just a thick stroke. No spaces or resemblense of my shape, only black paint.
Here is some code:
`Paint osmOtrPaintV = new Paint(Paint.ANTI_ALIAS_FLAG);
osmOtrPaintV.setColor(Color.BLACK);
osmOtrPaintV.setStyle(Paint.Style.STROKE);
osmOtrPaintV.setStrokeWidth((int)(11*sFactor));
osmOtrPaintV.setPathEffect(new PathDashPathEffect(vshape, 35, 5, PathDashPathEffect.Style.ROTATE));
...
Polyline osmOtrezokV = new Polyline(context);
osmOtrezokV.getPaint().set(osmOtrPaintV);
....
osmOtrezokV.setPoints(osmBG_V);
`

**Comment by MKergall** [comment]
To submit in osmdroid project, as Polyline has been moved there.
