### ISSUE TITLE
Add Custom Control as Marker

### ISSUE THREAD

**Issue by nadjibnet** [MKergall/osmbonuspack#349]
Hi,
Please how can I add Custom Control as Marker to OSMBONUSPACK ?

I create some Buttons and image in Android xml file

Named MyMarkerItem.xml

And I would like something like MyMarker.setDesign(R.layout.MyMarkerItem);

Thanks

**Comment by MKergall** [comment]
Explained in the Wiki. 
Please, questions for support on StackOverflow only.
