### ISSUE TITLE
Question regarding your LGPL license exception

### ISSUE THREAD

**Issue by sgustafsson** [MKergall/osmbonuspack#352]
Your license exception says:

> The constraints described in Section 5.d and 5.e of the LGPL LICENCE are DISCARDED.

As there are no section 5.d and 5.e in the LGPL v3 license, but section 4.d and 4.e exist, am I right in assuming your exception refers to sections 4.d and 4.e?

**Comment by MKergall** [comment]
That's right! 
Fixed now.
