### ISSUE TITLE
Get elevation from XML using GetPOICloseTo method

### ISSUE THREAD

**Issue by Bastgabr** [MKergall/osmbonuspack#353]
Is it possible to update the pack to be able to get the elevation from the XML using GetPOICloseTo (GeoNames Provider). The problem is that the data coming from the XML file are catsted into a POI object. 

Is it possible for you to fix that ?

Thank you in advance !

**Comment by MKergall** [comment]
Effectively, seems pretty simple to fix and set in the POI object, as GeoNames provides elevation. 
But do you known what is the unit/reference of elevation returned by GeoNames? Not found in their doc.

**Comment by Bastgabr** [comment]
The unit of elevation returned by GeoNames is meter. 
Thanks for your answer
