### ISSUE TITLE
osmdroid says you have CacheManager. Does it support download by countries?

### ISSUE THREAD

**Issue by anonym24** [MKergall/osmbonuspack#355]
osmdroid says you have CacheManager. Does it support download by countries?

![image](https://user-images.githubusercontent.com/8851301/49861627-f21b4d80-fe04-11e8-8f37-ee05983dd4cb.png)

(https://github.com/osmdroid/osmdroid/wiki/Offline-Map-Tiles)

Can it do something like this?

(20 km vs 200 km)

![z1](https://user-images.githubusercontent.com/8851301/49853324-71058b80-fdef-11e8-8688-64e37be51baf.jpg) ![z2](https://user-images.githubusercontent.com/8851301/49853332-7531a900-fdef-11e8-8ae1-5e73a517e788.jpg)

**Comment by MKergall** [comment]
1) The wiki is wrong: CacheManager has been moved in osmdroid. 
2) For a country-wide offline map, bitmap tiles will take too much space. But you can use the [MapsForge adapter](https://github.com/osmdroid/osmdroid/wiki/Mapsforge).

**Comment by spyhunter99** [comment]
2nd that. CacheManager can download a region by a bounding box and zoom levels or by a specific route + zoom levels.

**Comment by spyhunter99** [comment]
also not idea where @anonym24 got that screen grab from. I don't see if anywhere in the osmdroid wiki

**Comment by MKergall** [comment]
because I fixed the wiki... :-)
