### ISSUE TITLE
Integration of Open Route Service with BonusPack

### ISSUE THREAD

**Issue by arbhardwaj98** [MKergall/osmbonuspack#356]
I wanted to test Open Route Service(ORS) for my navigation app, instead of OSRM which I have been using for quite some time. I wanted to know if it was possible to use the BonusPack for fetching data from Open Route Service by doing some minor changes in the API. Also is the data provided by OSM and OSRM same?

**Comment by MKergall** [comment]
Apparently, ORS Directions is a fork from GraphHopper. You could try using the GraphHopperRoadManager, it could work as is (use setService method to target the ORS server). 

If it doesn't work as is: we will need the ORS Directions API doc to see needed changes. 
I found numerous details about all possible request options, but I've not been able to find any doc about the JSON response yet.

**Comment by MKergall** [comment]
ping
