### ISSUE TITLE
KmlDocument ParseGeojson Not Working With Multipolygon

### ISSUE THREAD

**Issue by khnoize** [MKergall/osmbonuspack#357]
Hello.

I've tried to use KmlDocument to parse geojson this way (from a link in medium):

                    KmlDocument kmlDocument = new KmlDocument();
                    kmlDocument.parseGeoJSON(stringGeoJson);

                    Drawable defaultMarker = getResources().getDrawable(R.drawable.marker_default);

                    Bitmap defaultBitmap = ((BitmapDrawable) defaultMarker).getBitmap();

                    Style defaultStyle = new Style(defaultBitmap,
                            Color.argb(0, 0,0,0),
                            5f,
                            Color.argb(75, 255,0,0));

                    FolderOverlay geoJsonOverlay =
                            (FolderOverlay) kmlDocument.mKmlRoot.buildOverlay(
                                    mv, defaultStyle, null, kmlDocument);

                    mv.getOverlays().add(geoJsonOverlay);
                    mv.invalidate();

And it works wonderfully. However, when I was trying to parse a geojson url with type "multipolygon" instead of "polygon", it won't work. No errors or anything, it's just won't show the polygon.

Is there anything I can do to make it work? Thank you.

**Comment by MKergall** [comment]
MultiPolygon is not supported currently. 
Refer to https://github.com/MKergall/osmbonuspack/wiki/GeoJSON for supported GeoJSON types. 

Franckly, with GeometryCollection type available, I don't understand why GeoJSON spec added all those "multi" types, that's a pain to handle. 
But we can implement it (as done for MultiPoint), if needed.

**Comment by khnoize** [comment]
Oh, okay. Would be great for multi polygon users if later versions can handle that.

**Comment by MKergall** [comment]
Not tested yet. Give this commit a try.

**Comment by MKergall** [comment]
included in v6.6.0, now published.
