### ISSUE TITLE
How to smooth update the RadiusMarkerClusterer

### ISSUE THREAD

**Issue by xyz32** [MKergall/osmbonuspack#358]
I have a RadiusMarkerClusterer that is update by a OverpassAPI call whenever the map is scrolled.
The http request and the parsing of the data are all done in a thread, including the call to the invalidate method.
When the map gets update it gets unresponsive to user imputes and the console outputs:
```Skipped 55 frames!  The application may be doing too much work on its main thread.```

Is there a best practice on how to update the Markers smoothly?

Thanks.

**Comment by MKergall** [comment]
Request for advice => ask on StackOverflow. 

(if you call OverpassAPI at every map scroll event, it's obvious you will have a performance issue)

**Comment by xyz32** [comment]
I am not asking for advice, I am reporting a weird performance issue I am having.
The data is all local (I download it from OverpassAPI at app install time).
The update of the cluster is done inside a separate thread (not the UI thread) and I do use a semaphore to only run one update at the time.
The message happens after I call the update method from the library (so out of my control).

Anyway thanks for the answer.
