### ISSUE TITLE
org.json.JSONException: No value for exit

### ISSUE THREAD

**Issue by Kigstom** [MKergall/osmbonuspack#360]
Good morning, I found that while trying to retrieve the road from a start GeoPoint and an end GeoPoint, the response json falls into 'JSONException' when trie to retrieve the value of a key that doesn't exit.

I show below the problem that i get:
![Screenshot 2019-03-21 at 11 07 03](https://user-images.githubusercontent.com/45695568/54748434-8d248000-4bc9-11e9-9bce-08efd6c69762.png)

For my understanding the problem is when the manager tries to parse a value from a key that doesn't exits, my questions are:
     -> The json must has that set of key-value?;
     -> If the above is false, can we check if the keys exits first and then retrieve its possible value?.

Thank you for your time and patience.
Best regards from DCS.

**Comment by MKergall** [comment]
Could you please copy/paste the value of the "url" variable as text? I will then try and see what happens.

**Comment by Kigstom** [comment]
> Could you please copy/paste the value of the "url" variable as text? I will then try and see what happens.

Good afternoon,
if I'm not wrong you it must be the response of that url request, correct?

Here is a Json file of what i get:
[data.txt](https://github.com/MKergall/osmbonuspack/files/2996896/data.txt)

**Comment by MKergall** [comment]
assume obsolete
