### ISSUE TITLE
Problem download map

### ISSUE THREAD

**Issue by augustopeterle** [MKergall/osmbonuspack#361]
Hi, I'm new in Android development. I started a new project using OSM. So, I wrote this following code to draw the map in my Main Activity layout.

` @Override

 protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        MapView mapa = (MapView) findViewById(R.id.mapaId);
        mapa.setTileSource(TileSourceFactory.MAPNIK);
        GeoPoint pontoInicial = new GeoPoint(-22.9090153, -43.1722342);
        IMapController mapController = mapa.getController();

        mapController.setCenter(pontoInicial);
        mapController.animateTo(pontoInicial);
        mapa.setVisibility(View.VISIBLE);
        mapa.setZoomRounding(true);
        mapa.setMultiTouchControls(true);

        Marker startMarker = new Marker(mapa);
        startMarker.setPosition(pontoInicial);
        startMarker.setTitle("Ponto Inicial");

        mapa.invalidate();
        startMarker.setAnchor(Marker.ANCHOR_CENTER, Marker.ANCHOR_BOTTOM);
        mapa.getOverlays().add(startMarker);
        mapa.invalidate();

    }` 

I tried to open the app and the box of the map exits but the map doesn't is showed. I received this error in Android Studio Logcat:

`03-26 15:18:43.642 23895-23895/com.vale.myapplication D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN

03-26 15:18:47.165 23895-23957/com.vale.myapplication I/System.out: (HTTPLog)-Static: isSBSettingEnabled false

03-26 15:18:47.285 23895-23957/com.vale.myapplication W/OsmDroid: Problem downloading MapTile: /0/0/0 HTTP response: Forbidden

03-26 15:18:47.425 23895-24036/com.vale.myapplication I/System.out: (HTTPLog)-Static: isSBSettingEnabled false

03-26 15:18:47.515 23895-24036/com.vale.myapplication W/OsmDroid: Problem downloading MapTile: /0/0/0 HTTP response: Forbidden

03-26 15:18:47.656 23895-23957/com.vale.myapplication I/System.out: (HTTPLog)-Static: isSBSettingEnabled false

03-26 15:18:47.746 23895-23957/com.vale.myapplication W/OsmDroid: Problem downloading MapTile: /0/0/0 HTTP response: Forbidden`

**Comment by spyhunter99** [comment]
you need to set the user agent. See the osmdroid wiki
