### ISSUE TITLE
I'm creating an app to store notes in different coordinates, I need to add a note note in the clicked place on the map, how do I do this?

### ISSUE THREAD

**Issue by josileudo** [MKergall/osmbonuspack#362]
quero indicar um\ nota no mapa, porém não sei como fazer isso

**Comment by MKergall** [comment]
english required.

**Comment by josileudo** [comment]
I'm creating an app to store notes in different coordinates, I need to add a note note in the clicked place on the map, how do I do this?

**Comment by MKergall** [comment]
Requests for help: ask on StackOverflow.
