### ISSUE TITLE
OnClick Cluster. Zoom in while cluster not opens

### ISSUE THREAD

**Issue by Dimitry82** [MKergall/osmbonuspack#368]
Hello))

Please answer me how can i zoom in map while cluster not expand on click on this cluster?

Russian:
Подскажите, пожалуйста, как мне сделать увеличение масштаба карты пока не развернётся кластер по клику на него?

**Comment by MKergall** [comment]
Sorry, I didn't understood the question.

**Comment by Dimitry82** [comment]
Well, I will try to describe in detail. Suppose we are looking at a map with 10 zoom and we have a cluster containing 3 markers. With a zoom of 11, we also have a cluster containing 3 markers. But with a zoom of 12, we already have 1 cluster containing 2 markers and one detached marker. Now the question is, how can I make it so that when you click on a cluster in the 10th zoom card, the map will approach up to 12th zoom, that is, the map will understand that the cluster containing 3 markers is falling apart.

**Comment by MKergall** [comment]
What you could easily do: 
Start by sub-classing the RadiusMarkerClusterer, and override onSingleTapConfirmed. 
On single tap: 
- Search if a cluster of the clusterer has been tapped. 
- If yes, zoom on the boundingbox enclosing all the markers of this cluster. 

Not exactly the behaviour you describe, but quite close.

**Comment by Dimitry82** [comment]
Ok, i'll try it. Thank you))

**Comment by Dimitry82** [comment]
Here is my solution:

`    @Override
    public Marker buildClusterMarker(final StaticCluster cluster, MapView mapView) {
        Marker m = new Marker(mapView);

//(configure marker...)

        m.setOnMarkerClickListener(new Marker.OnMarkerClickListener() {
            @Override
            public boolean onMarkerClick(Marker marker, MapView mapView) {
                double latMax = cluster.getItem(0).getPosition().getLatitude();
                double latMin = cluster.getItem(0).getPosition().getLatitude();
                double longMax = cluster.getItem(0).getPosition().getLongitude();
                double longMin = cluster.getItem(0).getPosition().getLongitude();

                for (int i = 1; i < cluster.getSize(); i++) {
                    latMax = Math.max(latMax, cluster.getItem(i).getPosition().getLatitude());
                    latMin = Math.min(latMin, cluster.getItem(i).getPosition().getLatitude());
                    longMax = Math.max(longMax, cluster.getItem(i).getPosition().getLongitude());
                    longMin = Math.max(longMin, cluster.getItem(i).getPosition().getLongitude());
                }

//encreasing boundingbox by 10%
                double z = 0.1;
                double deltaLat = Math.abs(Math.abs(latMax) - Math.abs(latMin))*z;
                double deltaLong = Math.abs(Math.abs(longMax) - Math.abs(longMin))*z;

                mapView.zoomToBoundingBox(
                        new BoundingBox(
                        latMax + deltaLat,
                        longMax + deltaLong,
                        latMin - deltaLat,
                        longMin - deltaLong
                ), true);

                return true;
            }
        });
        return m;
    }`

**Comment by MKergall** [comment]
Well done! 

I'm thinking about including this behaviour directly in the standard RadiusMarkerClusterer. 
Opinions will be welcomed!

**Comment by MKergall** [comment]
Now pushed in the standard RadiusMarkerClusterer (I like that a lot!)
Behaviour by default; can be inactivated with RadiusMarkerClusterersetAnimation(false).

**Comment by Dimitry82** [comment]
Cool ;)
