### ISSUE TITLE
Add MAPS kmz

### ISSUE THREAD

**Issue by onuff** [MKergall/osmbonuspack#370]
Add maps kmz
![Screenshot_20190721-085438_Locus Map](https://user-images.githubusercontent.com/26882705/61684970-dc1f2500-ad23-11e9-90f8-aec255a584fe.jpg)

**Comment by MKergall** [comment]
"KMZ maps" is not defined in the [KML Reference](https://developers.google.com/kml/documentation/kmlreference). 

Could you clarify what you expect? Looking at your picture, this seems to be a GroundOverlay.

**Comment by onuff** [comment]
The is format for garmin and planet earth.
Yes, ground overlay.
Visibility two maps.

**Comment by onuff** [comment]
https://yadi.sk/d/7-QsGQSTIc9SXQ

**Comment by onuff** [comment]
The is format for garmin and planet earth.
Yes, ground overlay.
Visibility two maps.

**Comment by onuff** [comment]
Open

**Comment by onuff** [comment]
How can this be used?
kmz

**Comment by MKergall** [comment]
Your example uses GroundOverlay LatLonQuad, which is not supported currently in OSMBonusPack, as stated in [KML](https://github.com/MKergall/osmbonuspack/wiki/KML) page. 
Either use the LatLonBox, or wait for the next release of the lib.

**Comment by MKergall** [comment]
GroundOverlay support for LatLnQuad added, and just pushed. 
Tried successfully on your kmz file. Give it a try!

**Comment by onuff** [comment]
Ok. Very good.
