### ISSUE TITLE
Unable to build APK

### ISSUE THREAD

**Issue by MKergall** [MKergall/osmbonuspack#375]
I was trying to upgrade OSMBonusPack to osmdroid 6.1.4. Quite straightforward, it compiles and run on emulator (changes commited). 
But when trying to build the demo APK, I'm completely blocked with this error: 

_The project is using an unsupported version of Gradle.
Please point to a supported Gradle version in the project's Gradle settings or in the project's Gradle wrapper (if applicable.)_

But if I upgrade Gradle wrapper (distributionUrl), it's even worst, I get errors at compile level. 

All this Gradle stuff is a mystery for me. 
Help!!! 

P.S. I also upgraded to Android Studio 3.5.3 - I have concerns this could be the root cause.

**Comment by MKergall** [comment]
@spyhunter99 or @monsieurtanuki, 
Do you think you could help me on this one? 
This issue is blocking me to provide OBP versions updated to latest osmdroid version.

**Comment by spyhunter99** [comment]
So that's building osmdroid's demo apk or osmbonuspack's? I take a look at
it later tonight or this weekend

**Comment by monsieurtanuki** [comment]
Isn't that related to https://github.com/osmdroid/osmdroid/issues/1560?
The last time I tried I had no problems with AS 3.5.3 and `distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-bin.zip` in `gradle-wrapper.properties`.
But I don't understand anything about gradles.
Hope this helps.

**Comment by MKergall** [comment]
I had to change my PC, so, following a fresh install, I'm on AS 3.6.3. 

Direct build with no project change: build OK, then nothing happens. No way to install and launch the app. 

Upgrading to gradle:3.6.3: 
"Gradle sync failed: Minimum supported Gradle version is 5.6.4. "

Upgrading to distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
"Gradle sync failed: Cannot create variant 'android-aidl' after configuration"

SO advice for this error message: "Some of libraries does not support gradle 3.3 yet. downgrade gradle and wait for that libraries new version"

Pfffffffffffffffffffffffffffffffff !!!! What a mess!

**Comment by MKergall** [comment]
Sorry, Direct build with no project change is raising this error in Run tab: 
"Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: No outputs for the main artifact of variant: debug"

**Comment by spyhunter99** [comment]
try 3.5.3 you can still download the older versions

if you run the build from the command line, typically

    gradlew build

you can then install the apk via

    adb install path/to/your.apk

You can still attach the debugger too via the run menu, then attach to external process or something like that

**Comment by spyhunter99** [comment]
We saw that issue with the newer android studio paired with our (osmdroid)
of the ordinary build script.
If you're seeing it on osmbonuspack, maybe it's something related to that.

**Comment by MKergall** [comment]
Correction pushed - thanks to @hannesa2 
Upgrade to osmdroid 6.1.6
Android Studio 4.0 now required
