### ISSUE TITLE
Cannot create variant 'android-aidl' after configuration ':OSMBonusPack:debugApiElements' has been resolved

### ISSUE THREAD

**Issue by ghost** [MKergall/osmbonuspack#376]
Cannot create variant 'android-aidl' after configuration ':OSMBonusPack:debugApiElements' has been resolved

**Comment by MKergall** [comment]
You solved an issue? Can you create the pull request?

**Comment by Black4guy** [comment]
> Cannot create variant 'android-aidl' after configuration ':OSMBonusPack:debugApiElements' has been resolved

Issue resolved ?

**Comment by realSaeedHassani** [comment]
resolved ?

**Comment by realSaeedHassani** [comment]
Don't update your gradle! and use the same current project settings!

**Comment by MKergall** [comment]
I have the same issue. And if I don't update the gradle, I have this error: 
"Gradle sync failed: Minimum supported Gradle version is 5.6.4."
(Android Studio 3.6.3)

I feel completely trapped...

**Comment by MKergall** [comment]
Should be fixed now. 
Requiring to upgrade to Android 4.0.
