### ISSUE TITLE
Creating a walking path in park environment 

### ISSUE THREAD

**Issue by NimaaZx** [MKergall/osmbonuspack#379]
Hello. I need to draw a path or a walking path for park environment. it is better to be more natural like road in default map and add them to a park. I can use groundOverlay feature , and overlay a Path (Png Format) to map. but I want to know that is there a method or better tools for doing this job better? 

I also read a little bit about Polyline.
I implemented RoadManager but it seems used for doing different thing .

Thanks a lot.

**Comment by MKergall** [comment]
Polyline should do the job. Lot of options are possible (like dashed, or arrows). 

(ask questions on StackOverflow, please)
