### ISSUE TITLE
Caused by: org.gradle.api.resources.MissingResourceException: Could not read script 'C:\projects\kmlmoduleexample\maven.gradle' as it does not exist.

### ISSUE THREAD

**Issue by techomite** [MKergall/osmbonuspack#380]
when i am trying to add the project as module into my project. i am getting maven.gradle does not exist error.

on line 38, in OSMBonusPack\build.gradle

apply from: '../maven.gradle'

how can i solve this?

**Comment by MKergall** [comment]
assume obsolete issue.
