### ISSUE TITLE
Change ArrayList implementation of List to the List Interface

### ISSUE THREAD

**Issue by Geist5000** [MKergall/osmbonuspack#381]
I would be very happy if the functions, which have an ArrayList as argument, will get changed to an List argument.

One example is the getRoutes function of the OSRMRoadManager.

I would do it by myself, but I did not found an contribution guide so I wanted to wait for your comment

**Comment by MKergall** [comment]
In theory, good idea: user is supposed to ignore what is the underlying implementation. 
In practice, this is completely wrong. At the end, you will have to know, and this approach will oblige you to cast (not readable), and sometimes to convert (inefficient!). 
I hate that.

**Comment by Geist5000** [comment]
In my opinion and experience, the problem with using the ArrayList implementation is, that it makes the usage of this library with other ones, a pain.
Usually libraries are using the List interface, if I want to pass a List of GeoPoints, from another Library which provides a List interface, to one of your functions, I need to create a new ArrayList Object which is a created from the existing List (inefficient) or inspect the code of the library to find out which implementation is used (much effort) and cast it back.
