### ISSUE TITLE
Remove Marker from RadiusMarkerClusterer 

### ISSUE THREAD

**Issue by tvaknin** [MKergall/osmbonuspack#385]
Hi,

I found that there is no option to remove a marker from an existing RadiusMarkerClusterer.
If so, Is it possible to add this option?

Thanks,
Tal

**Comment by tvaknin** [comment]
My solution for now:

'''    public void updateCluster() {

        map.getOverlays().remove(rMarkerClusterPoints);
        rMarkerClusterPoints = new RadiusMarkerClusterer(getApplicationContext());
        Bitmap bitmap = Utils.drawableToBitmap(this);
        if(bitmap != null)
            rMarkerClusterPoints.setIcon(bitmap);
        rMarkerClusterPoints.getTextPaint().setColor(Color.BLACK);
        rMarkerClusterPoints.getTextPaint().setTextSize(12 * getResources().getDisplayMetrics().density);
        rMarkerClusterPoints.mAnchorU = Marker.ANCHOR_RIGHT;
        rMarkerClusterPoints.mAnchorV = Marker.ANCHOR_BOTTOM;
        rMarkerClusterPoints.mTextAnchorV = 0.40f;
        // copy the updated list of markers
        for (Marker marker : markerPoints)
            rMarkerClusterPoints.add(marker);
        map.getOverlays().add(rMarkerClusterPoints);

    }'''

**Comment by MKergall** [comment]
Usually, when my "model" has a change, I have a method to completely rebuild the "view" (overlays). 

You can also subclass the RadiusMarkerClusterer and implement a "remove" method. SHould be something like that:

```
	public void remove(Marker marker){
		mItems.remove(marker);
	}

```
