### ISSUE TITLE
Implementing geojson feature click listener in osmdroid

### ISSUE THREAD

**Issue by MLAndroid** [MKergall/osmbonuspack#388]
Hi,
 
I am trying to replace google maps in my android app with openstreet map to make it functional with offline map data (custom tiles).

I have a geojson string that contains several polygons. I was able to add it to my osm mapview with the help of osmbonuspack.
what I did was, I've created a kmldocument with geojson string and added it as a folderoverlay on the osm mapview, 

But now I'm stuck where I want to replace the geojson layer feature click listener in google maps with its osm alternative,
My requirement is to click on a polygon on that geojson layer, get the boundary coordinates, get the feature properties, and add a marker at its center.

**"In short, I couldn't find a comprehensive answer with an exact alternative in osmdroid for the following google maps code"**

 geoJsonLayer.setOnFeatureClickListener(new GeoJsonLayer.OnFeatureClickListener() {
                @Override
                public void onFeatureClick(final Feature feature) {
                    final List<LatLng> boundaryCoordinates = ((List<List<LatLng>>) feature.getGeometry().getGeometryObject()).get(0);
                    final LatLngBounds.Builder boundsBuilder = LatLngBounds.builder();
                    for (final LatLng boundaryCoordinate : boundaryCoordinates) {
                        boundsBuilder.include(boundaryCoordinate);
                    }
                    mMarker = mMap.addMarker(new MarkerOptions()
                            .alpha(0.0f)
                            .infoWindowAnchor(.6f, 1.0f)
                            .position(boundsBuilder.build().getCenter())
                            .title(feature.getProperty("property1"))
                            .snippet(feature.getProperty("property2")));
                    mMarker.showInfoWindow();
                }
            });

**How can I achieve this in osmdroid ?**, any help would be appreciated,   Thanks in advance

**Comment by MKergall** [comment]
In other words, you need to customize the polygon overlay, to set your own OnClickListener. 
Read this: 
https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4#132-advanced-styling-with-the-styler

**Comment by MLAndroid** [comment]
I've used styler and applied color and stroke to the polygon like this,

 @Override
    public void onPolygon(Polygon polygon, KmlPlacemark kmlPlacemark, KmlPolygon kmlPolygon) {

        polygon.getFillPaint().setColor(context.getResources().getColor(R.color.colorPrimary));   // blue color 
        polygon.getFillPaint().setStrokeWidth(3.0f);
  }

 KmlFeature.Styler myKmlStyler = new MyKmlStyler();
 FolderOverlay geoJsonOverlay = (FolderOverlay) kmlDocument.mKmlRoot.buildOverlay(osmmapView, null, myKmlStyler, kmlDocument);

and then I tried to apply the default style to it as shown below.

@Override
    public void onPolygon(Polygon polygon, KmlPlacemark kmlPlacemark, KmlPolygon kmlPolygon) {
     kmlPolygon.applyDefaultStyling(polygon, myDefaultStyle, kmlPlacemark, myKmlDocument, myOsmMapView);
  }

  **Unfortunately both the attempts failed to show the polygons.**

 but when I provide the default style directly as mentioned in the article it shows the polygons correctly. **what's wrong here ?**

 following is my geojson format,
  {
"type":"FeatureCollection",
"features":[
{
"type":"Feature",
"geometry":         {
"type":"Polygon",
"coordinates":[
[                                                                                 
[latitude,longitude].........
]
                  ]
                         },
"properties":{"fieldId":"ABCD","area":"0.63"},
"id":"iiiiii_dddd"},
},...............
]}

it doesn't have a "style" field in it.


**when default style is applied, click on a polygon shows an info window with the information I need(area, field id), is it possible to add a click listener on this window, if `it's possible, that'll do it for me.**

**Comment by vkanarola** [comment]
Hi @Deepu-MobAppDeveloper  Thank you . That was very helpful .
Could you please share details of naviagtion management if you have managed ?
As from geoJson file I am not able to create route manager and not able to do further routing process.
