### ISSUE TITLE
Fatal Exception: java.lang.StackOverflowError stack size 8MB

### ISSUE THREAD

**Issue by erizoo** [MKergall/osmbonuspack#391]
Good day. I get a lot of crashes with such a decoding.
Could you tell me what it might be?

Fatal Exception: java.lang.StackOverflowError
stack size 8MB
org.osmdroid.views.Projection.<init> (Projection.java:45)
org.osmdroid.views.Projection.<init> (Projection.java:65)
org.osmdroid.views.MapView.getProjection (MapView.java:358)
org.osmdroid.views.MapView.setExpectedCenter (MapView.java:1809)
org.osmdroid.views.MapView.setExpectedCenter (MapView.java:1823)
org.osmdroid.views.MapView.setZoomLevel (MapView.java:480)
org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate (MapController.java:520)
android.animation.ValueAnimator.animateValue (ValueAnimator.java:1547)
android.animation.ValueAnimator.end (ValueAnimator.java:1133)
org.osmdroid.views.MapController.animateTo (MapController.java:167)
org.osmdroid.views.MapController.animateTo (MapController.java:137)
org.osmdroid.views.MapController.animateTo (MapController.java:183)
org.osmdroid.views.MapController.animateTo (MapController.java:129)
org.osmdroid.views.MapView.setZoomLevel (MapView.java:492)
org.osmdroid.views.MapController$MapAnimatorListener.onAnimationUpdate (MapController.java:520)

**Comment by MKergall** [comment]
Would need some context: code sample, or application used? Versions?
