### ISSUE TITLE
MAPBOX_ACCESS_TOKEN is not working 

### ISSUE THREAD

**Issue by tvaknin** [MKergall/osmbonuspack#393]
Updated tokens of MAPBOX are not supported by osmdroid/osmbonuspack
Tiles are not loaded at all with MAPBOX's **new** tokens.

I used the same configuration as on this project:

        OnlineTileSourceBase MAPBOXSATELLITELABELLED = new MapBoxTileSource("MapBoxSatelliteLabelled", 1, 19, 256, ".png");
        ((MapBoxTileSource) MAPBOXSATELLITELABELLED).retrieveAccessToken(this);
        ((MapBoxTileSource) MAPBOXSATELLITELABELLED).retrieveMapBoxMapId(this);
        TileSourceFactory.addTileSource(MAPBOXSATELLITELABELLED);

_AndoridManifest.xml_

        <meta-data
            android:name="MAPBOX_MAPID"
            android:value="mapbox.streets-satellite" />
        <meta-data
            android:name="MAPBOX_ACCESS_TOKEN"
            android:value="???????????????????????????????????????????????????????????????????" />

**Comment by MKergall** [comment]
What do you call  "MAPBOX's new tokens" ? 
MAPBOX changed their access system?

**Comment by tvaknin** [comment]
I mean, if you create a new token from MAPBOX, they provide some tokens that are not compatible with osmdorid.

I guess it's working with OSM-NAVIGATOR only because it uses some old token that we cannot achieve now from MAPBOX.

**Comment by MKergall** [comment]
"Old" token was just a string. 
I just had a look (https://docs.mapbox.com/help/glossary/access-token), I've not noticed any change: access token is still a string. 

Are you sure you defined properly the scope of your token? For Raster tiles? 
And the tileset id in your app? 

(note that this is an osmdroid issue, as MapBoxTileSource is part of osmdroid repo)

**Comment by tvaknin** [comment]
Yes, it's still String, but the issue is not about the type of token but about what MAPBOX response for each token.
Try to generate a new token from MAPBOX and use it to see the issue.

Regarding the scope, it's on STYLES:TILES with all the default public scopes.
tileset id  is the same as OSM NAVIGATOR: "mapbox.streets-satellite" 

Correct, I should post it on osmdroid repo. 

Thanks allot.

**Comment by tvaknin** [comment]
using "mapbox.mapbox-streets-v8" instead of "mapbox.streets-satellite" solved the issue.**

**Comment by tazefikirler** [comment]
hello previously working codes are working on mapbox satellite API26 (android 8) but **mapbox satellite API29 (android 10) does not work,** is there a solution to this? or **how to fix mapbox satellite**

**Comment by MKergall** [comment]
@tvaknin Effectively, we have an issue with MapBox Satellite:
"mapbox.mapbox-streets-v8" gives names only, unusable. 
"mapbox.satellite" gives satellite image without names and roads. 

Mapbox Studio seems to be working by combining multiples images as layers. 

I ask them.
