### ISSUE TITLE
How to fix cluster icon bug [Answer]

### ISSUE THREAD

**Issue by UrbanSide** [MKergall/osmbonuspack#394]
If you have this bug too
![image](https://user-images.githubusercontent.com/26259129/96652554-d60d5f00-133f-11eb-8ae0-f79494489fba.png)
You need this code:
`mPoiMarkers.setIcon(getBitmapFromVectorDrawable(this,R.drawable.marker_cluster));`
And:
```
public static Bitmap getBitmapFromVectorDrawable(Context context, int drawableId) {
        Drawable drawable = AppCompatResources.getDrawable(context, drawableId);
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            drawable = (DrawableCompat.wrap(drawable)).mutate();
        }

        Bitmap bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(),
                drawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
        drawable.draw(canvas);

        return bitmap;
    }
```
And all work!
![image](https://user-images.githubusercontent.com/26259129/96652663-0f45cf00-1340-11eb-8fcc-7c4b49d56e06.png)

**Comment by UrbanSide** [comment]
I hope I was able to help those who have the same problem.

**Comment by ryancornia** [comment]
Thank you, I was just digging in to try and figure this out!

**Comment by UrbanSide** [comment]
> Thank you, I was just digging in to try and figure this out!

I'm glad that at least someone helped)

**Comment by MKergall** [comment]
@UrbanSide 
It depends on the Android version used?
Do you think a fix should be set right inside the lib, to avoid this issue? 
Feel free to push a PR, if relevant.

**Comment by UrbanSide** [comment]
> @UrbanSide
> It depends on the Android version used?
> Do you think a fix should be set right inside the lib, to avoid this issue?
> Feel free to push a PR, if relevant.

I gave it out as a way that helped me)I do not understand whether it is necessary to implement something and somewhere

**Comment by MKergall** [comment]
Got the same when upgrading SDK. Your fix is working. 
=> getBitmapFromVectorDrawable method added in BonusPackHelper, and used in the tutorial.
