### ISSUE TITLE
How to replace infowindow

### ISSUE THREAD

**Issue by KatharosMelancho** [MKergall/osmbonuspack#395]
How to replace infowindow or bubble for layers after kml import?

`KmlDocument Forest_Boundary_arhangelsk; //Общий слой, подложка для карты Архангельска
        Forest_Boundary_arhangelsk = new KmlDocument();
        Forest_Boundary_arhangelsk.parseKMLStream(getResources().openRawResource(R.raw.forest_boundary_arhangelsk), null);
        FolderOverlay kmlOverlay_forest_boundary_arhangelsk = (FolderOverlay)Forest_Boundary_arhangelsk.mKmlRoot.buildOverlay(mapView, null, null,Forest_Boundary_arhangelsk);
        mapView.getOverlays().add(1,kmlOverlay_forest_boundary_arhangelsk);`

**Comment by MKergall** [comment]
Using the KML Styler inside buildOverlay. Read this carefully: 
https://github.com/MKergall/osmbonuspack/wiki/Tutorial_4#132-advanced-styling-with-the-styler
