### ISSUE TITLE
How to get Max speed limit 

### ISSUE THREAD

**Issue by amlan007** [MKergall/osmbonuspack#401]
I am using OSRMRoadManager 
i am getting the road through OSRMRoadManager.getRoads:http://router.project-osrm.org/route/v1/driving/105.8680712896,20.9947322000;105.8922453000,21.0393411000?alternatives=true&overview=full&steps=true

is there any API through which i can get maximum speed limits between two node pints ?

**Comment by MKergall** [comment]
Questions => on StackOverflow please
