### ISSUE TITLE
map not loading on android 11 devices 

### ISSUE THREAD

**Issue by amlan007** [MKergall/osmbonuspack#403]
i have added the below code to oncreate()

    IConfigurationProvider osmConf = Configuration.getInstance();
    File basePath = new File(getCacheDir().getAbsolutePath(), "osmdroid");
    osmConf.setOsmdroidBasePath(basePath);
    File tileCache = new File(osmConf.getOsmdroidBasePath().getAbsolutePath(), "tile");
    osmConf.setOsmdroidTileCache(tileCache);
    Configuration.getInstance().setUserAgentValue(userAgent);
and build.gradle config is as below

    minSdkVersion 16
    targetSdkVersion 28
also in AndroidManifest.xml

android:requestLegacyExternalStorage="true" and

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
still map is not loading
please help us

**Comment by eclectice** [comment]
Refer osmdroid/osmdroid#1743
