### ISSUE TITLE
osrm routing default backend url change

### ISSUE THREAD

**Issue by datendelphin** [MKergall/osmbonuspack#406]
Hi

I'm one of the admins of the fossgis routing server, which is currently behind https://router.project-osrm.org. We intend to shut down that domain, as that was previously run by someone else and the terms of service have changed. OsmBonusPack/1 is the largest user currently. So two things I would like to ask:

* Switch to using routing.openstreetmap.de/routed-car and maybe even include the two other profiles (bike and foot)
* As I understand it, osmbonuspack is a library incorporated into other applications. Include setting the user agent to the application name in the tutorial. We would appreciate if we see less of the generic OsmBonusPack/1. commercial usage is not allowed if routing is a core part of the product, so we might need to enforce this in the future with bans if the load gets too high. Having the generic user agent might ban legitimate applications in collateral damage.

Thank you for your efforts. It seems osmbonuspack is doing a good job in making the routing server accessible, even if we don't know for what currently.

**Comment by MKergall** [comment]
Hi @datendelphin, 

Message received! 
- I moved the service to routing.openstreetmap.de
- I removed the default user agent, so each lib user will have to define his own user agent
The change on figures will be slow, depending on: lib-users upgrading their app, and then end-users updating their app. 

I also added a method to easily choose the 2 other profiles. Thanks for the information, that's a great improvement. 

I'm really surprised to discover that OsmBonusPack/1 is your largest user (I suppose this is excluding openstreetmap.org Web site). Could you provide some figures? 

Thanks a lot for your impressive work. OSRM rocks!

**Comment by MKergall** [comment]
Message to developers using OSRMRoadManager: 
Upgrade your OSMBonusPack lib to https://github.com/MKergall/osmbonuspack/releases/tag/6.7.0

**Comment by datendelphin** [comment]
It is the biggest user as seen relatively to other distinct users. I made some statistics recently. The biggest portion by far is unfortunately unidentifiable because no referrer or user agent is sent.
Of about 8M Requests a day, 1M are with no user agent or referrer, 1M with no referrer but with a user agent of a specific iOS browser version, and about 0.75M are OsmBonusPack/1 on third place.

openstreetmap.org is a lot less at about 50k, but I guess that is explainable as using that library on a mobile device might generate lots of queries during one journey, constantly updating the remainder of the route.

Thank you for the quick response and including the other profiles as well.
