### ISSUE TITLE
getting details of road intersection along a calculated road

### ISSUE THREAD

**Issue by GumiBear93** [MKergall/osmbonuspack#409]
I'm fairly new to this library, and currently sinking my teeth into the tutorial. I want to use this library for an university project, and have the following idea/ vision:

I mainly want to give "grades" to routes, by calculating a sort of difficulty for each route. For this I'm planning to use a route complexity analysis by K.-F. Richter and M. Duckham. Simply put, the idea is to evaluate a routes' simplicity by scoring its crossings and turns - walking straight at an intersection is considered easier than making a turn at a T-intersection or any other kind of complex intersection (see an example in the attached image).
![Richter and Duckham Complexity](https://user-images.githubusercontent.com/73489816/127407054-c04f8a28-063d-41a2-9df3-39661fc4f045.png)

Can someone point me into the right direction to find the types of turns and intersections along the calculated route? that would be much appreciated.
Thank you for offering such an amazing open source library.

**Comment by MKergall** [comment]
1) Such questions should be asked on StackOverflow. 
2) You will have to dig in the API of the routing service you want to use (OSRM, or GraphHopper), as each one has its own definition of types of turns/intersections.
