### ISSUE TITLE
Navigation for geoJson loaded path

### ISSUE THREAD

**Issue by vkanarola** [MKergall/osmbonuspack#414]
Hi , I am integrating this library for one of my project. I have geoJson file from which I have loaded path between source and destination . Now i would like to show navigation between path with details . I am not able to find a way to do the same .Can any one please help ?

**Comment by MKergall** [comment]
Request for help: on StackOverflow please.

**Comment by vkanarola** [comment]
Could you please explain some details here if you have idea about it .

**Comment by MKergall** [comment]
Your need, from your comment in #90 :

"I am using open route services direction api to get direction between 2 points . I am getting data in geoJson formate which include waypoints and all other details ,. I am successfully able to show route on osmdroid map . Now I want navigation on that route with details (like turn left ) .How Can I achieve this?

Here is geoJson data which I have .
https://docs.google.com/document/d/15nBB8wbs1UuFE0UJHL74WuTKGlLuRPqpmLu-VrF7YNQ/edit?usp=sharing"

**Comment by MKergall** [comment]
Recommended solution: 
Look how OsmBonusPack RoadManagers are written - particularly [OSRMRouteManager](https://github.com/MKergall/osmbonuspack/blob/master/OSMBonusPack/src/main/java/org/osmdroid/bonuspack/routing/OSRMRoadManager.java). 
And then write your own OpenRouteServiceRoadManager. 

An alternative if this is too complex for you: don't use Openrouteservice, use OSRM or GraphHopper services instead, as everything is ready to use in OsmBonusPack.

**Comment by vkanarola** [comment]
Have you managed anything like this before?

**Comment by MKergall** [comment]
Of course: OBP contains implementation of access to four route services. 
Maybe you should start here: https://github.com/MKergall/osmbonuspack/wiki/Tutorial_1

**Comment by vkanarola** [comment]
Yes I have gone through all of this . My question is this route managers will create their own paths and in my case I have all geo coordinates through which I have to create route.

**Comment by MKergall** [comment]
You asked a question: "I am successfully able to show route on osmdroid map . Now I want navigation on that route with details (like turn left ) .How Can I achieve this?". 
I gave you the answer.
