### ISSUE TITLE
Lines not connected at nodes

### ISSUE THREAD

**Issue by Zimbelstern** [MKergall/osmbonuspack#417]
When I import a geojson string containing a route and drawing this route as described in Tutorial_4, the lines of this route are not connected at the nodes (i.e. the provided coordinates). You can clearly see separate pieces at a line width of 10f and above.
Is this the supposed behaviour? Is there any way I can change this?

**Comment by MKergall** [comment]
Could you provide a geojson sample and a screen copy?

**Comment by MKergall** [comment]
Oh I see. Yes, known behaviour. 
And yes, I think there are some options on Polylines to round vertices.

**Comment by zimbelstern** [comment]
Could you tell me which method I need to call or which object to modify? I was looking at the osmdroid samples (i.e. in the "Show advanced polyline styles" section you can clearly see round vertices) and I was digging into the javadoc and trying to modify my Style object but however didn't manage to indentify the correct property. :(

**Comment by MKergall** [comment]
I don't know... Ask on StackOverflow?
