### ISSUE TITLE
文件管理器打开kmz文件报错

### ISSUE THREAD

**Issue by Tamarackwyh** [MKergall/osmbonuspack#420]
运行代码：
 kmlKmzDocument = new KmlDocument();
 kmlKmzDocument .parseKMZFile(f);
错误信息：
TinkerUncaughtHandler catch exception:java.lang.StackOverflowError: stack size 8192KB
运行设备及系统：
HONOR V30/HarmonyOS 2.0.0

补充：
同一个kmz文件在别的手机上一切正常显示
用了Redmi Note11、小米5S Plus、nova7测试过都是正常显示

**Comment by MKergall** [comment]
In english only please.
