### ISSUE TITLE
Help with offline geocoding/navigation with geojson

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MKergall/osmbonuspack#90]
```
Hi,

This is not an issue.
I need a help/hints for working with offline maps.

The application is using offline map from mbtiles created using MOBAC for a 
small area.I have the geojson files with POIs and waypoints. which is rendered 
nicely using osmbonuspack in the app.
Now i need some kind of ability provide navigation within the area.

any help is much appreciated.

Thanks,
Safeer
```

Original issue reported on code.google.com by `safeer....@gmail.com` on 24 Oct 2014 at 4:24

**Comment by vkanarola** [comment]
Hi @GoogleCodeExporter  Could you please help me for this type of query .
I am using open route services direction api to get direction between 2 points . I am getting data in geoJson formate which include waypoints and all other details ,. I am successfully able to show route on osmdroid map . Now I want navigation on that route with details (like turn left ) .How Can I achieve this?
